-- Sample Co tables for The Fourth Sheet mock-ups. Generated by tools/sample_data.py.
-- Works in Azure SQL / SQL Server and PostgreSQL. Load each CSV into the table of the same name.
-- Create (and load) the dim_ tables before the fact_ tables: the facts reference them.

-- Calendar, 1 May to 31 Oct 2026: the drill-down path from financial year to quarter, month, week and day, with Brisbane working days and public holidays. date_key = yyyymmdd; weeks start Monday.
CREATE TABLE dim_date (
    date_key INT PRIMARY KEY,
    calendar_date DATE NOT NULL,
    day_of_month INT,
    day_name VARCHAR(3),
    day_of_week INT,
    is_weekend INT,
    is_working_day INT,
    public_holiday VARCHAR(60),
    week_start DATE,
    iso_week INT,
    month_key VARCHAR(7),
    month_name VARCHAR(8),
    calendar_quarter VARCHAR(7),
    financial_year VARCHAR(6),
    fy_month_no INT,
    fy_quarter VARCHAR(10)
);

-- The three sample organisations.
CREATE TABLE dim_org (
    org_id VARCHAR(10) PRIMARY KEY,
    toggle_name VARCHAR(30),
    legal_name VARCHAR(60),
    sector VARCHAR(20),
    about VARCHAR(300)
);

-- Every statement line for each organisation (P&L, balance sheet, cash flow). is_postable = daily facts post to it; the rest are subtotals and totals.
CREATE TABLE dim_account (
    account_id INT PRIMARY KEY,
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    statement VARCHAR(20),
    section VARCHAR(40),
    line VARCHAR(60),
    line_level VARCHAR(10),
    line_order INT,
    is_postable INT
);

-- Trades jobs: maintenance contracts (one id per customer, billed monthly), installations and call-outs.
CREATE TABLE dim_job (
    job_id VARCHAR(10) PRIMARY KEY,
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    job_type VARCHAR(30),
    description VARCHAR(80)
);

-- Services client engagements. rate_or_fee: hourly rate for projects, fixed fee for retainers (monthly) and training.
CREATE TABLE dim_engagement (
    engagement_id VARCHAR(10) PRIMARY KEY,
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    engagement_type VARCHAR(20),
    description VARCHAR(80),
    hourly_rate INT,
    fixed_fee INT,
    payment_days INT
);

-- Not-for-profit grants.
CREATE TABLE dim_grant (
    grant_id VARCHAR(10) PRIMARY KEY,
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    program VARCHAR(60),
    funder VARCHAR(60),
    grant_total INT,
    start_date DATE,
    end_date DATE
);

-- Daily P&L postings, Aug-Sep 2026 (income +, costs -). Grouped by month they equal every line of the P&L to the dollar. Tagged with the job, engagement or grant where there is one.
CREATE TABLE fact_gl_daily (
    date_key INT REFERENCES dim_date(date_key),
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    account_id INT REFERENCES dim_account(account_id),
    amount INT,
    job_id VARCHAR(10),
    engagement_id VARCHAR(10),
    grant_id VARCHAR(10)
);

-- Daily cash movements by cash-flow line, Aug-Sep 2026 (in +, out -). Customer receipts are the actual invoice payment dates.
CREATE TABLE fact_cash_daily (
    date_key INT REFERENCES dim_date(date_key),
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    account_id INT REFERENCES dim_account(account_id),
    amount INT
);

-- Closing cash at bank and unpaid customer invoices at the end of every day, Aug-Sep 2026. Month-end values equal the balance sheet.
CREATE TABLE fact_balance_daily (
    date_key INT REFERENCES dim_date(date_key),
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    cash_at_bank INT,
    unpaid_invoices INT
);

-- Hours by day against each trades job or services engagement, Aug-Sep 2026 (half-hour units). Add up to the job and engagement hours.
CREATE TABLE fact_timesheet_daily (
    date_key INT REFERENCES dim_date(date_key),
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    job_id VARCHAR(10),
    engagement_id VARCHAR(10),
    hours DECIMAL(6,1)
);

-- Each trades job by month, May-Sep 2026. Labour cost = hours x $68. Aug and Sep add up to the P&L.
CREATE TABLE fact_job_month (
    month_key VARCHAR(7),
    job_id VARCHAR(10) REFERENCES dim_job(job_id),
    invoice_date DATE,
    revenue INT,
    materials INT,
    subcontractors INT,
    tech_hours DECIMAL(6,1),
    labour_cost INT,
    gross_profit INT
);

-- Each services engagement by month, Aug-Sep 2026. Consultant time costed at $60/hour; wip_closing = unbilled project time at month end.
CREATE TABLE fact_engagement_month (
    month_key VARCHAR(7),
    engagement_id VARCHAR(10) REFERENCES dim_engagement(engagement_id),
    hours DECIMAL(6,1),
    revenue INT,
    billed INT,
    contractors INT,
    consultant_time_cost INT,
    contribution INT,
    wip_closing INT
);

-- Every customer invoice, May-Sep 2026, with the date it was paid. Unpaid at a date = debtors at that date.
CREATE TABLE fact_invoice (
    org_id VARCHAR(10) REFERENCES dim_org(org_id),
    invoice_id VARCHAR(20),
    job_id VARCHAR(10),
    engagement_id VARCHAR(10),
    invoice_date DATE,
    paid_date DATE,
    amount INT
);

-- Grant payment schedule.
CREATE TABLE fact_grant_instalment (
    grant_id VARCHAR(10) REFERENCES dim_grant(grant_id),
    date_key INT REFERENCES dim_date(date_key),
    amount INT
);

-- Each grant at 30 Sep 2026: received, spent, budget to date, still to spend. balance = received - spent (+ in advance, - receivable).
CREATE TABLE fact_grant_position (
    grant_id VARCHAR(10) REFERENCES dim_grant(grant_id),
    date_key INT,
    received_to_date INT,
    spent_to_date INT,
    budget_to_date INT,
    spend_vs_budget_pct DECIMAL(6,1),
    still_to_spend INT,
    balance INT,
    months_left INT
);

-- Warehouse screen: today's despatch KPIs.
CREATE TABLE display_warehouse_kpis (
    kpi VARCHAR(43),
    value INT,
    target INT,
    unit VARCHAR(30)
);

-- Warehouse screen: lines picked per hour today (sums to 142).
CREATE TABLE display_warehouse_picks_by_hour (
    pick_date DATE,
    hour_start VARCHAR(25),
    lines_picked INT
);

-- Warehouse screen: overdue inbound deliveries.
CREATE TABLE display_warehouse_overdue_deliveries (
    supplier VARCHAR(30),
    item VARCHAR(30),
    days_late INT
);

-- Reception screen: headline numbers (October 2026).
CREATE TABLE display_reception_kpis (
    kpi VARCHAR(37),
    value INT,
    of_total INT,
    unit VARCHAR(27),
    period VARCHAR(33)
);

-- Reception screen: orders shipped by week.
CREATE TABLE display_reception_orders_by_week (
    week_start DATE,
    week_label VARCHAR(22),
    orders_shipped INT
);

-- Reception screen: today's list.
CREATE TABLE display_reception_today (
    item VARCHAR(42),
    count INT
);

-- Boardroom screen: management pack KPIs, year to date October 2026.
CREATE TABLE display_boardroom_kpis (
    kpi VARCHAR(38),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(54)
);

-- Boardroom screen: revenue by month, $k. Actual Jan-Oct (sums to 4,820), budget Jan-Dec (Jan-Oct sums to 4,670), forecast Oct-Dec.
CREATE TABLE display_boardroom_revenue_monthly (
    month DATE,
    actual_aud_k INT,
    budget_aud_k INT,
    forecast_aud_k INT
);

-- Boardroom screen: what a sale really costs, as a share of revenue (sums to 100).
CREATE TABLE display_boardroom_cost_of_sale (
    component VARCHAR(34),
    pct_of_revenue DECIMAL(14,2)
);

-- Sales report: KPIs for October 2026.
CREATE TABLE report_sales_kpis (
    kpi VARCHAR(37),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(47)
);

-- Sales report: revenue by month (chart shows $k).
CREATE TABLE report_sales_revenue_monthly (
    month DATE,
    revenue_aud INT
);

-- Sales report: top customers, October 2026.
CREATE TABLE report_sales_top_customers (
    customer VARCHAR(30),
    revenue_aud INT,
    change_vs_last_year_pct INT,
    cancellation_pct DECIMAL(14,2)
);

-- Sales report: cancelled orders by reason (47 of 1,248 = 3.8%).
CREATE TABLE report_sales_cancellations_by_reason (
    reason VARCHAR(33),
    orders_cancelled INT
);

-- Purchasing report: KPIs for October 2026.
CREATE TABLE report_purchasing_kpis (
    kpi VARCHAR(40),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(48)
);

-- Purchasing report: on-time delivery by supplier.
CREATE TABLE report_purchasing_on_time_by_supplier (
    supplier VARCHAR(30),
    on_time_pct INT
);

-- Purchasing report: all 14 late purchase orders (the preview shows the worst 7).
CREATE TABLE report_purchasing_late_orders (
    po_number VARCHAR(27),
    supplier VARCHAR(30),
    days_late INT,
    value_aud INT
);

-- Purchasing report: unit cost index by month (May = 100).
CREATE TABLE report_purchasing_unit_cost_index (
    month DATE,
    freight_index INT,
    steel_index INT
);

-- Payroll and overtime report: KPIs for October 2026.
CREATE TABLE report_payroll_kpis (
    kpi VARCHAR(34),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(51)
);

-- Payroll and overtime report: overtime hours by week (sums to 412).
CREATE TABLE report_payroll_overtime_by_week (
    week_start DATE,
    week_label VARCHAR(22),
    overtime_hours INT
);

-- Payroll and overtime report: overtime, jobs and labour per job by team.
CREATE TABLE report_payroll_by_team (
    team VARCHAR(31),
    overtime_hours INT,
    jobs_completed INT,
    labour_per_job_aud INT
);

-- Payroll and overtime report: hours worked vs jobs completed, indexed (W1 = 100).
CREATE TABLE report_payroll_hours_vs_jobs (
    week_start DATE,
    week_label VARCHAR(22),
    hours_index INT,
    jobs_index INT
);

-- Management pack template: profit and loss, actual against budget, October 2026. Variance is favourable when positive.
CREATE TABLE template_pnl (
    month DATE,
    line VARCHAR(32),
    actual_aud INT,
    budget_aud INT,
    variance_aud INT,
    variance_pct DECIMAL(14,2),
    what_drove_it VARCHAR(61)
);

-- Home-page dashboard: month-end P&L / income and expenditure, balance sheet and cash flow for the three sample organisations, September 2026 and August 2026, whole dollars. Costs and outflows are negative. level = detail/subtotal/total/key.
CREATE TABLE model_statements (
    org VARCHAR(28),
    statement_key VARCHAR(23),
    statement VARCHAR(58),
    line_order INT,
    line VARCHAR(65),
    level VARCHAR(28),
    period VARCHAR(27),
    amount_aud INT
);

-- Home-page dashboard: the fourth-sheet KPI tiles for September 2026, as displayed.
CREATE TABLE model_fourth_sheet_kpis (
    org VARCHAR(28),
    kpi VARCHAR(53),
    value VARCHAR(32),
    comparison VARCHAR(50)
);

-- Home-page dashboard: the assumptions each sample organisation's statements are built from.
CREATE TABLE model_assumptions (
    org VARCHAR(28),
    assumption_group VARCHAR(43),
    assumption VARCHAR(49),
    value VARCHAR(174)
);
