-- Sample Co tables for The Fourth Sheet mock-ups. Generated by tools/sample_data.py.
-- Works in Azure SQL / SQL Server and PostgreSQL. Load each CSV into the table of the same name.

-- Warehouse screen: today's despatch KPIs.
CREATE TABLE display_warehouse_kpis (
    kpi VARCHAR(43),
    value INT,
    target INT,
    unit VARCHAR(30)
);

-- Warehouse screen: lines picked per hour today (sums to 142).
CREATE TABLE display_warehouse_picks_by_hour (
    pick_date DATE,
    hour_start VARCHAR(25),
    lines_picked INT
);

-- Warehouse screen: overdue inbound deliveries.
CREATE TABLE display_warehouse_overdue_deliveries (
    supplier VARCHAR(30),
    item VARCHAR(30),
    days_late INT
);

-- Reception screen: headline numbers (October 2026).
CREATE TABLE display_reception_kpis (
    kpi VARCHAR(37),
    value INT,
    of_total INT,
    unit VARCHAR(27),
    period VARCHAR(33)
);

-- Reception screen: orders shipped by week.
CREATE TABLE display_reception_orders_by_week (
    week_start DATE,
    week_label VARCHAR(22),
    orders_shipped INT
);

-- Reception screen: today's list.
CREATE TABLE display_reception_today (
    item VARCHAR(42),
    count INT
);

-- Boardroom screen: management pack KPIs, year to date October 2026.
CREATE TABLE display_boardroom_kpis (
    kpi VARCHAR(38),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(54)
);

-- Boardroom screen: revenue by month, $k. Actual Jan-Oct (sums to 4,820), budget Jan-Dec (Jan-Oct sums to 4,670), forecast Oct-Dec.
CREATE TABLE display_boardroom_revenue_monthly (
    month DATE,
    actual_aud_k INT,
    budget_aud_k INT,
    forecast_aud_k INT
);

-- Boardroom screen: what a sale really costs, as a share of revenue (sums to 100).
CREATE TABLE display_boardroom_cost_of_sale (
    component VARCHAR(34),
    pct_of_revenue DECIMAL(14,2)
);

-- Sales report: KPIs for October 2026.
CREATE TABLE report_sales_kpis (
    kpi VARCHAR(37),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(47)
);

-- Sales report: revenue by month (chart shows $k).
CREATE TABLE report_sales_revenue_monthly (
    month DATE,
    revenue_aud INT
);

-- Sales report: top customers, October 2026.
CREATE TABLE report_sales_top_customers (
    customer VARCHAR(30),
    revenue_aud INT,
    change_vs_last_year_pct INT,
    cancellation_pct DECIMAL(14,2)
);

-- Sales report: cancelled orders by reason (47 of 1,248 = 3.8%).
CREATE TABLE report_sales_cancellations_by_reason (
    reason VARCHAR(33),
    orders_cancelled INT
);

-- Purchasing report: KPIs for October 2026.
CREATE TABLE report_purchasing_kpis (
    kpi VARCHAR(40),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(48)
);

-- Purchasing report: on-time delivery by supplier.
CREATE TABLE report_purchasing_on_time_by_supplier (
    supplier VARCHAR(30),
    on_time_pct INT
);

-- Purchasing report: all 14 late purchase orders (the preview shows the worst 7).
CREATE TABLE report_purchasing_late_orders (
    po_number VARCHAR(27),
    supplier VARCHAR(30),
    days_late INT,
    value_aud INT
);

-- Purchasing report: unit cost index by month (May = 100).
CREATE TABLE report_purchasing_unit_cost_index (
    month DATE,
    freight_index INT,
    steel_index INT
);

-- Payroll and overtime report: KPIs for October 2026.
CREATE TABLE report_payroll_kpis (
    kpi VARCHAR(34),
    value DECIMAL(14,2),
    unit VARCHAR(27),
    comparison VARCHAR(51)
);

-- Payroll and overtime report: overtime hours by week (sums to 412).
CREATE TABLE report_payroll_overtime_by_week (
    week_start DATE,
    week_label VARCHAR(22),
    overtime_hours INT
);

-- Payroll and overtime report: overtime, jobs and labour per job by team.
CREATE TABLE report_payroll_by_team (
    team VARCHAR(31),
    overtime_hours INT,
    jobs_completed INT,
    labour_per_job_aud INT
);

-- Payroll and overtime report: hours worked vs jobs completed, indexed (W1 = 100).
CREATE TABLE report_payroll_hours_vs_jobs (
    week_start DATE,
    week_label VARCHAR(22),
    hours_index INT,
    jobs_index INT
);

-- Management pack template: profit and loss, actual against budget, October 2026. Variance is favourable when positive.
CREATE TABLE template_pnl (
    month DATE,
    line VARCHAR(32),
    actual_aud INT,
    budget_aud INT,
    variance_aud INT,
    variance_pct DECIMAL(14,2),
    what_drove_it VARCHAR(61)
);

-- Home-page dashboard: P&L / income and expenditure, balance sheet and cash flow for the three sample organisations, FY2026 and FY2025, $'000. Costs and outflows are negative. level = detail/subtotal/total/key.
CREATE TABLE model_statements (
    org VARCHAR(28),
    statement VARCHAR(44),
    line_order INT,
    line VARCHAR(56),
    level VARCHAR(28),
    financial_year VARCHAR(26),
    amount_aud_k INT
);

-- Home-page dashboard: the fourth-sheet KPI tiles, as displayed.
CREATE TABLE model_fourth_sheet_kpis (
    org VARCHAR(28),
    kpi VARCHAR(48),
    value VARCHAR(30),
    comparison VARCHAR(41)
);

-- Home-page dashboard: monthly drivers behind the fourth-sheet charts, FY2026 (sum to the annual figures).
CREATE TABLE model_monthly (
    org VARCHAR(28),
    financial_year VARCHAR(26),
    month VARCHAR(23),
    measure VARCHAR(35),
    value INT
);

-- Home-page dashboard: the assumptions each sample organisation's statements are built from.
CREATE TABLE model_assumptions (
    org VARCHAR(28),
    assumption_group VARCHAR(42),
    assumption VARCHAR(56),
    value VARCHAR(168)
);
