/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.
   Don't edit by hand: change the assumptions in financial_model.py and re-run.
   All figures are invented sample data, in whole dollars: September 2026 vs August 2026. */
window.FOURTH_SHEET_DASHBOARD = {
 "generated": "2026-10-06",
 "orgs": [
  {
   "id": "trades",
   "toggle": "SME · trades",
   "name": "Sample Electrical & Air Pty Ltd",
   "about": "An electrical and air-conditioning contractor in Brisbane: maintenance contracts, installations and call-outs. 7 technicians, 3 office staff.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss, September 2026",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Maintenance contracts (14)",
       "level": "detail",
       "values": [
        40500,
        40500
       ],
       "note": null
      },
      {
       "label": "Installations (jobs)",
       "level": "detail",
       "values": [
        130700,
        109600
       ],
       "note": null
      },
      {
       "label": "Call-outs and repairs",
       "level": "detail",
       "values": [
        31137,
        28907
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        202337,
        179007
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Materials",
       "level": "detail",
       "values": [
        -64860,
        -51530
       ],
       "note": null
      },
      {
       "label": "Subcontractors",
       "level": "detail",
       "values": [
        -13200,
        -9300
       ],
       "note": null
      },
      {
       "label": "Technician wages (incl. super)",
       "level": "detail",
       "values": [
        -54600,
        -54600
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -132660,
        -115430
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        69677,
        63577
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Office and admin wages",
       "level": "detail",
       "values": [
        -21900,
        -21900
       ],
       "note": null
      },
      {
       "label": "Marketing",
       "level": "detail",
       "values": [
        -7600,
        -8400
       ],
       "note": null
      },
      {
       "label": "Vehicles and fuel",
       "level": "detail",
       "values": [
        -8300,
        -7900
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -7000,
        -7000
       ],
       "note": null
      },
      {
       "label": "Insurance",
       "level": "detail",
       "values": [
        -3000,
        -3000
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -2300,
        -2300
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -3900,
        -3600
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -54000,
        -54100
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        15677,
        9477
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -4500,
        -4300
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -1080,
        -1100
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        10097,
        4077
       ],
       "note": null
      },
      {
       "label": "Income tax provision (25%)",
       "level": "subtotal",
       "values": [
        -2524,
        -1019
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        7573,
        3058
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        59746,
        65263
       ],
       "note": null
      },
      {
       "label": "Trade debtors (unpaid invoices)",
       "level": "detail",
       "values": [
        151063,
        129819
       ],
       "note": null
      },
      {
       "label": "Materials on hand",
       "level": "detail",
       "values": [
        66000,
        66000
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        21000,
        21000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        297809,
        282082
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        255200,
        247700
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        553009,
        529782
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors (bills due next month)",
       "level": "detail",
       "values": [
        78060,
        60830
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        106000,
        105100
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        35043,
        32519
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        219103,
        198449
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        95000,
        100000
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        314103,
        298449
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        238906,
        231333
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        10000,
        10000
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        228906,
        221333
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        238906,
        231333
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers (invoices paid)",
       "level": "detail",
       "values": [
        181093,
        156273
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers",
       "level": "detail",
       "values": [
        -92930,
        -97510
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -75600,
        -75400
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -1080,
        -1100
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next PAYG instalment is due in October."
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        11483,
        -17737
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        -12000,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -12000,
        0
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -5000,
        -5000
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -5000,
        -5000
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -5517,
        -22737
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        65263,
        88000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        59746,
        65263
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Gross margin, September",
      "value": "34.4%",
      "sub": "▼ from 35.5% in Aug",
      "cls": "bad",
      "spine": true,
      "support": {
       "title": "Gross margin",
       "formula": "Gross profit ÷ revenue",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Revenue (every job invoiced in the month)",
         "$202,337",
         "$179,007"
        ],
        [
         "Materials",
         "$-64,860",
         "$-51,530"
        ],
        [
         "Subcontractors",
         "$-13,200",
         "$-9,300"
        ],
        [
         "Technician wages",
         "$-54,600",
         "$-54,600"
        ],
        [
         "Gross profit",
         "$69,677",
         "$63,577"
        ],
        [
         "Gross margin",
         "34.4%",
         "35.5%"
        ]
       ],
       "note": "Technicians are on salary, so a quiet month for jobs lowers the margin even if every job is priced well.",
       "series": null
      }
     },
     {
      "label": "Cost to win a customer",
      "value": "$162",
      "sub": "▼ from $205 in Aug",
      "cls": "good",
      "support": {
       "title": "Cost to win a customer",
       "formula": "Marketing spend ÷ new customers",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Marketing spend",
         "$7,600",
         "$8,400"
        ],
        [
         "New customers (first job ever)",
         "47",
         "41"
        ],
        [
         "Cost per new customer",
         "$162",
         "$205"
        ]
       ],
       "note": null,
       "series": null
      }
     },
     {
      "label": "Technician time on jobs",
      "value": "64%",
      "sub": "▲ from 62% in Aug",
      "cls": "good",
      "support": {
       "title": "Technician time on jobs",
       "formula": "Hours charged to jobs ÷ hours available",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Hours charged to jobs (timesheets)",
         "752.5 h",
         "655 h"
        ],
        [
         "Technicians",
         "7",
         "7"
        ],
        [
         "Working days",
         "22",
         "20"
        ],
        [
         "Hours available (technicians × days × 7.6)",
         "1,170.4 h",
         "1,064 h"
        ],
        [
         "Time on jobs",
         "64%",
         "62%"
        ]
       ],
       "note": "August had one fewer working day for the Ekka show holiday. The rest is travel, training, quoting and waiting time.",
       "series": null
      }
     }
    ],
    "chart": {
     "title": "Margin by installation job, September (%)",
     "labels": [
      "Wacol warehouse switchboard",
      "Milton office LED lighting",
      "Carindale solar and battery",
      "West End cafe air-con",
      "Bulimba EV chargers",
      "Chermside clinic cabling"
     ],
     "values": [
      13.5,
      39.5,
      26.9,
      33.5,
      45.2,
      36.6
     ],
     "target": 35,
     "format": "pct0",
     "what": "job margin",
     "details": [
      {
       "title": "Wacol warehouse switchboard",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "4 Sep",
         ""
        ],
        [
         "Revenue",
         "$46,800",
         ""
        ],
        [
         "Materials",
         "$-22,900",
         ""
        ],
        [
         "Subcontractors",
         "$-7,400",
         ""
        ],
        [
         "Technician time",
         "150 h × $68 = $-10,200",
         ""
        ],
        [
         "Gross profit",
         "$6,300",
         ""
        ],
        [
         "Margin",
         "13.5%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Milton office LED lighting",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "9 Sep",
         ""
        ],
        [
         "Revenue",
         "$18,600",
         ""
        ],
        [
         "Materials",
         "$-6,900",
         ""
        ],
        [
         "Subcontractors",
         "$0",
         ""
        ],
        [
         "Technician time",
         "64 h × $68 = $-4,352",
         ""
        ],
        [
         "Gross profit",
         "$7,348",
         ""
        ],
        [
         "Margin",
         "39.5%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Carindale solar and battery",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "15 Sep",
         ""
        ],
        [
         "Revenue",
         "$27,400",
         ""
        ],
        [
         "Materials",
         "$-13,800",
         ""
        ],
        [
         "Subcontractors",
         "$-3,100",
         ""
        ],
        [
         "Technician time",
         "46 h × $68 = $-3,128",
         ""
        ],
        [
         "Gross profit",
         "$7,372",
         ""
        ],
        [
         "Margin",
         "26.9%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "West End cafe air-con",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "18 Sep",
         ""
        ],
        [
         "Revenue",
         "$12,900",
         ""
        ],
        [
         "Materials",
         "$-5,100",
         ""
        ],
        [
         "Subcontractors",
         "$-900",
         ""
        ],
        [
         "Technician time",
         "38 h × $68 = $-2,584",
         ""
        ],
        [
         "Gross profit",
         "$4,316",
         ""
        ],
        [
         "Margin",
         "33.5%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Bulimba EV chargers",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "23 Sep",
         ""
        ],
        [
         "Revenue",
         "$9,800",
         ""
        ],
        [
         "Materials",
         "$-3,600",
         ""
        ],
        [
         "Subcontractors",
         "$0",
         ""
        ],
        [
         "Technician time",
         "26 h × $68 = $-1,768",
         ""
        ],
        [
         "Gross profit",
         "$4,432",
         ""
        ],
        [
         "Margin",
         "45.2%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Chermside clinic cabling",
       "formula": "Gross profit ÷ revenue for this job",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Invoiced",
         "29 Sep",
         ""
        ],
        [
         "Revenue",
         "$15,200",
         ""
        ],
        [
         "Materials",
         "$-4,300",
         ""
        ],
        [
         "Subcontractors",
         "$-1,800",
         ""
        ],
        [
         "Technician time",
         "52 h × $68 = $-3,536",
         ""
        ],
        [
         "Gross profit",
         "$5,564",
         ""
        ],
        [
         "Margin",
         "36.6%",
         ""
        ]
       ],
       "note": null,
       "series": null
      }
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to the movement in retained earnings",
    "Every job's revenue, materials and subcontractors add up to the P&L",
    "Trade debtors equal the invoices still unpaid at month end"
   ],
   "assumptions": [
    [
     "The business",
     [
      [
       "What it is",
       "An electrical and air-conditioning contractor in Brisbane: maintenance contracts, installations and call-outs. 7 technicians, 3 office staff."
      ],
      [
       "Reporting month",
       "September 2026 (the last closed month), compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Jobs (September)",
     [
      [
       "Maintenance contracts",
       "14 customers, invoiced on the 1st, paid in about 30 days"
      ],
      [
       "Installations",
       "6 named jobs, each with its own quote, materials, subcontractors and hours"
      ],
      [
       "Call-outs",
       "64 jobs at $145/hour plus materials marked up 30%"
      ],
      [
       "Jobs in September",
       "84 in total (every one is in the Excel download and CSV)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Technicians",
       "7 on salary: $54,600 a month incl. super"
      ],
      [
       "Job costing rate",
       "$68/hour for technician time charged to a job"
      ],
      [
       "Working days",
       "20 in August (Ekka show holiday), 22 in September; 7.6 hours a day"
      ],
      [
       "Overheads",
       "set month by month, as shown in the P&L"
      ],
      [
       "Income tax",
       "25% of profit, provided monthly; next PAYG instalment due October"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Customer payments",
       "each invoice is paid on its own date; unpaid invoices at month end = debtors"
      ],
      [
       "Supplier bills",
       "materials and subcontractors are paid the following month"
      ],
      [
       "Equipment finance",
       "$5,000 repaid each month"
      ],
      [
       "New equipment",
       "a $12,000 trailer bought in September"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/trades-sample-statements.xlsx",
    "pdf": "media/exports/trades-sample-statements.pdf"
   }
  },
  {
   "id": "services",
   "toggle": "SME · services",
   "name": "Sample Advisory Pty Ltd",
   "about": "A Brisbane finance and operations consultancy: projects billed on milestones, monthly retainers and training. 6 consultants, 3 management and admin staff.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss, September 2026",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Projects (hours worked)",
       "level": "detail",
       "values": [
        85950,
        75740
       ],
       "note": null
      },
      {
       "label": "Retainers",
       "level": "detail",
       "values": [
        32500,
        32500
       ],
       "note": null
      },
      {
       "label": "Training",
       "level": "detail",
       "values": [
        13400,
        6400
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        131850,
        114640
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Consultant salaries (incl. super)",
       "level": "detail",
       "values": [
        -46500,
        -46500
       ],
       "note": null
      },
      {
       "label": "Contractors",
       "level": "detail",
       "values": [
        -8500,
        -6900
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -55000,
        -53400
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        76850,
        61240
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Management and admin wages",
       "level": "detail",
       "values": [
        -24000,
        -24000
       ],
       "note": null
      },
      {
       "label": "Marketing and business development",
       "level": "detail",
       "values": [
        -5800,
        -6500
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -8000,
        -8000
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -4500,
        -4500
       ],
       "note": null
      },
      {
       "label": "Professional indemnity insurance",
       "level": "detail",
       "values": [
        -2500,
        -2500
       ],
       "note": null
      },
      {
       "label": "Travel",
       "level": "detail",
       "values": [
        -1800,
        -2600
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -3300,
        -3300
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -49900,
        -51400
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        26950,
        9840
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -2000,
        -2000
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -240,
        -250
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        24710,
        7590
       ],
       "note": null
      },
      {
       "label": "Income tax provision (25%)",
       "level": "subtotal",
       "values": [
        -6178,
        -1898
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        18532,
        5692
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        149260,
        192150
       ],
       "note": null
      },
      {
       "label": "Trade debtors (unpaid invoices)",
       "level": "detail",
       "values": [
        116800,
        71290
       ],
       "note": null
      },
      {
       "label": "Work in progress (unbilled project time)",
       "level": "detail",
       "values": [
        99290,
        77900
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        15000,
        15000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        380350,
        356340
       ],
       "note": null
      },
      {
       "label": "Office equipment",
       "level": "subtotal",
       "values": [
        60200,
        59000
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        440550,
        415340
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors (bills due next month)",
       "level": "detail",
       "values": [
        8500,
        6900
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        122300,
        121700
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        56576,
        50398
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        187376,
        178998
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        14600,
        16300
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        201976,
        195298
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        238574,
        220042
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        20000,
        20000
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        218574,
        200042
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        238574,
        220042
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers (invoices paid)",
       "level": "detail",
       "values": [
        64950,
        137200
       ],
       "note": null
      },
      {
       "label": "Payments to contractors and suppliers",
       "level": "detail",
       "values": [
        -32800,
        -31300
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -69900,
        -69800
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -240,
        -250
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next PAYG instalment is due in October."
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        -37990,
        35850
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of equipment",
       "level": "detail",
       "values": [
        -3200,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -3200,
        0
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -1700,
        -1700
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -1700,
        -1700
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -42890,
        34150
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        192150,
        158000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        149260,
        192150
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Consultant utilisation, September",
      "value": "74%",
      "sub": "▲ from 71% in Aug",
      "cls": "good",
      "spine": true,
      "support": {
       "title": "Consultant utilisation",
       "formula": "Billable hours ÷ hours available",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Billable hours (timesheets)",
         "742 h",
         "648 h"
        ],
        [
         "Consultants",
         "6",
         "6"
        ],
        [
         "Working days",
         "22",
         "20"
        ],
        [
         "Hours available (consultants × days × 7.6)",
         "1,003.2 h",
         "912 h"
        ],
        [
         "Utilisation",
         "74%",
         "71%"
        ]
       ],
       "note": null,
       "series": null
      }
     },
     {
      "label": "Revenue per billable hour",
      "value": "$178",
      "sub": "▲ from $177 in Aug",
      "cls": "good",
      "support": {
       "title": "Revenue per billable hour",
       "formula": "Revenue ÷ billable hours",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Revenue",
         "$131,850",
         "$114,640"
        ],
        [
         "Billable hours",
         "742 h",
         "648 h"
        ],
        [
         "Revenue per hour",
         "$178",
         "$177"
        ]
       ],
       "note": "Retainers and training are fixed fees, so fewer hours on them raises the hourly figure.",
       "series": null
      }
     },
     {
      "label": "Unbilled work + unpaid invoices",
      "value": "$216,090",
      "sub": "▲ from $149,190 in Aug",
      "cls": "bad",
      "support": {
       "title": "Cash tied up in work",
       "formula": "Work in progress + unpaid invoices at month end",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Work in progress (project time not yet billed)",
         "$99,290",
         "$77,900"
        ],
        [
         "Unpaid client invoices",
         "$116,800",
         "$71,290"
        ],
        [
         "Total tied up",
         "$216,090",
         "$149,190"
        ]
       ],
       "note": "Milestone billing on the logistics and manufacturer projects landed at the end of September, so it moved from unbilled to unpaid.",
       "series": null
      }
     }
    ],
    "chart": {
     "title": "Margin by engagement, September (%)",
     "labels": [
      "Logistics systems rollout",
      "Retail pricing review",
      "Health charity board pack",
      "Manufacturer process mapping",
      "Construction firm finance",
      "Dental group reporting",
      "Agribusiness CFO support",
      "Hospitality payroll",
      "Excel for managers",
      "Power BI basics"
     ],
     "values": [
      52.7,
      68.4,
      63.6,
      53.9,
      63.4,
      61.2,
      65.0,
      48.6,
      62.5,
      81.7
     ],
     "target": 40,
     "format": "pct0",
     "what": "engagement margin",
     "details": [
      {
       "title": "Logistics systems rollout",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Project",
         ""
        ],
        [
         "Hours",
         "210 h",
         ""
        ],
        [
         "Revenue",
         "$36,750",
         ""
        ],
        [
         "Contractors",
         "$-4,800",
         ""
        ],
        [
         "Consultant time",
         "210 h × $60 = $-12,600",
         ""
        ],
        [
         "Contribution",
         "$19,350",
         ""
        ],
        [
         "Margin",
         "52.7%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Retail pricing review",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Project",
         ""
        ],
        [
         "Hours",
         "96 h",
         ""
        ],
        [
         "Revenue",
         "$18,240",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "96 h × $60 = $-5,760",
         ""
        ],
        [
         "Contribution",
         "$12,480",
         ""
        ],
        [
         "Margin",
         "68.4%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Health charity board pack",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Project",
         ""
        ],
        [
         "Hours",
         "64 h",
         ""
        ],
        [
         "Revenue",
         "$10,560",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "64 h × $60 = $-3,840",
         ""
        ],
        [
         "Contribution",
         "$6,720",
         ""
        ],
        [
         "Margin",
         "63.6%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Manufacturer process mapping",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Project",
         ""
        ],
        [
         "Hours",
         "120 h",
         ""
        ],
        [
         "Revenue",
         "$20,400",
         ""
        ],
        [
         "Contractors",
         "$-2,200",
         ""
        ],
        [
         "Consultant time",
         "120 h × $60 = $-7,200",
         ""
        ],
        [
         "Contribution",
         "$11,000",
         ""
        ],
        [
         "Margin",
         "53.9%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Construction firm finance",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Retainer",
         ""
        ],
        [
         "Hours",
         "58 h",
         ""
        ],
        [
         "Revenue",
         "$9,500",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "58 h × $60 = $-3,480",
         ""
        ],
        [
         "Contribution",
         "$6,020",
         ""
        ],
        [
         "Margin",
         "63.4%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Dental group reporting",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Retainer",
         ""
        ],
        [
         "Hours",
         "44 h",
         ""
        ],
        [
         "Revenue",
         "$6,800",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "44 h × $60 = $-2,640",
         ""
        ],
        [
         "Contribution",
         "$4,160",
         ""
        ],
        [
         "Margin",
         "61.2%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Agribusiness CFO support",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Retainer",
         ""
        ],
        [
         "Hours",
         "70 h",
         ""
        ],
        [
         "Revenue",
         "$12,000",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "70 h × $60 = $-4,200",
         ""
        ],
        [
         "Contribution",
         "$7,800",
         ""
        ],
        [
         "Margin",
         "65.0%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Hospitality payroll",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Retainer",
         ""
        ],
        [
         "Hours",
         "36 h",
         ""
        ],
        [
         "Revenue",
         "$4,200",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "36 h × $60 = $-2,160",
         ""
        ],
        [
         "Contribution",
         "$2,040",
         ""
        ],
        [
         "Margin",
         "48.6%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Excel for managers",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Training",
         ""
        ],
        [
         "Hours",
         "30 h",
         ""
        ],
        [
         "Revenue",
         "$8,800",
         ""
        ],
        [
         "Contractors",
         "$-1,500",
         ""
        ],
        [
         "Consultant time",
         "30 h × $60 = $-1,800",
         ""
        ],
        [
         "Contribution",
         "$5,500",
         ""
        ],
        [
         "Margin",
         "62.5%",
         ""
        ]
       ],
       "note": null,
       "series": null
      },
      {
       "title": "Power BI basics",
       "formula": "Contribution ÷ revenue for this engagement",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Type",
         "Training",
         ""
        ],
        [
         "Hours",
         "14 h",
         ""
        ],
        [
         "Revenue",
         "$4,600",
         ""
        ],
        [
         "Contractors",
         "$0",
         ""
        ],
        [
         "Consultant time",
         "14 h × $60 = $-840",
         ""
        ],
        [
         "Contribution",
         "$3,760",
         ""
        ],
        [
         "Margin",
         "81.7%",
         ""
        ]
       ],
       "note": null,
       "series": null
      }
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to the movement in retained earnings",
    "Every engagement's revenue adds up to the P&L",
    "Work in progress equals unbilled project time; debtors equal unpaid invoices"
   ],
   "assumptions": [
    [
     "The business",
     [
      [
       "What it is",
       "A Brisbane finance and operations consultancy: projects billed on milestones, monthly retainers and training. 6 consultants, 3 management and admin staff."
      ],
      [
       "Reporting month",
       "September 2026, compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Engagements (September)",
     [
      [
       "Projects",
       "hours worked at each project's rate; billed on milestones (unbilled time = work in progress)"
      ],
      [
       "Retainers",
       "fixed monthly fee, billed monthly"
      ],
      [
       "Training",
       "fixed fee, billed on delivery"
      ],
      [
       "Engagements in September",
       "10 (every one is in the Excel download and CSV)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Consultants",
       "6 on salary: $46,500 a month incl. super"
      ],
      [
       "Engagement costing rate",
       "$60/hour for consultant time"
      ],
      [
       "Working days",
       "20 in August (Ekka show holiday), 22 in September; 7.6 hours a day"
      ],
      [
       "Income tax",
       "25% of profit, provided monthly"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Client payments",
       "each invoice is paid on its own date; unpaid invoices at month end = debtors"
      ],
      [
       "Contractors",
       "paid the following month"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/services-sample-statements.xlsx",
    "pdf": "media/exports/services-sample-statements.pdf"
   }
  },
  {
   "id": "nfp",
   "toggle": "Not-for-profit",
   "name": "Sample Community Services Ltd",
   "about": "A Brisbane community services charity funded by six grants, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Income and expenditure, September 2026",
     "rows": [
      {
       "label": "Income",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Youth outreach grant",
       "level": "detail",
       "values": [
        22800,
        21500
       ],
       "note": null
      },
      {
       "label": "Housing support grant",
       "level": "detail",
       "values": [
        31200,
        30500
       ],
       "note": null
      },
      {
       "label": "Community meals grant",
       "level": "detail",
       "values": [
        4300,
        4100
       ],
       "note": null
      },
      {
       "label": "Digital literacy grant",
       "level": "detail",
       "values": [
        4900,
        5200
       ],
       "note": null
      },
      {
       "label": "Mental health first aid grant",
       "level": "detail",
       "values": [
        10800,
        9400
       ],
       "note": null
      },
      {
       "label": "Volunteer coordinator grant",
       "level": "detail",
       "values": [
        3000,
        3000
       ],
       "note": null
      },
      {
       "label": "Donations",
       "level": "detail",
       "values": [
        27900,
        18400
       ],
       "note": null
      },
      {
       "label": "Fundraising events",
       "level": "detail",
       "values": [
        41600,
        0
       ],
       "note": null
      },
      {
       "label": "Program fees",
       "level": "detail",
       "values": [
        28300,
        26800
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "detail",
       "values": [
        1380,
        1450
       ],
       "note": null
      },
      {
       "label": "Total income",
       "level": "subtotal",
       "values": [
        176180,
        120350
       ],
       "note": null
      },
      {
       "label": "Programs",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant-funded program wages",
       "level": "detail",
       "values": [
        -57750,
        -55275
       ],
       "note": null
      },
      {
       "label": "Grant-funded program costs",
       "level": "detail",
       "values": [
        -19250,
        -18425
       ],
       "note": null
      },
      {
       "label": "Program delivery wages (untied)",
       "level": "detail",
       "values": [
        -14500,
        -14000
       ],
       "note": null
      },
      {
       "label": "Program costs (untied)",
       "level": "detail",
       "values": [
        -6100,
        -5500
       ],
       "note": null
      },
      {
       "label": "Total program spend",
       "level": "subtotal",
       "values": [
        -97600,
        -93200
       ],
       "note": null
      },
      {
       "label": "Fundraising",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant writing and reporting",
       "level": "detail",
       "values": [
        -7100,
        -7100
       ],
       "note": null
      },
      {
       "label": "Donor campaigns",
       "level": "detail",
       "values": [
        -5400,
        -2200
       ],
       "note": null
      },
      {
       "label": "Event costs",
       "level": "detail",
       "values": [
        -16900,
        -2400
       ],
       "note": null
      },
      {
       "label": "Total fundraising costs",
       "level": "subtotal",
       "values": [
        -29400,
        -11700
       ],
       "note": null
      },
      {
       "label": "Administration",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Administration wages",
       "level": "detail",
       "values": [
        -18300,
        -18300
       ],
       "note": null
      },
      {
       "label": "Occupancy",
       "level": "detail",
       "values": [
        -10000,
        -10000
       ],
       "note": null
      },
      {
       "label": "Other administration",
       "level": "detail",
       "values": [
        -7600,
        -8000
       ],
       "note": null
      },
      {
       "label": "Total administration",
       "level": "subtotal",
       "values": [
        -35900,
        -36300
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -2900,
        -2900
       ],
       "note": null
      },
      {
       "label": "Total expenses",
       "level": "total",
       "values": [
        -165800,
        -144100
       ],
       "note": null
      },
      {
       "label": "Surplus for the month",
       "level": "key",
       "values": [
        10380,
        -23750
       ],
       "note": "Income-tax exempt charity: no income tax."
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        480780,
        525675
       ],
       "note": null
      },
      {
       "label": "Program fees receivable",
       "level": "detail",
       "values": [
        10400,
        9800
       ],
       "note": null
      },
      {
       "label": "Grants receivable (spent ahead of instalment)",
       "level": "detail",
       "values": [
        20900,
        9700
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        21000,
        21000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        533080,
        566175
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        172200,
        175100
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        705280,
        741275
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Payables (bills due next month)",
       "level": "detail",
       "values": [
        65250,
        46525
       ],
       "note": null
      },
      {
       "label": "Grants received in advance (unspent)",
       "level": "detail",
       "values": [
        156100,
        221900
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        166600,
        165900
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        387950,
        434325
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        317330,
        306950
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Accumulated funds",
       "level": "key",
       "values": [
        317330,
        306950
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant instalments received",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next instalments arrive in October."
      },
      {
       "label": "Donations and fundraising received",
       "level": "detail",
       "values": [
        69500,
        18400
       ],
       "note": null
      },
      {
       "label": "Program fees received",
       "level": "detail",
       "values": [
        27700,
        26100
       ],
       "note": null
      },
      {
       "label": "Interest received",
       "level": "detail",
       "values": [
        1380,
        1450
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers",
       "level": "detail",
       "values": [
        -46525,
        -36500
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -96950,
        -93775
       ],
       "note": null
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        -44895,
        -84325
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        0,
        0
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -44895,
        -84325
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        525675,
        610000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        480780,
        525675
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Cost to raise a dollar, September",
      "value": "20¢",
      "sub": "▲ from 13¢ in Aug",
      "cls": "bad",
      "spine": true,
      "support": {
       "title": "Cost to raise a dollar",
       "formula": "Fundraising costs ÷ money raised (grants, donations, events)",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Grant writing and reporting",
         "$7,100",
         "$7,100"
        ],
        [
         "Donor campaigns",
         "$5,400",
         "$2,200"
        ],
        [
         "Event costs",
         "$16,900",
         "$2,400"
        ],
        [
         "Fundraising costs",
         "$29,400",
         "$11,700"
        ],
        [
         "Grant income",
         "$77,000",
         "$73,700"
        ],
        [
         "Donations",
         "$27,900",
         "$18,400"
        ],
        [
         "Fundraising events",
         "$41,600",
         "$0"
        ],
        [
         "Money raised",
         "$146,500",
         "$92,100"
        ],
        [
         "Cost per dollar raised",
         "20¢",
         "13¢"
        ]
       ],
       "note": "September's gala raised $41,600 but cost $16,900 to run, which lifts the month's figure.",
       "series": null
      }
     },
     {
      "label": "Unrestricted cash runway",
      "value": "2.0 months",
      "sub": "▼ from 2.2 months in Aug",
      "cls": "bad",
      "support": {
       "title": "Unrestricted cash runway",
       "formula": "(Cash at bank − unspent grant money) ÷ this month's cash spending",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Cash at bank",
         "$480,780",
         "$525,675"
        ],
        [
         "Less unspent grant money (belongs to funders' programs)",
         "$-156,100",
         "$-221,900"
        ],
        [
         "Unrestricted cash",
         "$324,680",
         "$303,775"
        ],
        [
         "Cash spending in the month (expenses less depreciation)",
         "$162,900",
         "$141,200"
        ],
        [
         "Runway",
         "2.0 months",
         "2.2 months"
        ]
       ],
       "note": "Reserves target: 3 months.",
       "series": null
      }
     },
     {
      "label": "Grants ending in 6 months",
      "value": "2 · $117,300",
      "sub": "still to spend before they end",
      "cls": "bad",
      "support": {
       "title": "Grants ending in the next 6 months",
       "formula": "Grant total − spent to date",
       "head": [
        "",
        "Ends",
        "Still to spend"
       ],
       "rows": [
        [
         "Housing support",
         "31 Dec 2026",
         "$102,300"
        ],
        [
         "Volunteer coordinator",
         "28 Feb 2027",
         "$15,000"
        ],
        [
         "Total",
         "",
         "$117,300"
        ]
       ],
       "note": "Unspent money usually has to be returned, or an extension negotiated, so plan the spending now.",
       "series": null
      }
     }
    ],
    "chart": {
     "title": "Grant spend to date against budget",
     "labels": [
      "Youth outreach",
      "Housing support",
      "Community meals",
      "Digital literacy",
      "Mental health first aid",
      "Volunteer coordinator"
     ],
     "values": [
      102.1,
      95.4,
      100.0,
      99.3,
      95.3,
      100.0
     ],
     "target": 100,
     "format": "pct0",
     "what": "grant spend against budget",
     "plain": true,
     "views": [
      {
       "id": "pct",
       "label": "% of budget",
       "values": [
        102.1,
        95.4,
        100.0,
        99.3,
        95.3,
        100.0
       ],
       "format": "pct0",
       "target": 100
      },
      {
       "id": "spend",
       "label": "$ spent",
       "values": [
        306300,
        257700,
        12000,
        59600,
        57200,
        21000
       ],
       "format": "money_k",
       "marks": [
        300000,
        270000,
        12000,
        60000,
        60000,
        21000
       ],
       "mark_label": "Budget to date"
      }
     ],
     "details": [
      {
       "title": "Youth outreach",
       "formula": "State Department of Families · $480,000 · Jul 2025 to Jun 2027",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$300,000",
         ""
        ],
        [
         "Still to spend",
         "$173,700",
         ""
        ],
        [
         "Months left",
         "9",
         ""
        ],
        [
         "Spent to date",
         "$306,300",
         ""
        ],
        [
         "Budget to date",
         "$300,000",
         ""
        ],
        [
         "Spent against budget",
         "102.1%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Jul 25",
         "Aug 25",
         "Sep 25",
         "Oct 25",
         "Nov 25",
         "Dec 25",
         "Jan 26",
         "Feb 26",
         "Mar 26",
         "Apr 26",
         "May 26",
         "Jun 26",
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         17363,
         21144,
         17537,
         21925,
         21079,
         19272,
         21157,
         20743,
         16515,
         20451,
         21174,
         20366,
         23274,
         21500,
         22800
        ],
        "budget": [
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000,
         20000
        ],
        "format": "money0"
       }
      },
      {
       "title": "Housing support",
       "formula": "State Housing Program · $360,000 · Jan 2026 to Dec 2026",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$360,000",
         ""
        ],
        [
         "Still to spend",
         "$102,300",
         ""
        ],
        [
         "Months left",
         "3",
         ""
        ],
        [
         "Spent to date",
         "$257,700",
         ""
        ],
        [
         "Budget to date",
         "$270,000",
         ""
        ],
        [
         "Spent against budget",
         "95.4%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Jan 26",
         "Feb 26",
         "Mar 26",
         "Apr 26",
         "May 26",
         "Jun 26",
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         30502,
         26508,
         24832,
         23730,
         31337,
         29994,
         29097,
         30500,
         31200
        ],
        "budget": [
         30000,
         30000,
         30000,
         30000,
         30000,
         30000,
         30000,
         30000,
         30000
        ],
        "format": "money0"
       }
      },
      {
       "title": "Community meals",
       "formula": "Local council community grant · $48,000 · Jul 2026 to Jun 2027",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$48,000",
         ""
        ],
        [
         "Still to spend",
         "$36,000",
         ""
        ],
        [
         "Months left",
         "9",
         ""
        ],
        [
         "Spent to date",
         "$12,000",
         ""
        ],
        [
         "Budget to date",
         "$12,000",
         ""
        ],
        [
         "Spent against budget",
         "100.0%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         3600,
         4100,
         4300
        ],
        "budget": [
         4000,
         4000,
         4000
        ],
        "format": "money0"
       }
      },
      {
       "title": "Digital literacy",
       "formula": "Philanthropic foundation · $90,000 · Oct 2025 to Mar 2027",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$45,000",
         ""
        ],
        [
         "Still to spend",
         "$30,400",
         ""
        ],
        [
         "Months left",
         "6",
         ""
        ],
        [
         "Spent to date",
         "$59,600",
         ""
        ],
        [
         "Budget to date",
         "$60,000",
         ""
        ],
        [
         "Spent against budget",
         "99.3%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Oct 25",
         "Nov 25",
         "Dec 25",
         "Jan 26",
         "Feb 26",
         "Mar 26",
         "Apr 26",
         "May 26",
         "Jun 26",
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         5160,
         4585,
         5221,
         4426,
         5408,
         5427,
         5509,
         4635,
         4316,
         4813,
         5200,
         4900
        ],
        "budget": [
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000,
         5000
        ],
        "format": "money0"
       }
      },
      {
       "title": "Mental health first aid",
       "formula": "Federal health program · $120,000 · Apr 2026 to Mar 2027",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$60,000",
         ""
        ],
        [
         "Still to spend",
         "$62,800",
         ""
        ],
        [
         "Months left",
         "6",
         ""
        ],
        [
         "Spent to date",
         "$57,200",
         ""
        ],
        [
         "Budget to date",
         "$60,000",
         ""
        ],
        [
         "Spent against budget",
         "95.3%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Apr 26",
         "May 26",
         "Jun 26",
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         9584,
         8950,
         9797,
         8669,
         9400,
         10800
        ],
        "budget": [
         10000,
         10000,
         10000,
         10000,
         10000,
         10000
        ],
        "format": "money0"
       }
      },
      {
       "title": "Volunteer coordinator",
       "formula": "State volunteering grant · $36,000 · Mar 2026 to Feb 2027",
       "head": [
        "",
        "Sep 2026",
        "Aug 2026"
       ],
       "rows": [
        [
         "Received from the funder",
         "$36,000",
         ""
        ],
        [
         "Still to spend",
         "$15,000",
         ""
        ],
        [
         "Months left",
         "5",
         ""
        ],
        [
         "Spent to date",
         "$21,000",
         ""
        ],
        [
         "Budget to date",
         "$21,000",
         ""
        ],
        [
         "Spent against budget",
         "100.0%",
         ""
        ]
       ],
       "note": null,
       "series": {
        "title": "Spend by month against budget",
        "labels": [
         "Mar 26",
         "Apr 26",
         "May 26",
         "Jun 26",
         "Jul 26",
         "Aug 26",
         "Sep 26"
        ],
        "values": [
         2932,
         3555,
         2649,
         2699,
         3165,
         3000,
         3000
        ],
        "budget": [
         3000,
         3000,
         3000,
         3000,
         3000,
         3000,
         3000
        ],
        "format": "money0"
       }
      }
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + accumulated funds",
    "Cash flow ends at the cash in the bank",
    "Surplus ties to the movement in accumulated funds",
    "Grant income equals what was spent on each grant",
    "Unspent grants equal instalments received less income recognised"
   ],
   "assumptions": [
    [
     "The organisation",
     [
      [
       "What it is",
       "A Brisbane community services charity funded by six grants, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt."
      ],
      [
       "Reporting month",
       "September 2026, compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Grants",
     [
      [
       "Youth outreach",
       "State Department of Families: $480,000, 2025-07 to 2027-06"
      ],
      [
       "Housing support",
       "State Housing Program: $360,000, 2026-01 to 2026-12"
      ],
      [
       "Community meals",
       "Local council community grant: $48,000, 2026-07 to 2027-06"
      ],
      [
       "Digital literacy",
       "Philanthropic foundation: $90,000, 2025-10 to 2027-03"
      ],
      [
       "Mental health first aid",
       "Federal health program: $120,000, 2026-04 to 2027-03"
      ],
      [
       "Volunteer coordinator",
       "State volunteering grant: $36,000, 2026-03 to 2027-02"
      ],
      [
       "Grant income",
       "recognised as the money is spent on the program"
      ],
      [
       "Unspent grants",
       "instalments received but not yet spent are a liability (grants received in advance)"
      ]
     ]
    ],
    [
     "Other income and costs",
     [
      [
       "Donations",
       "including the spring appeal in September"
      ],
      [
       "Fundraising event",
       "September gala: income and costs in the same month"
      ],
      [
       "Grant-funded spending",
       "75% wages, the rest program costs"
      ],
      [
       "Income tax",
       "none: registered charity, income-tax exempt"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Suppliers",
       "paid the following month"
      ],
      [
       "Unrestricted cash",
       "cash at bank less unspent grant money"
      ],
      [
       "Cash runway",
       "unrestricted cash ÷ this month's cash spending"
      ],
      [
       "Reserves target",
       "3 months of spending"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/nfp-sample-statements.xlsx",
    "pdf": "media/exports/nfp-sample-statements.pdf"
   }
  }
 ]
};
