/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.
   Don't edit by hand: change the assumptions in financial_model.py and re-run.
   All figures are invented sample data, in whole dollars: September 2026 vs August 2026. */
window.FOURTH_SHEET_DASHBOARD = {
 "generated": "2026-10-06",
 "orgs": [
  {
   "id": "trades",
   "toggle": "SME · trades",
   "name": "Sample Electrical & Air Pty Ltd",
   "about": "An electrical and air-conditioning contractor in Brisbane: maintenance contracts, installations and call-outs. 7 technicians, 3 office staff.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss, September 2026",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Maintenance contracts (14)",
       "level": "detail",
       "values": [
        40500,
        40500
       ],
       "note": null
      },
      {
       "label": "Installations (jobs)",
       "level": "detail",
       "values": [
        130700,
        109600
       ],
       "note": null
      },
      {
       "label": "Call-outs and repairs",
       "level": "detail",
       "values": [
        31137,
        28907
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        202337,
        179007
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Materials",
       "level": "detail",
       "values": [
        -64860,
        -51530
       ],
       "note": null
      },
      {
       "label": "Subcontractors",
       "level": "detail",
       "values": [
        -13200,
        -9300
       ],
       "note": null
      },
      {
       "label": "Technician wages (incl. super)",
       "level": "detail",
       "values": [
        -54600,
        -54600
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -132660,
        -115430
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        69677,
        63577
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Office and admin wages",
       "level": "detail",
       "values": [
        -21900,
        -21900
       ],
       "note": null
      },
      {
       "label": "Marketing",
       "level": "detail",
       "values": [
        -7600,
        -8400
       ],
       "note": null
      },
      {
       "label": "Vehicles and fuel",
       "level": "detail",
       "values": [
        -8300,
        -7900
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -7000,
        -7000
       ],
       "note": null
      },
      {
       "label": "Insurance",
       "level": "detail",
       "values": [
        -3000,
        -3000
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -2300,
        -2300
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -3900,
        -3600
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -54000,
        -54100
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        15677,
        9477
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -4500,
        -4300
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -1080,
        -1100
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        10097,
        4077
       ],
       "note": null
      },
      {
       "label": "Income tax provision (25%)",
       "level": "subtotal",
       "values": [
        -2524,
        -1019
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        7573,
        3058
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        59746,
        65263
       ],
       "note": null
      },
      {
       "label": "Trade debtors (unpaid invoices)",
       "level": "detail",
       "values": [
        151063,
        129819
       ],
       "note": null
      },
      {
       "label": "Materials on hand",
       "level": "detail",
       "values": [
        66000,
        66000
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        21000,
        21000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        297809,
        282082
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        255200,
        247700
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        553009,
        529782
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors (bills due next month)",
       "level": "detail",
       "values": [
        78060,
        60830
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        106000,
        105100
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        35043,
        32519
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        219103,
        198449
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        95000,
        100000
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        314103,
        298449
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        238906,
        231333
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        10000,
        10000
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        228906,
        221333
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        238906,
        231333
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers (invoices paid)",
       "level": "detail",
       "values": [
        181093,
        156273
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers",
       "level": "detail",
       "values": [
        -92930,
        -97510
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -75600,
        -75400
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -1080,
        -1100
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next PAYG instalment is due in October."
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        11483,
        -17737
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        -12000,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -12000,
        0
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -5000,
        -5000
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -5000,
        -5000
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -5517,
        -22737
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        65263,
        88000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        59746,
        65263
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Gross margin, September",
      "value": "34.4%",
      "sub": "▼ from 35.5% in Aug",
      "cls": "bad",
      "spine": true
     },
     {
      "label": "Cost to win a customer",
      "value": "$162",
      "sub": "▼ from $205 in Aug",
      "cls": "good"
     },
     {
      "label": "Technician time on jobs",
      "value": "64%",
      "sub": "▲ from 62% in Aug",
      "cls": "good"
     }
    ],
    "chart": {
     "title": "Margin by installation job, September (%)",
     "labels": [
      "Wacol warehouse switchboard",
      "Milton office LED lighting",
      "Carindale solar and battery",
      "West End café air-con",
      "Bulimba EV chargers",
      "Chermside clinic cabling"
     ],
     "values": [
      13.5,
      39.5,
      26.9,
      33.5,
      45.2,
      36.6
     ],
     "target": 35,
     "format": "pct0",
     "what": "job margin"
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to the movement in retained earnings",
    "Every job's revenue, materials and subcontractors add up to the P&L",
    "Trade debtors equal the invoices still unpaid at month end"
   ],
   "assumptions": [
    [
     "The business",
     [
      [
       "What it is",
       "An electrical and air-conditioning contractor in Brisbane: maintenance contracts, installations and call-outs. 7 technicians, 3 office staff."
      ],
      [
       "Reporting month",
       "September 2026 (the last closed month), compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Jobs (September)",
     [
      [
       "Maintenance contracts",
       "14 customers, invoiced on the 1st, paid in about 30 days"
      ],
      [
       "Installations",
       "6 named jobs, each with its own quote, materials, subcontractors and hours"
      ],
      [
       "Call-outs",
       "64 jobs at $145/hour plus materials marked up 30%"
      ],
      [
       "Jobs in September",
       "84 in total (every one is in the Excel download and CSV)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Technicians",
       "7 on salary: $54,600 a month incl. super"
      ],
      [
       "Job costing rate",
       "$68/hour for technician time charged to a job"
      ],
      [
       "Working days",
       "20 in August (Ekka show holiday), 22 in September; 7.6 hours a day"
      ],
      [
       "Overheads",
       "set month by month, as shown in the P&L"
      ],
      [
       "Income tax",
       "25% of profit, provided monthly; next PAYG instalment due October"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Customer payments",
       "each invoice is paid on its own date; unpaid invoices at month end = debtors"
      ],
      [
       "Supplier bills",
       "materials and subcontractors are paid the following month"
      ],
      [
       "Equipment finance",
       "$5,000 repaid each month"
      ],
      [
       "New equipment",
       "a $12,000 trailer bought in September"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/trades-sample-statements.xlsx",
    "pdf": "media/exports/trades-sample-statements.pdf"
   }
  },
  {
   "id": "services",
   "toggle": "SME · services",
   "name": "Sample Advisory Pty Ltd",
   "about": "A Brisbane finance and operations consultancy: projects billed on milestones, monthly retainers and training. 6 consultants, 3 management and admin staff.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss, September 2026",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Projects (hours worked)",
       "level": "detail",
       "values": [
        85950,
        75740
       ],
       "note": null
      },
      {
       "label": "Retainers",
       "level": "detail",
       "values": [
        32500,
        32500
       ],
       "note": null
      },
      {
       "label": "Training",
       "level": "detail",
       "values": [
        13400,
        6400
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        131850,
        114640
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Consultant salaries (incl. super)",
       "level": "detail",
       "values": [
        -46500,
        -46500
       ],
       "note": null
      },
      {
       "label": "Contractors",
       "level": "detail",
       "values": [
        -8500,
        -6900
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -55000,
        -53400
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        76850,
        61240
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Management and admin wages",
       "level": "detail",
       "values": [
        -24000,
        -24000
       ],
       "note": null
      },
      {
       "label": "Marketing and business development",
       "level": "detail",
       "values": [
        -5800,
        -6500
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -8000,
        -8000
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -4500,
        -4500
       ],
       "note": null
      },
      {
       "label": "Professional indemnity insurance",
       "level": "detail",
       "values": [
        -2500,
        -2500
       ],
       "note": null
      },
      {
       "label": "Travel",
       "level": "detail",
       "values": [
        -1800,
        -2600
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -3300,
        -3300
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -49900,
        -51400
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        26950,
        9840
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -2000,
        -2000
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -240,
        -250
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        24710,
        7590
       ],
       "note": null
      },
      {
       "label": "Income tax provision (25%)",
       "level": "subtotal",
       "values": [
        -6178,
        -1898
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        18532,
        5692
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        149260,
        192150
       ],
       "note": null
      },
      {
       "label": "Trade debtors (unpaid invoices)",
       "level": "detail",
       "values": [
        116800,
        71290
       ],
       "note": null
      },
      {
       "label": "Work in progress (unbilled project time)",
       "level": "detail",
       "values": [
        99290,
        77900
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        15000,
        15000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        380350,
        356340
       ],
       "note": null
      },
      {
       "label": "Office equipment",
       "level": "subtotal",
       "values": [
        60200,
        59000
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        440550,
        415340
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors (bills due next month)",
       "level": "detail",
       "values": [
        8500,
        6900
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        122300,
        121700
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        56576,
        50398
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        187376,
        178998
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        14600,
        16300
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        201976,
        195298
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        238574,
        220042
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        20000,
        20000
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        218574,
        200042
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        238574,
        220042
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers (invoices paid)",
       "level": "detail",
       "values": [
        64950,
        137200
       ],
       "note": null
      },
      {
       "label": "Payments to contractors and suppliers",
       "level": "detail",
       "values": [
        -32800,
        -31300
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -69900,
        -69800
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -240,
        -250
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next PAYG instalment is due in October."
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        -37990,
        35850
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of equipment",
       "level": "detail",
       "values": [
        -3200,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -3200,
        0
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -1700,
        -1700
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -1700,
        -1700
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -42890,
        34150
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        192150,
        158000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        149260,
        192150
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Consultant utilisation, September",
      "value": "74%",
      "sub": "▲ from 71% in Aug",
      "cls": "good",
      "spine": true
     },
     {
      "label": "Revenue per billable hour",
      "value": "$178",
      "sub": "▲ from $177 in Aug",
      "cls": "good"
     },
     {
      "label": "Unbilled work + unpaid invoices",
      "value": "$216,090",
      "sub": "▲ from $149,190 in Aug",
      "cls": "bad"
     }
    ],
    "chart": {
     "title": "Margin by engagement, September (%)",
     "labels": [
      "Logistics systems rollout",
      "Retail pricing review",
      "Health charity board pack",
      "Manufacturer process mapping",
      "Construction firm finance",
      "Dental group reporting",
      "Agribusiness CFO support",
      "Hospitality payroll",
      "Excel for managers",
      "Power BI basics"
     ],
     "values": [
      52.7,
      68.4,
      63.6,
      53.9,
      63.4,
      61.2,
      65.0,
      48.6,
      62.5,
      81.7
     ],
     "target": 40,
     "format": "pct0",
     "what": "engagement margin"
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to the movement in retained earnings",
    "Every engagement's revenue adds up to the P&L",
    "Work in progress equals unbilled project time; debtors equal unpaid invoices"
   ],
   "assumptions": [
    [
     "The business",
     [
      [
       "What it is",
       "A Brisbane finance and operations consultancy: projects billed on milestones, monthly retainers and training. 6 consultants, 3 management and admin staff."
      ],
      [
       "Reporting month",
       "September 2026, compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Engagements (September)",
     [
      [
       "Projects",
       "hours worked at each project's rate; billed on milestones (unbilled time = work in progress)"
      ],
      [
       "Retainers",
       "fixed monthly fee, billed monthly"
      ],
      [
       "Training",
       "fixed fee, billed on delivery"
      ],
      [
       "Engagements in September",
       "10 (every one is in the Excel download and CSV)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Consultants",
       "6 on salary: $46,500 a month incl. super"
      ],
      [
       "Engagement costing rate",
       "$60/hour for consultant time"
      ],
      [
       "Working days",
       "20 in August (Ekka show holiday), 22 in September; 7.6 hours a day"
      ],
      [
       "Income tax",
       "25% of profit, provided monthly"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Client payments",
       "each invoice is paid on its own date; unpaid invoices at month end = debtors"
      ],
      [
       "Contractors",
       "paid the following month"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/services-sample-statements.xlsx",
    "pdf": "media/exports/services-sample-statements.pdf"
   }
  },
  {
   "id": "nfp",
   "toggle": "Not-for-profit",
   "name": "Sample Community Services Ltd",
   "about": "A Brisbane community services charity funded by six grants, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt.",
   "columns": [
    "Sep 2026",
    "Aug 2026"
   ],
   "unit": "$",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Income and expenditure, September 2026",
     "rows": [
      {
       "label": "Income",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Youth outreach grant",
       "level": "detail",
       "values": [
        22800,
        21500
       ],
       "note": null
      },
      {
       "label": "Housing support grant",
       "level": "detail",
       "values": [
        31200,
        30500
       ],
       "note": null
      },
      {
       "label": "Community meals grant",
       "level": "detail",
       "values": [
        4300,
        4100
       ],
       "note": null
      },
      {
       "label": "Digital literacy grant",
       "level": "detail",
       "values": [
        4900,
        5200
       ],
       "note": null
      },
      {
       "label": "Mental health first aid grant",
       "level": "detail",
       "values": [
        10800,
        9400
       ],
       "note": null
      },
      {
       "label": "Volunteer coordinator grant",
       "level": "detail",
       "values": [
        3000,
        3000
       ],
       "note": null
      },
      {
       "label": "Donations",
       "level": "detail",
       "values": [
        27900,
        18400
       ],
       "note": null
      },
      {
       "label": "Fundraising events",
       "level": "detail",
       "values": [
        41600,
        0
       ],
       "note": null
      },
      {
       "label": "Program fees",
       "level": "detail",
       "values": [
        28300,
        26800
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "detail",
       "values": [
        1380,
        1450
       ],
       "note": null
      },
      {
       "label": "Total income",
       "level": "subtotal",
       "values": [
        176180,
        120350
       ],
       "note": null
      },
      {
       "label": "Programs",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant-funded program wages",
       "level": "detail",
       "values": [
        -57750,
        -55275
       ],
       "note": null
      },
      {
       "label": "Grant-funded program costs",
       "level": "detail",
       "values": [
        -19250,
        -18425
       ],
       "note": null
      },
      {
       "label": "Program delivery wages (untied)",
       "level": "detail",
       "values": [
        -14500,
        -14000
       ],
       "note": null
      },
      {
       "label": "Program costs (untied)",
       "level": "detail",
       "values": [
        -6100,
        -5500
       ],
       "note": null
      },
      {
       "label": "Total program spend",
       "level": "subtotal",
       "values": [
        -97600,
        -93200
       ],
       "note": null
      },
      {
       "label": "Fundraising",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant writing and reporting",
       "level": "detail",
       "values": [
        -7100,
        -7100
       ],
       "note": null
      },
      {
       "label": "Donor campaigns",
       "level": "detail",
       "values": [
        -5400,
        -2200
       ],
       "note": null
      },
      {
       "label": "Event costs",
       "level": "detail",
       "values": [
        -16900,
        -2400
       ],
       "note": null
      },
      {
       "label": "Total fundraising costs",
       "level": "subtotal",
       "values": [
        -29400,
        -11700
       ],
       "note": null
      },
      {
       "label": "Administration",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Administration wages",
       "level": "detail",
       "values": [
        -18300,
        -18300
       ],
       "note": null
      },
      {
       "label": "Occupancy",
       "level": "detail",
       "values": [
        -10000,
        -10000
       ],
       "note": null
      },
      {
       "label": "Other administration",
       "level": "detail",
       "values": [
        -7600,
        -8000
       ],
       "note": null
      },
      {
       "label": "Total administration",
       "level": "subtotal",
       "values": [
        -35900,
        -36300
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -2900,
        -2900
       ],
       "note": null
      },
      {
       "label": "Total expenses",
       "level": "total",
       "values": [
        -165800,
        -144100
       ],
       "note": null
      },
      {
       "label": "Surplus for the month",
       "level": "key",
       "values": [
        10380,
        -23750
       ],
       "note": "Income-tax exempt charity: no income tax."
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 September 2026",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        480780,
        525675
       ],
       "note": null
      },
      {
       "label": "Program fees receivable",
       "level": "detail",
       "values": [
        10400,
        9800
       ],
       "note": null
      },
      {
       "label": "Grants receivable (spent ahead of instalment)",
       "level": "detail",
       "values": [
        20900,
        9700
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        21000,
        21000
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        533080,
        566175
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        172200,
        175100
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        705280,
        741275
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Payables (bills due next month)",
       "level": "detail",
       "values": [
        65250,
        46525
       ],
       "note": null
      },
      {
       "label": "Grants received in advance (unspent)",
       "level": "detail",
       "values": [
        156100,
        221900
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        166600,
        165900
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        387950,
        434325
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        317330,
        306950
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Accumulated funds",
       "level": "key",
       "values": [
        317330,
        306950
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow, September 2026",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant instalments received",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": "Next instalments arrive in October."
      },
      {
       "label": "Donations and fundraising received",
       "level": "detail",
       "values": [
        69500,
        18400
       ],
       "note": null
      },
      {
       "label": "Program fees received",
       "level": "detail",
       "values": [
        27700,
        26100
       ],
       "note": null
      },
      {
       "label": "Interest received",
       "level": "detail",
       "values": [
        1380,
        1450
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers",
       "level": "detail",
       "values": [
        -46525,
        -36500
       ],
       "note": null
      },
      {
       "label": "Payments to employees",
       "level": "detail",
       "values": [
        -96950,
        -93775
       ],
       "note": null
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        -44895,
        -84325
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        0,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        0,
        0
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        -44895,
        -84325
       ],
       "note": null
      },
      {
       "label": "Cash at start of month",
       "level": "subtotal",
       "values": [
        525675,
        610000
       ],
       "note": null
      },
      {
       "label": "Cash at end of month",
       "level": "key",
       "values": [
        480780,
        525675
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Cost to raise a dollar, September",
      "value": "20¢",
      "sub": "▲ from 13¢ in Aug",
      "cls": "bad",
      "spine": true
     },
     {
      "label": "Unrestricted cash runway",
      "value": "2.0 months",
      "sub": "▼ from 2.2 months in Aug",
      "cls": "bad"
     },
     {
      "label": "Grants ending in 6 months",
      "value": "2 · $117,300",
      "sub": "still to spend before they end",
      "cls": "bad"
     }
    ],
    "chart": {
     "title": "Grant spend vs budget to date (%)",
     "labels": [
      "Youth outreach",
      "Housing support",
      "Community meals",
      "Digital literacy",
      "Mental health first aid",
      "Volunteer coordinator"
     ],
     "values": [
      102.1,
      95.4,
      100.0,
      99.3,
      95.3,
      100.0
     ],
     "target": 100,
     "format": "pct0",
     "what": "grant spend against budget"
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + accumulated funds",
    "Cash flow ends at the cash in the bank",
    "Surplus ties to the movement in accumulated funds",
    "Grant income equals what was spent on each grant",
    "Unspent grants equal instalments received less income recognised"
   ],
   "assumptions": [
    [
     "The organisation",
     [
      [
       "What it is",
       "A Brisbane community services charity funded by six grants, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt."
      ],
      [
       "Reporting month",
       "September 2026, compared with August 2026"
      ],
      [
       "Financial year",
       "FY2027: 1 July 2026 to 30 June 2027"
      ]
     ]
    ],
    [
     "Grants",
     [
      [
       "Youth outreach",
       "State Department of Families: $480,000, 2025-07 to 2027-06"
      ],
      [
       "Housing support",
       "State Housing Program: $360,000, 2026-01 to 2026-12"
      ],
      [
       "Community meals",
       "Local council community grant: $48,000, 2026-07 to 2027-06"
      ],
      [
       "Digital literacy",
       "Philanthropic foundation: $90,000, 2025-10 to 2027-03"
      ],
      [
       "Mental health first aid",
       "Federal health program: $120,000, 2026-04 to 2027-03"
      ],
      [
       "Volunteer coordinator",
       "State volunteering grant: $36,000, 2026-03 to 2027-02"
      ],
      [
       "Grant income",
       "recognised as the money is spent on the program"
      ],
      [
       "Unspent grants",
       "instalments received but not yet spent are a liability (grants received in advance)"
      ]
     ]
    ],
    [
     "Other income and costs",
     [
      [
       "Donations",
       "including the spring appeal in September"
      ],
      [
       "Fundraising event",
       "September gala: income and costs in the same month"
      ],
      [
       "Grant-funded spending",
       "75% wages, the rest program costs"
      ],
      [
       "Income tax",
       "none: registered charity, income-tax exempt"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Suppliers",
       "paid the following month"
      ],
      [
       "Unrestricted cash",
       "cash at bank less unspent grant money"
      ],
      [
       "Cash runway",
       "unrestricted cash ÷ this month's cash spending"
      ],
      [
       "Reserves target",
       "3 months of spending"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/nfp-sample-statements.xlsx",
    "pdf": "media/exports/nfp-sample-statements.pdf"
   }
  }
 ]
};
