/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.
   Don't edit by hand: change the assumptions in financial_model.py and re-run.
   All figures are invented sample data, in $'000 unless labelled. */
window.FOURTH_SHEET_DASHBOARD = {
 "generated": "2026-10-06",
 "orgs": [
  {
   "id": "trades",
   "toggle": "SME · trades",
   "name": "Sample Trade Services Pty Ltd",
   "about": "A field/trade services business: maintenance contracts, installations and call-outs. About 14 staff.",
   "columns": [
    "FY2026",
    "FY2025"
   ],
   "unit": "$'000",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Maintenance contracts",
       "level": "detail",
       "values": [
        720,
        660
       ],
       "note": null
      },
      {
       "label": "Installations",
       "level": "detail",
       "values": [
        1180,
        1060
       ],
       "note": null
      },
      {
       "label": "Call-outs and repairs",
       "level": "detail",
       "values": [
        540,
        490
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        2440,
        2210
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Materials",
       "level": "detail",
       "values": [
        -510,
        -476
       ],
       "note": null
      },
      {
       "label": "Subcontractors",
       "level": "detail",
       "values": [
        -170,
        -152
       ],
       "note": null
      },
      {
       "label": "Direct labour (incl. super)",
       "level": "detail",
       "values": [
        -840,
        -786
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -1520,
        -1414
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        920,
        796
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Office and admin wages",
       "level": "detail",
       "values": [
        -330,
        -310
       ],
       "note": null
      },
      {
       "label": "Marketing",
       "level": "detail",
       "values": [
        -96,
        -104
       ],
       "note": null
      },
      {
       "label": "Vehicles and fuel",
       "level": "detail",
       "values": [
        -118,
        -110
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -84,
        -80
       ],
       "note": null
      },
      {
       "label": "Insurance",
       "level": "detail",
       "values": [
        -36,
        -33
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -28,
        -24
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -48,
        -45
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -740,
        -706
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        180,
        90
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -52,
        -48
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -14,
        -18
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        114,
        24
       ],
       "note": null
      },
      {
       "label": "Income tax (25%)",
       "level": "subtotal",
       "values": [
        -29,
        -6
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        85,
        18
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 June",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        82,
        52
       ],
       "note": null
      },
      {
       "label": "Trade debtors",
       "level": "detail",
       "values": [
        227,
        230
       ],
       "note": null
      },
      {
       "label": "Materials on hand",
       "level": "detail",
       "values": [
        66,
        62
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        22,
        20
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        397,
        364
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        250,
        262
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        647,
        626
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors",
       "level": "detail",
       "values": [
        125,
        118
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        105,
        99
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        29,
        6
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        259,
        223
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        110,
        170
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        369,
        393
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        278,
        233
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        10,
        10
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        268,
        223
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        278,
        233
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow statement",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers",
       "level": "detail",
       "values": [
        2443,
        2192
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers and employees",
       "level": "detail",
       "values": [
        -2253,
        -2133
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -14,
        -18
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        -6,
        -4
       ],
       "note": null
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        170,
        37
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        -40,
        -70
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -40,
        -70
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -60,
        -60
       ],
       "note": null
      },
      {
       "label": "Dividends paid",
       "level": "detail",
       "values": [
        -40,
        0
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -100,
        -60
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        30,
        -93
       ],
       "note": null
      },
      {
       "label": "Cash at 1 July",
       "level": "subtotal",
       "values": [
        52,
        145
       ],
       "note": null
      },
      {
       "label": "Cash at 30 June",
       "level": "key",
       "values": [
        82,
        52
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Cost to win a customer",
      "value": "$184",
      "sub": "FY2025: $239",
      "cls": "good",
      "spine": true
     },
     {
      "label": "Gross margin",
      "value": "37.7%",
      "sub": "FY2025: 36.0%",
      "cls": "good"
     },
     {
      "label": "Debtor days",
      "value": "34",
      "sub": "FY2025: 38",
      "cls": "good"
     },
     {
      "label": "Break-even revenue",
      "value": "$2.14M",
      "sub": "88% of revenue",
      "cls": ""
     }
    ],
    "chart": {
     "title": "Cost to win a customer, by month (FY2026)",
     "labels": [
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun"
     ],
     "values": [
      264.71,
      250.0,
      210.53,
      200.0,
      190.48,
      175.0,
      204.55,
      173.91,
      166.67,
      160.0,
      134.62,
      134.62
     ],
     "target": 200,
     "format": "money0",
     "what": "cost to win a customer"
    },
    "table": {
     "title": "Profit by service line, FY2026 ($'000)",
     "head": [
      "Service line",
      "Revenue",
      "Gross profit",
      "Margin"
     ],
     "rows": [
      [
       "Maintenance contracts",
       720,
       310,
       "43.1%"
      ],
      [
       "Installations",
       1180,
       360,
       "30.5%"
      ],
      [
       "Call-outs and repairs",
       540,
       250,
       "46.3%"
      ]
     ],
     "total": [
      "Total",
      2440,
      920,
      "37.7%"
     ]
    },
    "bridge": {
     "title": "Profit to cash, FY2026 ($'000)",
     "rows": [
      [
       "Net profit after tax",
       85
      ],
      [
       "Add back depreciation",
       52
      ],
      [
       "Working capital (debtors, stock, creditors)",
       10
      ],
      [
       "Tax owed but not yet paid",
       23
      ],
      [
       "Vehicles and equipment bought",
       -40
      ],
      [
       "Finance repaid",
       -60
      ],
      [
       "Dividends paid",
       -40
      ]
     ],
     "total": [
      "Change in cash",
      30
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to retained earnings, after dividends",
    "Profit-to-cash bridge ends at the change in cash"
   ],
   "assumptions": [
    [
     "The organisation",
     [
      [
       "What it is",
       "A field/trade services business: maintenance contracts, installations and call-outs. About 14 staff."
      ],
      [
       "Staff (full-time equivalent)",
       "14 (FY2025: 13)"
      ],
      [
       "Financial year",
       "1 July to 30 June; FY2026 = year to 30 June 2026"
      ]
     ]
    ],
    [
     "Revenue",
     [
      [
       "Maintenance contracts",
       "$720k (FY2025: $660k)"
      ],
      [
       "Installations",
       "$1,180k (FY2025: $1,060k)"
      ],
      [
       "Call-outs and repairs",
       "$540k (FY2025: $490k)"
      ],
      [
       "New customers won",
       "522 (FY2025: 436)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Direct costs by service line",
       "materials, subcontractors and labour set per line (see the P&L)"
      ],
      [
       "Overheads",
       "as listed in the P&L, set directly"
      ],
      [
       "Income tax",
       "25% of profit before tax (base rate entity); paid the following year"
      ],
      [
       "Superannuation",
       "included in wages"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Debtor days",
       "34 (FY2025: 38)"
      ],
      [
       "Creditor days",
       "42 days of non-wage costs"
      ],
      [
       "Materials on hand",
       "$66k at 30 June (FY2025: $62k)"
      ],
      [
       "Employee leave provisions",
       "9% of wages"
      ],
      [
       "Equipment bought",
       "$40k (FY2025: $70k)"
      ],
      [
       "Equipment finance repaid",
       "$60k a year"
      ],
      [
       "Dividends paid",
       "$40k (FY2025: $0k)"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/trades-sample-statements.xlsx",
    "pdf": "media/exports/trades-sample-statements.pdf"
   }
  },
  {
   "id": "services",
   "toggle": "SME · services",
   "name": "Sample Advisory Pty Ltd",
   "about": "A professional services consultancy: projects, monthly retainers and training. About 12 staff.",
   "columns": [
    "FY2026",
    "FY2025"
   ],
   "unit": "$'000",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Profit and loss",
     "rows": [
      {
       "label": "Revenue",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Projects",
       "level": "detail",
       "values": [
        980,
        900
       ],
       "note": null
      },
      {
       "label": "Retainers",
       "level": "detail",
       "values": [
        620,
        560
       ],
       "note": null
      },
      {
       "label": "Training",
       "level": "detail",
       "values": [
        200,
        160
       ],
       "note": null
      },
      {
       "label": "Total revenue",
       "level": "subtotal",
       "values": [
        1800,
        1620
       ],
       "note": null
      },
      {
       "label": "Cost of sales",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Subcontractors",
       "level": "detail",
       "values": [
        -130,
        -150
       ],
       "note": null
      },
      {
       "label": "Consultant salaries (incl. super)",
       "level": "detail",
       "values": [
        -830,
        -785
       ],
       "note": null
      },
      {
       "label": "Total cost of sales",
       "level": "subtotal",
       "values": [
        -960,
        -935
       ],
       "note": null
      },
      {
       "label": "Gross profit",
       "level": "total",
       "values": [
        840,
        685
       ],
       "note": null
      },
      {
       "label": "Operating expenses",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Management and admin wages",
       "level": "detail",
       "values": [
        -290,
        -280
       ],
       "note": null
      },
      {
       "label": "Marketing and business development",
       "level": "detail",
       "values": [
        -72,
        -80
       ],
       "note": null
      },
      {
       "label": "Rent and occupancy",
       "level": "detail",
       "values": [
        -96,
        -92
       ],
       "note": null
      },
      {
       "label": "IT and software",
       "level": "detail",
       "values": [
        -54,
        -48
       ],
       "note": null
      },
      {
       "label": "Professional indemnity insurance",
       "level": "detail",
       "values": [
        -30,
        -28
       ],
       "note": null
      },
      {
       "label": "Travel",
       "level": "detail",
       "values": [
        -26,
        -30
       ],
       "note": null
      },
      {
       "label": "Other overheads",
       "level": "detail",
       "values": [
        -40,
        -38
       ],
       "note": null
      },
      {
       "label": "Total operating expenses",
       "level": "subtotal",
       "values": [
        -608,
        -596
       ],
       "note": null
      },
      {
       "label": "EBITDA",
       "level": "total",
       "values": [
        232,
        89
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -24,
        -22
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "subtotal",
       "values": [
        -4,
        -6
       ],
       "note": null
      },
      {
       "label": "Profit before tax",
       "level": "total",
       "values": [
        204,
        61
       ],
       "note": null
      },
      {
       "label": "Income tax (25%)",
       "level": "subtotal",
       "values": [
        -51,
        -15
       ],
       "note": null
      },
      {
       "label": "Net profit after tax",
       "level": "key",
       "values": [
        153,
        46
       ],
       "note": null
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 June",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        211,
        106
       ],
       "note": null
      },
      {
       "label": "Trade debtors",
       "level": "detail",
       "values": [
        222,
        231
       ],
       "note": null
      },
      {
       "label": "Work in progress (unbilled)",
       "level": "detail",
       "values": [
        89,
        98
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        16,
        15
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        538,
        450
       ],
       "note": null
      },
      {
       "label": "Office equipment",
       "level": "subtotal",
       "values": [
        64,
        58
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        602,
        508
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Trade creditors",
       "level": "detail",
       "values": [
        37,
        38
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        123,
        117
       ],
       "note": null
      },
      {
       "label": "Income tax payable",
       "level": "detail",
       "values": [
        51,
        15
       ],
       "note": null
      },
      {
       "label": "Total current liabilities",
       "level": "subtotal",
       "values": [
        211,
        170
       ],
       "note": null
      },
      {
       "label": "Equipment finance",
       "level": "subtotal",
       "values": [
        0,
        20
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        211,
        190
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        391,
        318
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Share capital",
       "level": "detail",
       "values": [
        20,
        20
       ],
       "note": null
      },
      {
       "label": "Retained earnings",
       "level": "detail",
       "values": [
        371,
        298
       ],
       "note": null
      },
      {
       "label": "Total equity",
       "level": "key",
       "values": [
        391,
        318
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow statement",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Receipts from customers",
       "level": "detail",
       "values": [
        1818,
        1643
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers and employees",
       "level": "detail",
       "values": [
        -1564,
        -1547
       ],
       "note": null
      },
      {
       "label": "Interest paid",
       "level": "detail",
       "values": [
        -4,
        -6
       ],
       "note": null
      },
      {
       "label": "Income tax paid",
       "level": "detail",
       "values": [
        -15,
        -10
       ],
       "note": null
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        235,
        80
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of equipment",
       "level": "detail",
       "values": [
        -30,
        -20
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -30,
        -20
       ],
       "note": null
      },
      {
       "label": "Financing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Equipment finance repaid",
       "level": "detail",
       "values": [
        -20,
        -20
       ],
       "note": null
      },
      {
       "label": "Dividends paid",
       "level": "detail",
       "values": [
        -80,
        -30
       ],
       "note": null
      },
      {
       "label": "Net cash from financing activities",
       "level": "subtotal",
       "values": [
        -100,
        -50
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        105,
        10
       ],
       "note": null
      },
      {
       "label": "Cash at 1 July",
       "level": "subtotal",
       "values": [
        106,
        96
       ],
       "note": null
      },
      {
       "label": "Cash at 30 June",
       "level": "key",
       "values": [
        211,
        106
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Utilisation",
      "value": "75%",
      "sub": "FY2025: 73%",
      "cls": "good",
      "spine": true
     },
     {
      "label": "Revenue per billable hour",
      "value": "$167",
      "sub": "FY2025: $163",
      "cls": "good"
     },
     {
      "label": "Lock-up days (debtors + WIP)",
      "value": "63",
      "sub": "FY2025: 74",
      "cls": "good"
     },
     {
      "label": "Cost to win a client",
      "value": "$1,500",
      "sub": "FY2025: $1,951",
      "cls": "good"
     }
    ],
    "chart": {
     "title": "Utilisation by month (FY2026)",
     "labels": [
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun"
     ],
     "values": [
      66.7,
      75.0,
      84.4,
      75.0,
      84.4,
      64.3,
      53.6,
      84.4,
      75.0,
      75.0,
      75.0,
      83.3
     ],
     "target": 75,
     "format": "pct0",
     "what": "utilisation"
    },
    "table": {
     "title": "Profit by service line, FY2026 ($'000)",
     "head": [
      "Service line",
      "Revenue",
      "Gross profit",
      "Margin"
     ],
     "rows": [
      [
       "Projects",
       980,
       420,
       "42.9%"
      ],
      [
       "Retainers",
       620,
       320,
       "51.6%"
      ],
      [
       "Training",
       200,
       100,
       "50.0%"
      ]
     ],
     "total": [
      "Total",
      1800,
      840,
      "46.7%"
     ]
    },
    "bridge": {
     "title": "Profit to cash, FY2026 ($'000)",
     "rows": [
      [
       "Net profit after tax",
       153
      ],
      [
       "Add back depreciation",
       24
      ],
      [
       "Working capital (debtors, stock, creditors)",
       22
      ],
      [
       "Tax owed but not yet paid",
       36
      ],
      [
       "Vehicles and equipment bought",
       -30
      ],
      [
       "Finance repaid",
       -20
      ],
      [
       "Dividends paid",
       -80
      ]
     ],
     "total": [
      "Change in cash",
      105
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + equity",
    "Cash flow ends at the cash in the bank",
    "Profit ties to retained earnings, after dividends",
    "Profit-to-cash bridge ends at the change in cash"
   ],
   "assumptions": [
    [
     "The organisation",
     [
      [
       "What it is",
       "A professional services consultancy: projects, monthly retainers and training. About 12 staff."
      ],
      [
       "Staff (full-time equivalent)",
       "12 (FY2025: 11.5)"
      ],
      [
       "Financial year",
       "1 July to 30 June; FY2026 = year to 30 June 2026"
      ]
     ]
    ],
    [
     "Revenue",
     [
      [
       "Projects",
       "$980k (FY2025: $900k)"
      ],
      [
       "Retainers",
       "$620k (FY2025: $560k)"
      ],
      [
       "Training",
       "$200k (FY2025: $160k)"
      ],
      [
       "New customers won",
       "48 (FY2025: 41)"
      ]
     ]
    ],
    [
     "Costs",
     [
      [
       "Direct costs by service line",
       "materials, subcontractors and labour set per line (see the P&L)"
      ],
      [
       "Overheads",
       "as listed in the P&L, set directly"
      ],
      [
       "Income tax",
       "25% of profit before tax (base rate entity); paid the following year"
      ],
      [
       "Superannuation",
       "included in wages"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Debtor days",
       "45 (FY2025: 52)"
      ],
      [
       "Creditor days",
       "30 days of non-wage costs"
      ],
      [
       "Work in progress (unbilled)",
       "$89k at 30 June (FY2025: $98k)"
      ],
      [
       "Employee leave provisions",
       "11% of wages"
      ],
      [
       "Equipment bought",
       "$30k (FY2025: $20k)"
      ],
      [
       "Equipment finance repaid",
       "$20k a year"
      ],
      [
       "Dividends paid",
       "$80k (FY2025: $30k)"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ],
    [
     "Utilisation",
     [
      [
       "Billable staff",
       "9 (FY2025: 8.5)"
      ],
      [
       "Available hours per person",
       "1,600 a year"
      ],
      [
       "Billable hours",
       "10,800 (FY2025: 9,950)"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/services-sample-statements.xlsx",
    "pdf": "media/exports/services-sample-statements.pdf"
   }
  },
  {
   "id": "nfp",
   "toggle": "Not-for-profit",
   "name": "Sample Community Services Ltd",
   "about": "A community services charity: government-funded programs, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt.",
   "columns": [
    "FY2026",
    "FY2025"
   ],
   "unit": "$'000",
   "statements": {
    "pnl": {
     "tab": "P&L",
     "title": "Income and expenditure",
     "rows": [
      {
       "label": "Income",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Government grants",
       "level": "detail",
       "values": [
        1420,
        1310
       ],
       "note": null
      },
      {
       "label": "Donations",
       "level": "detail",
       "values": [
        380,
        352
       ],
       "note": null
      },
      {
       "label": "Fundraising events",
       "level": "detail",
       "values": [
        210,
        188
       ],
       "note": null
      },
      {
       "label": "Program fees",
       "level": "detail",
       "values": [
        340,
        300
       ],
       "note": null
      },
      {
       "label": "Interest",
       "level": "detail",
       "values": [
        18,
        12
       ],
       "note": null
      },
      {
       "label": "Total income",
       "level": "subtotal",
       "values": [
        2368,
        2162
       ],
       "note": null
      },
      {
       "label": "Programs",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Program delivery wages",
       "level": "detail",
       "values": [
        -1180,
        -1120
       ],
       "note": null
      },
      {
       "label": "Program costs",
       "level": "detail",
       "values": [
        -260,
        -240
       ],
       "note": null
      },
      {
       "label": "Total program spend",
       "level": "subtotal",
       "values": [
        -1440,
        -1360
       ],
       "note": null
      },
      {
       "label": "Fundraising",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grant writing and reporting",
       "level": "detail",
       "values": [
        -85,
        -80
       ],
       "note": null
      },
      {
       "label": "Event costs",
       "level": "detail",
       "values": [
        -113,
        -120
       ],
       "note": null
      },
      {
       "label": "Donor campaigns",
       "level": "detail",
       "values": [
        -46,
        -50
       ],
       "note": null
      },
      {
       "label": "Total fundraising costs",
       "level": "subtotal",
       "values": [
        -244,
        -250
       ],
       "note": null
      },
      {
       "label": "Administration",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Administration wages",
       "level": "detail",
       "values": [
        -220,
        -230
       ],
       "note": null
      },
      {
       "label": "Occupancy",
       "level": "detail",
       "values": [
        -120,
        -116
       ],
       "note": null
      },
      {
       "label": "Other administration",
       "level": "detail",
       "values": [
        -96,
        -90
       ],
       "note": null
      },
      {
       "label": "Total administration",
       "level": "subtotal",
       "values": [
        -436,
        -436
       ],
       "note": null
      },
      {
       "label": "Depreciation",
       "level": "subtotal",
       "values": [
        -34,
        -30
       ],
       "note": null
      },
      {
       "label": "Total expenses",
       "level": "total",
       "values": [
        -2154,
        -2076
       ],
       "note": null
      },
      {
       "label": "Surplus for the year",
       "level": "key",
       "values": [
        214,
        86
       ],
       "note": "Income-tax exempt charity: no income tax."
      }
     ]
    },
    "bs": {
     "tab": "Balance sheet",
     "title": "Balance sheet at 30 June",
     "rows": [
      {
       "label": "Current assets",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Cash at bank",
       "level": "detail",
       "values": [
        1161,
        926
       ],
       "note": null
      },
      {
       "label": "Grants and fees receivable",
       "level": "detail",
       "values": [
        76,
        70
       ],
       "note": null
      },
      {
       "label": "Prepayments",
       "level": "detail",
       "values": [
        26,
        24
       ],
       "note": null
      },
      {
       "label": "Total current assets",
       "level": "subtotal",
       "values": [
        1263,
        1020
       ],
       "note": null
      },
      {
       "label": "Vehicles and equipment",
       "level": "subtotal",
       "values": [
        186,
        160
       ],
       "note": null
      },
      {
       "label": "Total assets",
       "level": "total",
       "values": [
        1449,
        1180
       ],
       "note": null
      },
      {
       "label": "Current liabilities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Payables",
       "level": "detail",
       "values": [
        101,
        92
       ],
       "note": null
      },
      {
       "label": "Grants received in advance (unspent)",
       "level": "detail",
       "values": [
        340,
        300
       ],
       "note": null
      },
      {
       "label": "Employee leave provisions",
       "level": "detail",
       "values": [
        168,
        162
       ],
       "note": null
      },
      {
       "label": "Total liabilities",
       "level": "total",
       "values": [
        609,
        554
       ],
       "note": null
      },
      {
       "label": "Net assets",
       "level": "key",
       "values": [
        840,
        626
       ],
       "note": null
      },
      {
       "label": "Equity",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Accumulated funds",
       "level": "key",
       "values": [
        840,
        626
       ],
       "note": null
      }
     ]
    },
    "cf": {
     "tab": "Cash flow",
     "title": "Cash flow statement",
     "rows": [
      {
       "label": "Operating activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Grants received",
       "level": "detail",
       "values": [
        1454,
        1344
       ],
       "note": null
      },
      {
       "label": "Donations and fundraising received",
       "level": "detail",
       "values": [
        590,
        540
       ],
       "note": null
      },
      {
       "label": "Program fees received",
       "level": "detail",
       "values": [
        340,
        300
       ],
       "note": null
      },
      {
       "label": "Interest received",
       "level": "detail",
       "values": [
        18,
        12
       ],
       "note": null
      },
      {
       "label": "Payments to suppliers and employees",
       "level": "detail",
       "values": [
        -2107,
        -2050
       ],
       "note": null
      },
      {
       "label": "Net cash from operating activities",
       "level": "subtotal",
       "values": [
        295,
        146
       ],
       "note": null
      },
      {
       "label": "Investing activities",
       "level": "heading",
       "values": null,
       "note": null
      },
      {
       "label": "Purchase of vehicles and equipment",
       "level": "detail",
       "values": [
        -60,
        -40
       ],
       "note": null
      },
      {
       "label": "Net cash from investing activities",
       "level": "subtotal",
       "values": [
        -60,
        -40
       ],
       "note": null
      },
      {
       "label": "Net change in cash",
       "level": "total",
       "values": [
        235,
        106
       ],
       "note": null
      },
      {
       "label": "Cash at 1 July",
       "level": "subtotal",
       "values": [
        926,
        820
       ],
       "note": null
      },
      {
       "label": "Cash at 30 June",
       "level": "key",
       "values": [
        1161,
        926
       ],
       "note": null
      }
     ]
    }
   },
   "fourth": {
    "kpis": [
     {
      "label": "Cost to raise a dollar",
      "value": "$0.12",
      "sub": "FY2025: $0.14",
      "cls": "good",
      "spine": true
     },
     {
      "label": "Spent on programs",
      "value": "67c in $1",
      "sub": "of every dollar spent",
      "cls": ""
     },
     {
      "label": "Cost per program hour",
      "value": "$62",
      "sub": "FY2025: $60",
      "cls": ""
     },
     {
      "label": "Cash runway (unrestricted)",
      "value": "4.6 months",
      "sub": "Target 3 months",
      "cls": "good"
     }
    ],
    "chart": {
     "title": "Where each dollar goes (FY2026, cents)",
     "labels": [
      "Programs",
      "Fundraising",
      "Admin",
      "Occupancy"
     ],
     "values": [
      67,
      11,
      15,
      7
     ],
     "target": null,
     "format": "cents_int",
     "what": "spending per dollar"
    },
    "table": {
     "title": "Funding sources, FY2026 ($'000)",
     "head": [
      "Source",
      "Raised",
      "Share",
      "Cost per $1"
     ],
     "rows": [
      [
       "Government grants",
       1420,
       "71%",
       "$0.06"
      ],
      [
       "Donations",
       380,
       "19%",
       "$0.12"
      ],
      [
       "Fundraising events",
       210,
       "10%",
       "$0.54"
      ]
     ],
     "total": [
      "Total",
      2010,
      "100%",
      "$0.12"
     ]
    },
    "bridge": {
     "title": "Surplus to cash, FY2026 ($'000)",
     "rows": [
      [
       "Surplus for the year",
       214
      ],
      [
       "Add back depreciation",
       34
      ],
      [
       "Grants received in advance (unspent)",
       40
      ],
      [
       "Working capital (receivables, payables)",
       7
      ],
      [
       "Vehicles and equipment bought",
       -60
      ]
     ],
     "total": [
      "Change in cash",
      235
     ]
    }
   },
   "checks": [
    "Every subtotal and total adds up",
    "Balance sheet balances: assets = liabilities + accumulated funds",
    "Cash flow ends at the cash in the bank",
    "Surplus ties to the movement in accumulated funds",
    "Profit-to-cash bridge ends at the change in cash"
   ],
   "assumptions": [
    [
     "The organisation",
     [
      [
       "What it is",
       "A community services charity: government-funded programs, donations, events and program fees. About 18 staff. Registered charity, income-tax exempt."
      ],
      [
       "Staff (full-time equivalent)",
       "18 (FY2025: 17)"
      ],
      [
       "Financial year",
       "1 July to 30 June; FY2026 = year to 30 June 2026"
      ]
     ]
    ],
    [
     "Income",
     [
      [
       "Government grants",
       "$1,420k (FY2025: $1,310k)"
      ],
      [
       "Donations",
       "$380k (FY2025: $352k)"
      ],
      [
       "Fundraising events",
       "$210k (FY2025: $188k)"
      ],
      [
       "Program fees",
       "$340k (FY2025: $300k)"
      ],
      [
       "Interest",
       "$18k (FY2025: $12k)"
      ]
     ]
    ],
    [
     "Spending",
     [
      [
       "Program, fundraising and admin costs",
       "set directly (see Income and expenditure)"
      ],
      [
       "Program hours delivered",
       "23,200 (FY2025: 22,600)"
      ],
      [
       "Income tax",
       "none: registered charity, income-tax exempt"
      ]
     ]
    ],
    [
     "Cash and balance sheet",
     [
      [
       "Grants received in advance (unspent)",
       "$340k at 30 June (FY2025: $300k)"
      ],
      [
       "Receivables / prepayments / payables",
       "$76k / $26k / $101k at 30 June"
      ],
      [
       "Employee leave provisions",
       "12% of wages"
      ],
      [
       "Equipment bought",
       "$60k (FY2025: $40k)"
      ],
      [
       "Unrestricted cash",
       "cash at bank less grants received in advance"
      ],
      [
       "Reserves target",
       "3 months of spending"
      ],
      [
       "GST",
       "excluded throughout, for simplicity"
      ]
     ]
    ]
   ],
   "exports": {
    "xlsx": "media/exports/nfp-sample-statements.xlsx",
    "pdf": "media/exports/nfp-sample-statements.pdf"
   }
  }
 ]
};
