"""
build.py — run a report for a period, and write it out.

    data = load_data()                                   # from the data source (CSV folder today)
    r = run_report("job-margins", "2026-06", data)       # the report, worked out for June 2026
    write_files(r, ["xlsx", "pdf", "pptx"])              # Excel, PDF and PowerPoint, built from scratch

Every file is generated in code from the report (no templates): Excel cell by cell with formulas
(openpyxl), the PDF as an HTML page printed by headless Chrome, PowerPoint slide by slide with native charts
(python-pptx). The website gets the same report as data, for every period, so its Period dropdown works.
"""

import json
from pathlib import Path

import data_status as ds

from .catalogue import NEEDS_CASH, REPORTS, cash_months
from .period import CURRENT, Period
from .source import load

REPO = Path(__file__).resolve().parents[2]
EXPORTS = REPO / "media" / "exports" / "reports"
FIRST_PERIOD_GAP = 12        # a period needs a year of history before it (year-on-year comparisons)


def load_data(src=None):
    src, D = load(src)
    from .catalogue import engagements, jobs
    D["_src"] = src
    D["_jobs"] = jobs(src)
    D["_engagements"] = engagements(src)
    D["_targets"] = {t["target"]: t["value"] for t in src.table("nfp", "target")}
    D["_current_grants"] = {i["grant_id"] for i in src.table("nfp", "fact_grant_instalment")}
    D["_grant_first"] = min(r["month_key"] for r in src.table("nfp", "fact_grant_spend_month"))
    return D


def periods_for(slug, D):
    """The periods a report can be run for, newest first."""
    months = D["trades"].months
    if slug in NEEDS_CASH:
        ok = cash_months(D)
    else:
        ok = months[FIRST_PERIOD_GAP:]
    if slug == "cost-to-win":       # needs the month's count of new customers
        ok = [m for m in ok if m in D["trades"].drivers["New customers (first job ever)"]]
    return [m for m in reversed(ok) if m <= CURRENT]


def default_period(slug, D):
    """The latest month that's over (locked or provisional): what a report shows unless asked otherwise."""
    return next(m for m in periods_for(slug, D) if ds.month_status(m)[0] != "Incomplete")


def run_report(slug, period, D):
    if slug not in REPORTS:
        raise SystemExit(f"No report called {slug!r}. Reports: {', '.join(REPORTS)}")
    if period not in periods_for(slug, D):
        raise SystemExit(f"{slug} can't be run for {period}. Periods with enough data: {', '.join(sorted(periods_for(slug, D)))}")
    P = Period(period, D["trades"].months)
    r = REPORTS[slug](D, P)
    r["periods"] = [Period(m, D["trades"].months).option() for m in periods_for(slug, D)]
    r["default_period"] = default_period(slug, D)
    return r


def out_dir(r):
    return EXPORTS / r["period"]


def write_files(r, formats, out=None):
    """Excel / PDF / PowerPoint for one report and period. Returns the paths written."""
    import build_reports as br
    out = Path(out) if out else out_dir(r)
    out.mkdir(parents=True, exist_ok=True)
    done = []
    for part in br.file_parts(r):        # one set of files per business
        f = br.file_name(part)
        if "xlsx" in formats:
            review = br.write_xlsx(part, out)
            done.append((out / f"{f}.xlsx", " | ".join(review)))
        if "pptx" in formats:
            br.write_pptx(part, out)
            done.append((out / f"{f}.pptx", ""))
        if "pdf" in formats:
            br.write_pdfs([part], out)
            done.append((out / f"{f}.pdf", ""))
    return done


def site_payload(r):
    import build_reports as br
    return br.page_payload([r])[r["slug"]]


def write_site(all_runs):
    """data/reports-data.js (each report at its default period, plus the list of periods) and
    data/reports/<slug>/<period>.js (every other period, loaded when someone picks it)."""
    import build_reports as br
    import exportkit as ek
    base = {}
    for slug, runs in all_runs.items():
        for r in runs:
            parts = br.file_parts(r)
            per = ek.period_name(r["period"], r["period_status"] == "Incomplete")
            meta = lambda p_: ek.export_meta({k: f"media/exports/reports/{r['period']}/{br.file_name(p_)}.{k}" for k in ("xlsx", "pdf", "pptx")},
                                             p_["business"], br.SHORT.get(r["slug"], r["slug"]), per)
            r["exports_meta"] = meta(parts[0])
            r["_parts"] = [{"file": br.file_name(p_), "label": p_["blocks"][0].get("label") if len(parts) > 1 else None, "meta": meta(p_)} for p_ in parts]
            p = site_payload(r)
            if r["period"] == r["default_period"]:
                base[slug] = p
            d = REPO / "data" / "reports" / slug
            d.mkdir(parents=True, exist_ok=True)
            js = (f"/* GENERATED by tools/fourthsheet from the data, for {r['period_label']}. Sample data. */\n"
                  f"(window.FOURTH_SHEET_PERIODS = window.FOURTH_SHEET_PERIODS || {{}})[{json.dumps(slug + '|' + r['period'])}] = "
                  + json.dumps(p, ensure_ascii=False, separators=(",", ":")) + ";\n")
            f = d / f"{r['period']}.js"
            if not f.exists() or f.read_text() != js:
                f.write_text(js)
    js = ("/* reports-data.js — GENERATED by tools/fourthsheet from the data. Don't edit by hand.\n"
          "   Invented sample data: each report at its default period. Other periods: data/reports/<report>/<period>.js. */\n"
          "window.FOURTH_SHEET_REPORTS = " + json.dumps(base, ensure_ascii=False, separators=(",", ":")) + ";\n")
    (REPO / "data" / "reports-data.js").write_text(js)
    return len(js)


LAST_DATA = None


def build_all(formats=("xlsx", "pdf", "pptx"), quiet=False):
    """Every report for every period it can run for: the website's data and pages, and every download.
    Returns the reports at their default periods (for the cards and the Power BI prompts)."""
    import build_reports as br
    global LAST_DATA
    D = LAST_DATA = load_data()          # kept, so later steps reuse it rather than re-read files OneDrive is still syncing
    runs = {slug: [run_report(slug, p, D) for p in periods_for(slug, D)] for slug in REPORTS}
    defaults = [next(r for r in rs if r["period"] == r["default_period"]) for rs in runs.values()]
    br.write_pages(defaults)
    br.write_cards(defaults)
    br.write_explainer()
    flat = [r for rs in runs.values() for r in rs]
    files = [part for r in flat for part in br.file_parts(r)]       # one set of downloads per business
    for r in files:
        if "xlsx" in formats:
            review = br.write_xlsx(r, out_dir(r))
            if not quiet and r["period"] == r["default_period"]:
                print(f"  {br.file_name(r)}.xlsx: " + " | ".join(review))
        if "pptx" in formats:
            br.write_pptx(r, out_dir(r))
    if "pdf" in formats:
        br.write_pdfs(files)
    size = write_site(runs)          # after the files, so the Export menu can say how many pages and slides they have
    from .dashboard_months import build as dashboard_months      # the home dashboard for every month (checks September against the model)
    n_months = dashboard_months(D)
    print(f"  {len(runs)} reports × their periods = {len(flat)} runs, each as Excel, PDF and PowerPoint (media/exports/reports/<period>/); "
          f"data/reports-data.js {size // 1024} KB + one file per period; home dashboard: {n_months} months")
    return defaults
