#!/usr/bin/env python3
"""
build_versions.py — rebuild the themed "old versions" from the main home page.

Each versions/<theme>/index.html is GENERATED from the current index.html, so
the copy, sections and dashboard always match the main site. Only the look
differs: the page loads the main styles.css first, then the theme's own
versions/<theme>/styles.css on top. Every theme uses the main script.js and
dashboard-data.js (the themes' old copies of the 2026 script were removed,
including the old email-macro code).

Run from the repo root after changing index.html:
    python3 tools/build_versions.py
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
THEMES = ["apple", "as400", "geocities", "insta", "modern", "nes", "sms", "snes", "social"]
PAGES = ["index.html", "sme.html", "not-for-profit.html", "work.html", "how-we-work.html", "about.html"]
EXTRA_SCRIPTS = {"nes": ['<script src="launcher.js"></script>']}  # the old NES game launcher in the footer


def build(theme, src):
    s = src
    # assets and pages live two folders up
    s = re.sub(r'(href|src)="(styles\.css|script\.js|dashboard-data\.js)(\?[^"]*)?"', r'\1="../../\2\3"', s)
    s = re.sub(r'(href|src)="(Assets/|media/|game/)', r'\1="../../\2', s)
    for p in PAGES:
        s = re.sub(rf'href="{re.escape(p)}(#[^"]*)?"', lambda m: f'href="../../{p}{m.group(1) or ""}"', s)
    s = s.replace('<a class="brand" href="#top">', '<a class="brand" href="../../index.html">')
    # theme stylesheet on top of the main one; not indexed by search engines
    s = re.sub(r'(<link rel="stylesheet" href="\.\./\.\./styles\.css[^"]*" />)',
               r'\1\n    <!-- Theme look for this old version, layered over the main styles -->\n    <link rel="stylesheet" href="styles.css" />', s, count=1)
    s = s.replace('<meta charset="UTF-8" />', '<meta charset="UTF-8" />\n    <meta name="robots" content="noindex" />', 1)
    s = re.sub(r'<title>(.*?)</title>', rf'<title>\1 ({theme} theme)</title>', s, count=1)
    if theme in EXTRA_SCRIPTS:
        s = s.replace('    <script src="../../dashboard-data.js', '    ' + '\n    '.join(EXTRA_SCRIPTS[theme]) + '\n    <script src="../../dashboard-data.js', 1)
    s = s.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- GENERATED by tools/build_versions.py from ../../index.html: edit the main page, then re-run. -->', 1)
    return s


def main():
    src = (REPO / "index.html").read_text()
    for t in THEMES:
        (REPO / "versions" / t / "index.html").write_text(build(t, src))
        css = REPO / "versions" / t / "styles.css"
        c = css.read_text()
        # the main header now has its own 4S mark; drop the theme's old pseudo-element badge
        c = c.replace('content: "4";', 'content: none;')
        css.write_text(c)
        old_js = REPO / "versions" / t / "script.js"
        if old_js.exists():
            old_js.unlink()
    print("Rebuilt:", ", ".join(THEMES))


if __name__ == "__main__":
    main()
