#!/usr/bin/env python3
"""
build_reports.py — one page per question on the SME and not-for-profit pages.

Writes, from tools/reports.py:
  report-<slug>.html                 the page (header, nav, contact and footer copied from sme.html,
                                     so every page stays the same; the report itself is drawn by script.js)
  data/reports-data.js               what the pages read (each set of workings stored once)
  media/exports/reports/<slug>.xlsx  data as values, every calculation a formula, print-checked
  media/exports/reports/<slug>.pdf   A4, vector charts, header and footer on every page

Run via tools/sample_data.py.
"""

import copy
import json
import re
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill
from openpyxl.utils import get_column_letter

import data_status as ds
import exportkit as ek
import publish_dashboard as pd

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "media" / "exports" / "reports"
AUDIENCE = {"sme": ("sme.html", "SMEs"), "nfp": ("not-for-profit.html", "Not-for-profits")}


# ------------------------------------------------------------------ page data

def strip(o):
    """Drop the Excel-only parts of every set of workings."""
    if isinstance(o, dict):
        return {k: strip(v) for k, v in o.items() if k != "xl"}
    if isinstance(o, list):
        return [strip(v) for v in o]
    return o


def page_payload(reports):
    out = {}
    for r in reports:
        r = copy.deepcopy(r)
        for b in r["blocks"]:
            for sec in b["sections"]:
                if sec["type"] == "series":
                    sups = {}
                    for vid, v in sec["views"].items():
                        line = vid.split("|")[0]
                        if v.get("supports") and line not in sups:
                            sups[line] = v["supports"]
                        v.pop("supports", None)
                    sec["supports"] = sups
        r.pop("data", None)
        for b in r["blocks"]:
            b.pop("data", None)
            b.pop("table_xl", None)
        r["exports"] = {"xlsx": f"media/exports/reports/{r['slug']}.xlsx", "pdf": f"media/exports/reports/{r['slug']}.pdf"}
        r["status"] = [{"label": date.fromisoformat(m + "-01").strftime("%B %Y"), "status": ds.month_status(m)[0], "note": ds.month_status(m)[1]}
                       for m in ("2026-09", "2026-10")]
        out[r["slug"]] = strip(r)
    return out


def write_js(reports):
    js = ("/* reports-data.js — GENERATED by tools/build_reports.py from tools/reports.py. Don't edit by hand.\n"
          "   Invented sample data: the report behind each question on the SME and not-for-profit pages. */\n"
          "window.FOURTH_SHEET_REPORTS = " + json.dumps(page_payload(reports), ensure_ascii=False, separators=(",", ":")) + ";\n")
    (REPO / "data" / "reports-data.js").write_text(js)
    return len(js)


# ---------------------------------------------------------------------- pages

def write_pages(reports):
    sme = (REPO / "sme.html").read_text()
    head, rest = sme.split("<main id=\"main\">", 1)
    main, tail = rest.split("</main>", 1)
    contact = main[main.index("      <!-- CONTACT -->"):]
    dialog = ('''      <dialog class="assumptions" id="support-dialog" aria-labelledby="support-title">
        <div class="assumptions-head">
          <h2 id="support-title">How it's worked out</h2>
          <button type="button" class="assumptions-close" id="support-close" aria-label="Close">&times;</button>
        </div>
        <div class="assumptions-body" id="support-body"></div>
      </dialog>
''')
    v = re.search(r'script\.js\?v=([\w-]+)', sme).group(1)
    for r in reports:
        page, label = AUDIENCE[r["audience"]]
        h = head.replace("<title>SMEs | The Fourth Sheet</title>", f"<title>{r['question']} | The Fourth Sheet</title>")
        h = re.sub(r'(<meta name="description" content=")[^"]*', lambda m: m.group(1) + r["intro"].replace('"', "'"), h, count=1)
        h = h.replace("/sme.html", f"/report-{r['slug']}.html").replace("SMEs | The Fourth Sheet", f"{r['question']} | The Fourth Sheet")
        if r["audience"] == "nfp":
            h = h.replace('<a href="sme.html" aria-current="page">SME</a>', '<a href="sme.html">SME</a>')
            h = h.replace('<a href="not-for-profit.html">Not-for-profit</a>', '<a href="not-for-profit.html" aria-current="page">Not-for-profit</a>')
        body = f'''<main id="main">
      <!-- REPORT: generated by tools/build_reports.py from tools/reports.py ({r['slug']}). Sample data. -->
      <section class="section page-top report-page" id="report" data-report="{r['slug']}">
        <div class="container">
          <p class="eyebrow"><a href="{page}">{label}</a> · Example report</p>
          <h1>{r['question']}</h1>
          <p class="lead">{r['intro']}</p>
          <p class="report-meta" id="report-meta"><span class="dash-sample">Sample data</span> {r['business']}</p>
          <div id="report-root"><noscript><p>Turn on JavaScript to see this report, or download it:
            <a href="media/exports/reports/{r['slug']}.pdf">PDF</a> · <a href="media/exports/reports/{r['slug']}.xlsx">Excel</a>.</p></noscript></div>
          <div class="report-downloads"><span>Download this report:</span>
            <span class="dash-actions"><a href="media/exports/reports/{r['slug']}.xlsx" download>Excel</a><a href="media/exports/reports/{r['slug']}.pdf" download>PDF</a></span>
            <a class="report-back" href="{page}#reports">&larr; Back to {label}</a></div>
        </div>
{dialog}      </section>
{contact}    </main>'''
        t = tail.replace(f'<script src="script.js?v={v}"></script>',
                         f'<script src="data/reports-data.js?v={v}"></script>\n    <script src="script.js?v={v}"></script>')
        (REPO / f"report-{r['slug']}.html").write_text(h + body + t)


# ---------------------------------------------------------------------- Excel

def write_xlsx(r):
    wb = Workbook()
    filename = f"{r['slug']}.xlsx"
    retrieved = ds.as_at_text()
    sub = f"{r['business']} · SAMPLE DATA (invented) · The Fourth Sheet"
    status = ("Data status: " + " · ".join(f"{date.fromisoformat(m + '-01').strftime('%b %Y')} {ds.month_status(m)[0].lower()}"
                                           for m in ("2026-08", "2026-09", "2026-10")) + f" (data retrieved {retrieved})")
    pages = {}
    ws = wb.active
    ws.title = "Report"
    wk = wb.create_sheet("Workings")
    pd.title_block(ws, r["question"], sub, status)
    pd.title_block(wk, "How each number is worked out", sub, status)
    rr, wr, wstarts, starts = 5, 5, [], []
    ws.cell(rr, 1, r["intro"]).alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells(start_row=rr, start_column=1, end_row=rr, end_column=4)
    ws.row_dimensions[rr].height = 32
    rr += 2
    blocks = r["blocks"]
    for b in blocks:
        if b.get("label"):
            starts.append(rr)
            ws.cell(rr, 1, b["label"]).font = Font(bold=True, size=13, color=pd.GREEN)
            rr += 1
        for sec in b["sections"]:
            t = sec["type"]
            if t == "kpis":
                starts.append(rr)
                pd.head_cells(ws, rr, ["Headline number", "Value", "Compared with"])
                for it in sec["items"]:
                    rr += 1
                    wr, rowmap, st = pd.xl_support(wk, wr, it["support"])
                    wstarts.append(st)
                    last = it["support"]["xl"]["rows"][-1]
                    ws.cell(rr, 1, it["label"])
                    c = ws.cell(rr, 2, f"=Workings!B{rowmap[len(it['support']['xl']['rows']) - 1]}")
                    c.number_format = pd.F[last["kind"]]
                    ws.cell(rr, 3, it.get("sub", "")).font = Font(color=pd.MUTED)
                rr += 2
            elif t == "bars":
                ch = sec["chart"]
                starts.append(rr)
                ws.cell(rr, 1, ch["title"]).font = Font(bold=True, color=pd.INK)
                rr += 1
                views = ch.get("views") or [{"label": "Value", "values": ch["values"], "format": ch["format"]}]
                pd.head_cells(ws, rr, ["", *[vw["label"] for vw in views]])
                det = ch.get("details") or []
                for i, lab in enumerate(ch["labels"]):
                    rr += 1
                    ws.cell(rr, 1, lab)
                    if det:
                        wr, rowmap, st = pd.xl_support(wk, wr, det[i])
                        wstarts.append(st)
                        n = len(det[i]["xl"]["rows"])
                    for c, vw in enumerate(views, 2):
                        pc = vw["format"].startswith("pct")
                        if det:
                            kinds = [x["kind"] for x in det[i]["xl"]["rows"]]
                            want = "pct" if pc else "money"
                            row_i = max(j for j, k in enumerate(kinds) if k == want)
                            ws.cell(rr, c, f"=Workings!B{rowmap[row_i]}").number_format = pd.F[want]
                        else:
                            val = vw["values"][i]
                            kind = "pct" if pc else "cents" if vw["format"] == "cents_int" else "money"
                            ws.cell(rr, c, val / 100 if pc else val).number_format = pd.F[kind]
                if sec.get("support"):
                    wr, rowmap, st = pd.xl_support(wk, wr, sec["support"])
                    wstarts.append(st)
                rr += 2
            elif t in ("text", "list"):
                starts.append(rr)
                items = [("What it shows", sec["shows"]), ("What you'd do about it", sec["action"])] if t == "text" else [(sec["title"], "\n".join("• " + x for x in sec["items"]))]
                for head, body in items:
                    ws.cell(rr, 1, head).font = Font(bold=True, color=pd.GREEN)
                    c = ws.cell(rr + 1, 1, body)
                    c.alignment = Alignment(wrap_text=True, vertical="top")
                    ws.merge_cells(start_row=rr + 1, start_column=1, end_row=rr + 1, end_column=4)
                    ws.row_dimensions[rr + 1].height = 15 * max(2, len(body) // 95 + body.count("\n") + 1)
                    rr += 3
            elif t == "table":
                if b.get("table_xl"):
                    continue          # written with formulas on the block's own sheet
                starts.append(rr)
                ws.cell(rr, 1, sec["title"]).font = Font(bold=True, color=pd.INK)
                rr += 1
                pd.head_cells(ws, rr, sec["head"])
                for row_ in sec["rows"]:
                    rr += 1
                    for c, v in enumerate(row_, 1):
                        ws.cell(rr, c, v).alignment = Alignment(horizontal="left" if c == 1 else "right")
                rr += 2
            elif t == "series":
                ws.cell(rr, 1, f"{sec['title']}: every month is on the Data sheet{'s' if len(blocks) > 1 else ''}.").font = Font(italic=True, color=pd.MUTED)
                rr += 2
    for col, wdt in zip("ABCD", (52, 20, 44, 18)):
        ws.column_dimensions[col].width = wdt
    wk.column_dimensions["A"].width = 58
    for col in "BCD":
        wk.column_dimensions[col].width = 20
    pages["Report"] = (None, starts, rr)
    pages["Workings"] = (None, wstarts, wr)

    # data sheets: values as data, calculations as formulas
    datas = [(r.get("data"), "Data")] if r.get("data") else []
    for b in blocks:
        if b.get("data"):
            datas.append((b["data"], f"Data {b['label']}"[:31]))
        if b.get("table_xl"):
            datas.append((b["table_xl"], f"12 months {b['label']}"[:31]))
    for d, name in datas:
        w = wb.create_sheet(name)
        pd.title_block(w, name, sub, status)
        r0 = 5
        refs = {}
        for key_, lab, val, kind in d.get("inputs", []):
            w.cell(r0, 1, lab)
            c = w.cell(r0, 2, val)
            c.number_format = pd.F[kind]
            refs[key_] = f"$B${r0}"
            r0 += 1
        hr = r0 + (1 if d.get("inputs") else 0)
        pd.head_cells(w, hr, d["head"])
        grp_starts = []
        prev = None
        for i, row_ in enumerate(d["rows"]):
            rw = hr + 1 + i
            if prev is not None and row_[0] != prev and name.startswith("Data") and len(d["rows"]) > 30:
                grp_starts.append(rw)
            prev = row_[0]
            for c, (v, kind) in enumerate(zip(row_, d["kinds"]), 1):
                if isinstance(v, str) and v.startswith("="):
                    v = v.replace("{r}", str(rw))
                    for k_, ref in refs.items():
                        v = v.replace("{" + k_ + "}", ref)
                cell = w.cell(rw, c, v)
                cell.number_format = pd.F[kind]
                if kind != "text":
                    cell.alignment = Alignment(horizontal="right")
        for c in range(1, len(d["head"]) + 1):
            w.column_dimensions[get_column_letter(c)].width = 34 if c == 1 else 16
        w.freeze_panes = f"B{hr + 1}"
        pages[name] = (hr, grp_starts, hr + len(d["rows"]))
    review = []
    for w in wb.worksheets:
        hr, st, last = pages[w.title]
        ek.xl_print(w, r["business"], filename, retrieved, landscape=True, header_row=hr)
        review.append(ek.xl_review(w, ek.xl_breaks(w, st, last, hr), hr))
    OUT.mkdir(parents=True, exist_ok=True)
    wb.save(OUT / filename)
    return review


# ------------------------------------------------------------------------ PDF

def html_report(r):
    esc = ek.esc
    parts = []
    for b in r["blocks"]:
        if b.get("label"):
            parts.append(f"<h2 class=block>{esc(b['label'])}</h2>")
        for sec in b["sections"]:
            t = sec["type"]
            if t == "kpis":
                parts.append("<div class=kpis>" + "".join(f"<div class=kpi><span>{esc(i['label'])}</span><b>{esc(i['value'])}</b><em>{esc(i.get('sub', ''))}</em></div>" for i in sec["items"]) + "</div>")
            elif t == "bars":
                ch = sec["chart"]
                views = ch.get("views") or [{"label": "", "values": ch["values"], "format": ch["format"], "target": ch.get("target")}]
                parts.append(f"<h3>{esc(ch['title'])}</h3>")
                for vw in views:
                    if len(views) > 1:
                        parts.append(f"<p class=viewlabel>{esc(vw['label'])}</p>")
                    parts.append("<div class=chart>" + ek.hbar_svg({**ch, **{k: vw.get(k) for k in ("values", "format", "target", "marks", "mark_label", "below_marks")}}) + "</div>")
            elif t == "series":
                dims = sec.get("dims") or {}
                line = (dims.get("line") or ["All"])[0]
                parts.append(f"<h3>{esc(sec['title'])}</h3>")
                for mid, mlab in (dims.get("measure") or [])[:2]:
                    vw = sec["views"].get(f"{line}|{mid}")
                    if not vw:
                        continue
                    parts.append(f"<p class=viewlabel>{esc(line if line != 'All' else 'All')} · {esc(mlab)}</p>")
                    vals = [v if v is not None else None for v in vw["values"]]
                    f = {"money0": "money0", "pct1": "pct1", "cents_int": "cents_int", "int": "int"}.get(vw["format"], "money0")
                    parts.append("<div class=chart>" + ek.col_svg(sec["labels"], vals, sec["status"], f) + "</div>")
                if sec.get("note"):
                    parts.append(f"<p class=note>{esc(sec['note'].replace(' Tap a month for its workings.', ''))} Every month, by line, is in the Excel download.</p>")
            elif t == "table":
                parts.append(f"<h3>{esc(sec['title'])}</h3><table><tr>" + "".join(f"<th{' class=n' if i else ''}>{esc(h)}</th>" for i, h in enumerate(sec["head"])) + "</tr>"
                             + "".join("<tr>" + "".join(f"<td{' class=n' if i else ''}>{esc(c)}</td>" for i, c in enumerate(row_)) + "</tr>" for row_ in sec["rows"]) + "</table>")
            elif t == "text":
                parts.append(f"<div class=two><div class=box><h4>What it shows</h4><p>{esc(sec['shows'])}</p></div><div class='box act'><h4>What you'd do about it</h4><p>{esc(sec['action'])}</p></div></div>")
            elif t == "list":
                parts.append(f"<h3>{esc(sec['title'])}</h3><ul>" + "".join(f"<li>{esc(x)}</li>" for x in sec["items"]) + "</ul>")
    status = ek.status_box_html([(date.fromisoformat(m + "-01").strftime("%B %Y"), *ds.month_status(m)) for m in ("2026-08", "2026-09", "2026-10")])
    return f"""<!doctype html><html><head><meta charset=utf-8>
<link rel=stylesheet href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap">
<style>
@page {{ size: A4; }} body {{ font-family: Inter, Arial, sans-serif; color: #25342a; font-size: 10pt; margin: 0; }}
header {{ display: flex; align-items: center; gap: 10px; border-bottom: 3px solid #2f7a5d; padding-bottom: 6px; margin-bottom: 8px; }}
.mark {{ min-width: 28px; height: 28px; padding: 0 4px; border-radius: 7px; background: #2f7a5d; color: #fff; font-weight: 800; display: flex; align-items: center; justify-content: center; }}
sup {{ font-size: .55em; }} header small {{ margin-left: auto; color: #5f6f63; }}
.sample {{ display: inline-block; background: #f6f1e7; border: 1px solid #c8a77e; color: #6b5532; border-radius: 4px; padding: 1px 7px; font-size: 8pt; font-weight: 700; }}
h1 {{ font-size: 16pt; margin: 6px 0 2px; }} .intro {{ color: #5f6f63; margin: 0 0 6px; }} h2.block {{ font-size: 13pt; color: #2f7a5d; margin: 14px 0 4px; page-break-before: always; }}
h3 {{ font-size: 10.5pt; margin: 12px 0 4px; }} .viewlabel {{ margin: 4px 0 0; font-size: 8.5pt; font-weight: 700; color: #5f6f63; }}
.kpis {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 6px; margin: 6px 0; }} .kpi {{ border: 1px solid #dce8dc; border-radius: 6px; padding: 6px 8px; page-break-inside: avoid; }}
.kpi span, .kpi em {{ display: block; font-size: 8pt; color: #5f6f63; font-style: normal; }} .kpi b {{ font-size: 14pt; color: #2f7a5d; }}
.chart {{ page-break-inside: avoid; margin: 2px 0 6px; }} .note {{ font-size: 8pt; color: #5f6f63; }}
.two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; page-break-inside: avoid; margin: 8px 0; }} .box {{ border: 1px solid #dce8dc; border-radius: 6px; padding: 6px 10px; }}
.box.act {{ background: #eef5f0; }} .box h4 {{ margin: 0 0 3px; font-size: 9.5pt; color: #2f7a5d; }} .box p {{ margin: 0; }}
table {{ width: 100%; border-collapse: collapse; page-break-inside: avoid; font-size: 9pt; }} th {{ text-align: left; background: #2f7a5d; color: #fff; padding: 3px 6px; }}
td {{ padding: 3px 6px; border-bottom: 1px solid #eef2ee; }} .n {{ text-align: right; font-variant-numeric: tabular-nums; }} ul {{ margin: 4px 0 8px; padding-left: 18px; }} li {{ margin: 3px 0; }}
""" + ek.STATUS_CSS + f"""</style></head><body>
<header><div class=mark>4<sup>th</sup></div><b>The 4<sup>th</sup> Sheet</b><small>Example report · {esc(AUDIENCE[r['audience']][1])}</small></header>
<span class=sample>SAMPLE DATA · invented figures for demonstration</span>
<h1>{esc(r['question'])}</h1><p class=intro>{esc(r['intro'])}</p>
{status}
{''.join(parts)}
</body></html>"""


def write_pdfs(reports):
    from playwright.sync_api import sync_playwright
    OUT.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as pw:
        try:
            browser = pw.chromium.launch(channel="chrome")
        except Exception:
            browser = pw.chromium.launch()
        page = browser.new_page()
        for r in reports:
            page.set_content(html_report(r), wait_until="networkidle")
            page.evaluate("document.fonts.ready")
            page.pdf(path=str(OUT / f"{r['slug']}.pdf"), **ek.pdf_options(r["business"], r["question"], f"{r['slug']}.pdf", ds.as_at_text()))
        browser.close()


def write_cards(reports):
    """The 'Example reports' cards on the SME and not-for-profit pages (between the REPORT CARDS markers)."""
    import html as H
    for aud, page in (("sme", "sme.html"), ("nfp", "not-for-profit.html")):
        cards = []
        for r in [x for x in reports if x["audience"] == aud]:
            shows = next((sec["shows"] for b in r["blocks"] for sec in b["sections"] if sec["type"] == "text"), r["intro"])
            first = shows.split(". ")[0].rstrip(".") + "."
            cards.append(f'            <li><h3><a href="report-{r["slug"]}.html">{H.escape(r["question"])}</a></h3>'
                         f'<p>{H.escape(first)}</p><a class="report-open" href="report-{r["slug"]}.html">Open the report &rarr;</a></li>')
        if aud == "sme":
            cards.append('            <li class="report-later"><h3>Will cash cover payroll next month?</h3><p>A 13-week cash forecast built from your bank and '
                         'accounting system, with room for what you expect that the systems don\'t know yet. Coming soon.</p></li>')
        f = REPO / page
        s_ = f.read_text()
        a_, b_ = s_.index("<!-- REPORT CARDS:START -->"), s_.index("<!-- REPORT CARDS:END -->")
        s_ = s_[:a_] + "<!-- REPORT CARDS:START -->\n          <ul class=\"report-cards\">\n" + "\n".join(cards) + "\n          </ul>\n          " + s_[b_:]
        f.write_text(s_)


def publish(reports):
    size = write_js(reports)
    write_pages(reports)
    write_cards(reports)
    for r in reports:
        review = write_xlsx(r)
        print(f"  {r['slug']}.xlsx: " + " | ".join(review))
    write_pdfs(reports)
    print(f"  {len(reports)} report pages, data/reports-data.js {size // 1024} KB")
