#!/usr/bin/env python3
"""
publish_dashboard.py — turns the checked financial model (financial_model.py)
into everything the website and your database use:

  dashboard-data.js                       data for the home-page dashboard
  media/exports/<org>-sample-statements.xlsx   formatted Excel workbook
  media/exports/<org>-sample-statements.pdf    A4 PDF report
  (CSV rows for the OneDrive data folder are returned to sample_data.py)

Run via:  python3 tools/sample_data.py   (it calls this)
Needs:    pip install openpyxl playwright   (PDFs use your installed Chrome)
"""

import json
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

import data_status as ds
import exportkit as ek

Font = ek.xl_font       # every Excel font is Roboto (exportkit.XL_FONT)
import financial_model as fm

STATUS_MONTHS = ["2026-09", "2026-08", "2026-10"]   # the reported month, the comparison, and the month now running

REPO = Path(__file__).resolve().parent.parent
EXPORTS = REPO / "media" / "exports"
ORDER = ["trades", "services", "nfp"]
TOGGLE = {"trades": "SME · trades", "services": "SME · services", "nfp": "Not-for-profit"}
GREEN, DARK, INK, MUTED, SOFT, LINE = "2F7A5D", "1F5A43", "25342A", "5F6F63", "EAF6EE", "DCE8DC"


def statements(org, v):
    nfp = org == "nfp"
    o = v["out"]
    return {
        "pnl": {"tab": "P&L", "title": ("Income and expenditure" if nfp else "Profit and loss") + ", September 2026", "rows": o["pnl"]},
        "bs": {"tab": "Balance sheet", "title": "Balance sheet at 30 September 2026", "rows": o["bsr"]},
        "cf": {"tab": "Cash flow", "title": "Cash flow, September 2026", "rows": o["cfr"]},
    }


def checks(org):
    nfp = org == "nfp"
    detail = {
        "trades": ["Every job's revenue, materials and subcontractors add up to the P&L",
                   "Trade debtors equal the invoices still unpaid at month end"],
        "services": ["Every engagement's revenue adds up to the P&L",
                     "Work in progress equals unbilled project time; debtors equal unpaid invoices"],
        "nfp": ["Grant income equals what was spent on each grant",
                "Unspent grants equal instalments received less income recognised"],
    }[org]
    return [
        "Every subtotal and total adds up",
        "Balance sheet balances: assets = liabilities + " + ("accumulated funds" if nfp else "equity"),
        "Cash flow ends at the cash in the bank",
        ("Surplus ties to the movement in accumulated funds" if nfp else "Profit ties to the movement in retained earnings"),
    ] + detail


def export_paths(org):
    return {"xlsx": f"media/exports/{org}-sample-statements.xlsx", "pdf": f"media/exports/{org}-sample-statements.pdf",
            "pptx": f"media/exports/{org}-sample-statements.pptx"}


def dashboard_payload(res):
    orgs = []
    for org in ORDER:
        v = res[org]
        f4 = v["fourth"]
        orgs.append({
            "id": org, "toggle": TOGGLE[org], "name": v["model"]["long_name"], "about": v["model"]["about"],
            "columns": fm.COLUMNS, "unit": "$",
            "statements": statements(org, v),
            "fourth": {"kpis": f4["kpis"], "chart": f4["chart"]},
            "checks": checks(org), "assumptions": v["assumptions"], "exports": export_paths(org), "exports_meta": ek.export_meta(export_paths(org), v["model"]["long_name"], "Monthly report pack", "September 2026"),
        })
    status = [{"month": m, "label": date.fromisoformat(m + "-01").strftime("%b %Y"), "status": ds.month_status(m)[0],
               "note": ds.month_status(m)[1]} for m in STATUS_MONTHS]
    return {"generated": date.today().isoformat(), "as_at": ds.as_at_text(), "status": status, "orgs": orgs}


def write_dashboard_js(res):
    payload = dashboard_payload(res)
    js = ("/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.\n"
          "   Don't edit by hand: change the assumptions in financial_model.py and re-run.\n"
          "   All figures are invented sample data, in whole dollars: September 2026 vs August 2026. */\n"
          "window.FOURTH_SHEET_DASHBOARD = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n")
    (REPO / "data" / "dashboard-data.js").write_text(js)


# ================================================= detail lists (granular)

def detail_table(org, v):
    """The granular list behind the statements: (title, head, rows, money columns)."""
    o = v["out"]
    if org == "trades":
        head = ["Month", "Job", "Type", "Invoiced", "Paid", "Revenue", "Materials", "Subcontractors",
                "Tech hours", "Labour cost (incl. on-costs)", "Job gross margin", "Job gross margin %"]
        rows = [[j["month"], j["description"], j["type"], j["invoice_date"].isoformat(), j["paid_date"].isoformat(),
                 j["revenue"], j["materials"], j["subcontractors"], j["hours"], j["labour_cost"], j["gross_profit"],
                 round(100 * j["gross_profit"] / j["revenue"], 1)] for j in o["jobs"] if j["month"] in fm.PERIODS]
        rows.sort(key=lambda r: (r[0] != "2026-09", r[2], r[1]))
        return "Jobs, September and August 2026", head, rows
    if org == "services":
        head = ["Month", "Engagement", "Type", "Hours", "Revenue", "Billed", "Contractors",
                "Consultant time cost (incl. on-costs)", "Gross margin", "Gross margin %"]
        rows = [[x["month"], x["description"], x["type"], x["hours"], x["revenue"], x["billed"], x["contractors"],
                 x["allocated_cost"], x["contribution"], round(100 * x["contribution"] / x["revenue"], 1)] for x in o["engagements"]]
        rows.sort(key=lambda r: (r[0] != "2026-09", r[1]))
        return "Client engagements, September and August 2026", head, rows
    head = ["Program", "Funder", "Total", "Start", "End", "Received to date", "Spent to date", "Spent Aug", "Spent Sep",
            "Budget to date", "Spend vs budget %", "Still to spend", "Months left"]
    rows = [[g["program"], g["funder"], g["total"], g["start"], g["end"], g["received_to_date"], g["spent_to_date"],
             g["spent_aug"], g["spent_sep"], g["budget_to_date"], g["spend_vs_budget_pct"], g["unspent"], g["months_left"]] for g in o["grants"]]
    return "Grants at 30 September 2026", head, rows


def pdf_detail_rows(org, v):
    """Shorter list for the PDF: September only, call-outs rolled into one line."""
    title, head, rows = detail_table(org, v)
    if org == "nfp":
        return title, head, rows
    sep = [r for r in rows if r[0] == "2026-09"]
    if org == "trades":
        calls = [r for r in sep if r[2] == "Call-out"]
        sep = [r for r in sep if r[2] != "Call-out"]
        tot = lambda i: sum(r[i] for r in calls)
        sep.append(["2026-09", f"{len(calls)} call-outs (each one is in the spreadsheet)", "Call-out", "", "",
                    tot(5), tot(6), tot(7), tot(8), tot(9), tot(10), round(100 * tot(10) / tot(5), 1)])
        keep = [1, 2, 5, 6, 7, 9, 10, 11]
    else:
        keep = [1, 2, 3, 4, 5, 6, 8, 9]
    return title.replace(", September and August", ", September"), [head[i] for i in keep], [[r[i] for i in keep] for r in sep]


# =============================================================== CSV rows

def csv_tables(res):
    st, kp, asm = [], [], []
    for org in ORDER:
        v = res[org]
        for skey, s in statements(org, v).items():
            for i, rw in enumerate(s["rows"], 1):
                if rw["values"] is None:
                    continue
                for period, val in zip(fm.PERIODS, rw["values"]):
                    st.append([org, skey, s["title"], i, rw["label"], rw["level"], period, val])
        for k in v["fourth"]["kpis"]:
            kp.append([org, k["label"], k["value"], k["sub"]])
        for group, items in v["assumptions"]:
            for item, val in items:
                asm.append([org, group, item, val])
    return {
        "model_statements": ("Home-page dashboard: month-end P&L / income and expenditure, balance sheet and cash flow for the three sample organisations, September 2026 and August 2026, whole dollars. Costs and outflows are negative. level = detail/subtotal/total/key.",
                             ["org", "statement_key", "statement", "line_order", "line", "level", "period", "amount_aud"], st),
        "model_fourth_sheet_kpis": ("Home-page dashboard: the fourth-sheet KPI tiles for September 2026, as displayed.", ["org", "kpi", "value", "comparison"], kp),
        "model_assumptions": ("Home-page dashboard: the assumptions each sample organisation's statements are built from.", ["org", "assumption_group", "assumption", "value"], asm),
    }


# =============================================================== Excel

THIN = Side(style="thin", color=LINE)
DOUBLE = Side(style="double", color=INK)
F = ek.XL_FMT

# How each total in a statement is worked out from the lines above it (written as Excel formulas).
# Subtotals with detail lines above them are SUMs; these totals combine other lines.
TOTALS = {
    "Gross profit": [("Total revenue", 1), ("Total cost of sales", 1)],
    "EBITDA": [("Gross profit", 1), ("Total operating expenses", 1)],
    "Profit before tax": [("EBITDA", 1), ("Depreciation", 1), ("Interest", 1)],
    "Net profit after tax": [("Profit before tax", 1), ("Income tax*", 1)],
    "Total expenses": [("Total program spend", 1), ("Total fundraising costs", 1), ("Total administration", 1), ("Depreciation", 1)],
    "Surplus for the month": [("Total income", 1), ("Total expenses", 1)],
    "Total assets": [("Total current assets", 1), ("@prev", 1)],
    "Total liabilities": [("Total current liabilities", 1), ("Equipment finance", 1)],
    "Net assets": [("Total assets", 1), ("Total liabilities", -1)],
    "Net change in cash": [("Net cash from*", 1)],
    "Cash at end of month": [("Cash at start of month", 1), ("Net change in cash", 1)],
}


def statement_spec(rows):
    """For each row: None (heading), 'input', ('sum', [i…]) or ('lin', [(i, sign)…])."""
    spec, pending = [], []
    def find(lab, i):
        if lab == "@prev":
            return [i - 1]
        if lab.endswith("*"):
            return [j for j in range(i) if rows[j]["label"].startswith(lab[:-1]) and rows[j]["values"] is not None]
        return [max(j for j in range(i) if rows[j]["label"] == lab)]
    for i, rw in enumerate(rows):
        lv = rw["level"]
        if lv == "heading":
            spec.append(None); pending = []
        elif lv == "detail":
            spec.append("input"); pending.append(i)
        elif pending:
            spec.append(("sum", pending)); pending = []
        elif lv in ("total", "key") and rw["label"] in TOTALS:
            spec.append(("lin", [(j, sg) for lab, sg in TOTALS[rw["label"]] for j in find(lab, i)]))
        else:
            spec.append("input")
    # prove the formulas give the model's numbers
    for i, (rw, sp) in enumerate(zip(rows, spec)):
        if isinstance(sp, tuple):
            for c in range(2):
                got = sum(rows[j]["values"][c] for j in sp[1]) if sp[0] == "sum" else sum(sg * rows[j]["values"][c] for j, sg in sp[1])
                if got != rw["values"][c]:
                    raise SystemExit(f"Excel formula for '{rw['label']}' gives {got}, model says {rw['values'][c]}")
    return spec


def head_cells(ws, r, heads, first_left=True):
    for c, h in enumerate(heads, 1):
        cell = ws.cell(r, c, h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=GREEN)
        cell.alignment = Alignment(horizontal="left" if (c == 1 and first_left) else "right", vertical="center", wrap_text=True)


def title_block(ws, title, sub, status):
    ws["A1"] = title
    ws["A1"].font = Font(bold=True, size=14, color=INK)
    ws["A2"] = sub
    ws["A2"].font = Font(italic=True, size=9, color=MUTED)
    ws["A3"] = status
    ws["A3"].font = Font(italic=True, size=9, color=MUTED)


def xl_statement(ws, title, sub, status, rows, colour_change=True):
    """Detail lines are data; every subtotal, total and the Change column are formulas."""
    title_block(ws, title, sub, status)
    hr = 4
    head_cells(ws, hr, ["$"] + fm.COLUMNS + ["Change"])
    spec = statement_spec(rows)
    rownum, starts = {}, []
    r = hr
    for i, (rw, sp) in enumerate(zip(rows, spec)):
        r += 1
        rownum[i] = r
        a = ws.cell(r, 1, rw["label"])
        if sp is None:
            a.font = Font(bold=True, color=GREEN)
            starts.append(r)
            continue
        for c, col in ((2, "B"), (3, "C")):
            if sp == "input":
                val = rw["values"][c - 2]
            elif sp[0] == "sum":
                rs = [rownum[j] for j in sp[1]]
                val = f"=SUM({col}{rs[0]}:{col}{rs[-1]})" if rs == list(range(rs[0], rs[-1] + 1)) else "=" + "+".join(f"{col}{x}" for x in rs)
            else:
                val = "=" + "".join(f"{'+' if sg > 0 else '-'}{col}{rownum[j]}" for j, sg in sp[1]).lstrip("+")
            cell = ws.cell(r, c, val)
            cell.number_format = F["money"]
        ch = ws.cell(r, 4, f"=B{r}-C{r}")
        ch.number_format = F["chg_money"]
        ch.font = Font(italic=True, color=MUTED)
        if colour_change:              # income +, costs −: a rise is always good for the result
            ek.xl_change(ws, f"D{r}", "higher")
        if rw["level"] == "detail":
            a.alignment = Alignment(indent=1)
            a.font = Font(color=MUTED)
        else:
            for c in range(1, 5):
                ws.cell(r, c).font = Font(bold=True, italic=(c == 4), color=GREEN if rw["level"] == "key" else INK)
                ws.cell(r, c).border = Border(top=THIN, bottom=DOUBLE if rw["level"] == "key" else None)
                if rw["level"] == "key":
                    ws.cell(r, c).fill = PatternFill("solid", fgColor=SOFT)
    ws.column_dimensions["A"].width = 52
    for col in "BCD":
        ws.column_dimensions[col].width = 16
    ws.freeze_panes = "B5"
    return starts, r


def xl_support(ws, r, sp):
    """One workings panel: inputs as values, calculated rows as formulas. Returns (next row, {row index: excel row}, block start)."""
    start = r
    ws.cell(r, 1, sp["title"]).font = Font(bold=True, color=GREEN, size=12)
    ws.cell(r + 1, 1, sp["formula"]).font = Font(italic=True, color=MUTED)
    r += 2
    cols = sp["xl"]["cols"]
    head_cells(ws, r, [""] + cols)
    rowmap = {}
    letters = [get_column_letter(c) for c in range(2, 2 + len(cols))]
    xr = sp["xl"]["rows"]
    for i, row_ in enumerate(xr):
        r += 1
        rowmap[i] = r
        ws.cell(r, 1, row_["label"])
        for k, L in enumerate(letters):
            if row_["calc"]:
                import re
                val = re.sub(r"r(\d+)", lambda m: f"{L}{rowmap[int(m.group(1))]}", row_["calc"])
                val = f'=IFERROR({val},"–")' if "/" in row_["calc"] and row_["values"][k] is None else "=" + val
            else:
                val = row_["values"][k]
            cell = ws.cell(r, 2 + k, val)
            cell.number_format = F[row_["kind"]]
            cell.alignment = Alignment(horizontal="right")
        if i == len(xr) - 1:
            for c in range(1, 2 + len(cols)):
                ws.cell(r, c).font = Font(bold=True)
                ws.cell(r, c).border = Border(top=THIN)
    if sp.get("note"):
        r += 1
        ws.cell(r, 1, sp["note"]).font = Font(italic=True, size=9, color=MUTED)
    if sp.get("series"):
        se = sp["series"]
        r += 2
        ws.cell(r, 1, se["title"]).font = Font(bold=True, color=INK)
        r += 1
        head_cells(ws, r, ["Month", "Spend", "Budget", "Spend against budget"])
        top = r + 1
        for lab, val, bud in zip(se["labels"], se["values"], se["budget"]):
            r += 1
            ws.cell(r, 1, lab)
            ws.cell(r, 2, val).number_format = F["money"]
            ws.cell(r, 3, bud).number_format = F["money"]
            ws.cell(r, 4, f"=IF(C{r}=0,\"\",B{r}/C{r})").number_format = F["pct"]
        r += 1
        ws.cell(r, 1, "Total").font = Font(bold=True)
        for c, L in ((2, "B"), (3, "C")):
            cell = ws.cell(r, c, f"=SUM({L}{top}:{L}{r - 1})")
            cell.number_format = F["money"]
            cell.font = Font(bold=True)
        cell = ws.cell(r, 4, f"=IF(C{r}=0,\"\",B{r}/C{r})")
        cell.number_format = F["pct"]
        cell.font = Font(bold=True)
    return r + 3, rowmap, start


def xl_list(ws, org, v, status, sub):
    """The job / engagement / grant list: data columns are values, worked-out columns are formulas."""
    o, m = v["out"], v["model"]
    if org == "trades":
        title = "Jobs, September and August 2026"
        title_block(ws, title, sub, status)
        ws["A4"], ws["B4"] = "Technician cost rate ($ per hour, wages and all on-costs)", m["tech_cost_rate"]
        ws["B4"].number_format = F["money"]
        heads = ["Month", "Job", "Type", "Invoiced", "Paid", "Revenue", "Technician time charged (call-outs)", "Materials charged (call-outs)",
                 "Materials", "Subcontractors", "Tech hours", "Labour cost (incl. on-costs)", "Job gross margin", "Job gross margin %"]
        kinds = ["text", "text", "text", "date", "date", "money", "money", "money", "money", "money", "hours", "money", "money", "pct"]
        jobs = sorted([j for j in o["jobs"] if j["month"] in fm.PERIODS], key=lambda j: (j["month"] != "2026-09", j["type"], j["description"]))
        data = [[j["month"], j["description"], j["type"], j["invoice_date"], j["paid_date"], j["revenue"], j["labour_revenue"], j["materials_revenue"],
                 j["materials"], j["subcontractors"], j["hours"], "=K{r}*$B$4", "=F{r}-I{r}-J{r}-L{r}", "=IF(F{r}=0,\"\",M{r}/F{r})"] for j in jobs]
        group = [j["month"] for j in jobs]
    elif org == "services":
        title = "Client engagements, September and August 2026"
        title_block(ws, title, sub, status)
        ws["A4"], ws["B4"] = "Consultant cost rate ($ per hour, wages and all on-costs)", m["cost_rate"]
        ws["B4"].number_format = F["money"]
        heads = ["Month", "Engagement", "Type", "Hours", "Revenue", "Billed", "Contractors", "Consultant time cost (incl. on-costs)", "Gross margin", "Gross margin %"]
        kinds = ["text", "text", "text", "hours", "money", "money", "money", "money", "money", "pct"]
        eng = sorted(o["engagements"], key=lambda x: (x["month"] != "2026-09", x["description"]))
        data = [[x["month"], x["description"], x["type"], x["hours"], x["revenue"], x["billed"], x["contractors"],
                 "=D{r}*$B$4", "=E{r}-G{r}-H{r}", "=IF(E{r}=0,\"\",I{r}/E{r})"] for x in eng]
        group = [x["month"] for x in eng]
    else:
        title = "Grants at 30 September 2026"
        title_block(ws, title, sub, status)
        ws["A4"] = "Budget to date = the grant spread evenly over its months, to 30 September 2026."
        ws["A4"].font = Font(italic=True, size=9, color=MUTED)
        heads = ["Program", "Funder", "Grant total", "Start", "End", "Received to date", "Spent to date", "Spent Aug",
                 "Spent Sep", "Budget to date", "Spent against budget", "Still to spend", "Months left"]
        kinds = ["text", "text", "money", "date", "date", "money", "money", "money", "money", "money", "pct", "money", "int"]
        G = sorted(o["grants"], key=lambda g: -g["total"])
        data = [[g["program"], g["funder"], g["total"], date.fromisoformat(g["start"]), date.fromisoformat(g["end"]), g["received_to_date"],
                 g["spent_to_date"], g["spent_aug"], g["spent_sep"], g["budget_to_date"], "=IF(J{r}=0,\"\",G{r}/J{r})", "=C{r}-G{r}", g["months_left"]] for g in G]
        group = ["all"] * len(G)
    hr = 6
    head_cells(ws, hr, heads)
    starts = []
    for i, row_ in enumerate(data):
        r = hr + 1 + i
        if i and group[i] != group[i - 1]:
            starts.append(r)          # a new month starts on a new page block
        for c, (val, kind) in enumerate(zip(row_, kinds), 1):
            if isinstance(val, str) and val.startswith("="):
                val = val.format(r=r)
            cell = ws.cell(r, c, val)
            cell.number_format = F[kind]
            if kind not in ("text",):
                cell.alignment = Alignment(horizontal="right")
    last = hr + len(data)
    # totals row: formulas over the list (not for the grants' months-left or percentages)
    tr = last + 1
    ws.cell(tr, 1, "Total").font = Font(bold=True)
    for c, kind in enumerate(kinds, 1):
        L = get_column_letter(c)
        if kind in ("money", "hours") and c > 2:
            cell = ws.cell(tr, c, f"=SUM({L}{hr + 1}:{L}{last})")
            cell.number_format = F[kind]
            cell.font = Font(bold=True)
            cell.border = Border(top=THIN, bottom=DOUBLE)
    for c, (h, kind) in enumerate(zip(heads, kinds), 1):
        ws.column_dimensions[get_column_letter(c)].width = 34 if h in ("Job", "Engagement", "Program", "Funder") else 13
    ws.column_dimensions["A"].width = max(ws.column_dimensions["A"].width, 12)
    ws.freeze_panes = f"C{hr + 1}"
    ek.xl_table(ws, {"trades": "Jobs", "services": "Engagements", "nfp": "Grants"}[org], hr, last, len(heads))
    # the chart beside it: September's installations / September's engagements / every grant, as on the website
    if org == "trades":
        rows_ = [hr + 1 + i for i, j in enumerate(jobs) if j["month"] == "2026-09" and j["type"] == "Installation"]
        title_, vcol, fmt_ = "Job gross margin %, September installations", 14, "0.0%"
    elif org == "services":
        rows_ = [hr + 1 + i for i, x in enumerate(eng) if x["month"] == "2026-09"]
        title_, vcol, fmt_ = "Gross margin %, September engagements", 10, "0.0%"
    else:
        rows_ = list(range(hr + 1, last + 1))
        title_, vcol, fmt_ = "Spent against budget to date", 11, "0.0%"
    if rows_ and rows_ == list(range(rows_[0], rows_[-1] + 1)):
        ek.xl_bar_chart(ws, f"{get_column_letter(len(heads) + 2)}{hr}", title_, (ws, 2 if org != "nfp" else 1, rows_[0], 2 if org != "nfp" else 1, rows_[-1]),
                        (ws, vcol, rows_[0], vcol, rows_[-1]), len(rows_), fmt_, title_)
    return hr, starts, tr


def write_xlsx(org, v):
    wb = ek.xl_default_font(Workbook())
    name = v["model"]["long_name"]
    filename = f"{org}-sample-statements.xlsx"
    retrieved = ds.as_at_text()
    sub = f"{name} · SAMPLE DATA (invented) · The Fourth Sheet · {ek.MADE_WITH['xlsx']}"
    status = "Data status: " + " · ".join(f"{date.fromisoformat(m + '-01').strftime('%b %Y')} {ds.month_status(m)[0].lower()}" for m in STATUS_MONTHS) + f" (data retrieved {retrieved}) · {ek.generated_text()}"
    f4 = v["fourth"]
    pages = {}

    # --- Workings first in memory (other sheets point at it), shown after the fourth sheet
    ws4 = wb.active
    ws4.title = "The fourth sheet"
    wk = wb.create_sheet("Workings")
    title_block(wk, "How each number is worked out", sub, status)
    r, starts, kpi_ref, det_ref = 5, [], [], []
    for k in f4["kpis"]:
        r, rowmap, st = xl_support(wk, r, k["support"])
        starts.append(st)
        kpi_ref.append((rowmap[len(k["support"]["xl"]["rows"]) - 1], k["support"]["xl"]["rows"][-1]["kind"], len(k["support"]["xl"]["cols"])))
    for d in f4["chart"].get("details", []):
        r, rowmap, st = xl_support(wk, r, d)
        starts.append(st)
        det_ref.append(rowmap)
    wk.column_dimensions["A"].width = 58
    for col in "BCD":
        wk.column_dimensions[col].width = 20
    pages["Workings"] = (None, starts, r)

    # --- The fourth sheet: every number is a formula pointing at its workings
    title_block(ws4, "The fourth sheet: September 2026 against August 2026", sub, status)
    head_cells(ws4, 5, ["Headline number", "Sep 2026", "Aug 2026", "Change"])
    used = set()
    for i, (k, (wr, kind, ncols)) in enumerate(zip(f4["kpis"], kpi_ref)):
        r = 6 + i
        ws4.cell(r, 1, k["label"].replace(", September", ""))
        ws4.cell(r, 2, f"=Workings!B{wr}").number_format = F[kind]
        ek.xl_name(wb, k["label"].replace(", September", ""), "The fourth sheet", f"B{r}", used)
        if ncols > 1:
            ws4.cell(r, 3, f"=Workings!C{wr}").number_format = F[kind]
            if kind == "pct":       # a change in a rate is in percentage points
                ws4.cell(r, 4, f"=(B{r}-C{r})*100").number_format = F["pts"]
            else:
                ws4.cell(r, 4, f"=B{r}-C{r}").number_format = F.get("chg_" + kind, F["chg_money"])
            ek.xl_change(ws4, f"D{r}", k.get("good_when", "higher"))
    r = 6 + len(f4["kpis"]) + 2
    ch = f4["chart"]
    ws4.cell(r, 1, ch["title"]).font = Font(bold=True, color=INK)
    ws4.cell(r + 1, 1, ch.get("subtitle", "")).font = Font(italic=True, size=9, color=MUTED)
    r += 2
    views = ch.get("views") or [{"label": "Value", "format": ch["format"]}]
    head_cells(ws4, r, ["", *[vw["label"] for vw in views]])
    chart_hr = r
    # which workings row holds the % and the $ for each bar
    for i, (lab, rowmap) in enumerate(zip(ch["labels"], det_ref)):
        r += 1
        ws4.cell(r, 1, lab)
        n = len(rowmap)
        pct_row = rowmap[n - 1]                                  # the last row is the % (margin / spent against budget)
        dollar_row = rowmap[n - 2]                                # profit / contribution; grants: over (under) budget in $
        for c, vw in enumerate(views, 2):
            pc = vw["format"].startswith("pct")
            ws4.cell(r, c, f"=Workings!B{pct_row if pc else dollar_row}").number_format = F["pct" if pc else "money"]
    v0 = views[0]
    pc0 = v0["format"].startswith("pct")
    ek.xl_bar_chart(ws4, f"F{chart_hr - 1}", ch["title"], (ws4, 1, chart_hr + 1, 1, r), (ws4, 2, chart_hr + 1, 2, r), len(ch["labels"]),
                    "0.0%" if pc0 else "#,##0;(#,##0)", v0["label"], ch.get("target"), f"{ch['target']:.1f}%" if ch.get("target") is not None else None,
                    below=None if ch.get("plain") or ch.get("target") is None else [x < ch["target"] for x in v0["values"]],
                    bad=[x >= 1 for x in v0["values"]] if ch.get("variance") else [x < 0 for x in v0["values"]],
                    warn=[0.05 <= abs(x) < 1 for x in v0["values"]] if ch.get("variance") else None,
                    values=[x / 100 if pc0 else x for x in v0["values"]],
                    lines=[(f"Target {ch['target']:.1f}%", ch["target"] / 100 if pc0 else ch["target"], "25342A", "dash")] if ch.get("target") is not None else None)
    if ch.get("target") is not None:
        r += 1
        ws4.cell(r, 1, "Target").font = Font(italic=True, color=MUTED)
        ws4.cell(r, 2, ch["target"] / 100).number_format = F["pct"]
    ws4.column_dimensions["A"].width = 52
    for col in "BCD":
        ws4.column_dimensions[col].width = 18
    pages["The fourth sheet"] = (5, [], r)

    # --- statements: data lines and formula totals
    for key, st in statements(org, v).items():
        tab = {"pnl": "Income and expenditure" if org == "nfp" else "Profit and loss", "bs": "Balance sheet", "cf": "Cash flow"}[key]
        w = wb.create_sheet(tab)
        starts, last = xl_statement(w, st["title"], sub, status, st["rows"], colour_change=key != "bs")
        pages[tab] = (4, starts, last)

    # --- the granular list
    tab = {"trades": "Jobs", "services": "Engagements", "nfp": "Grants"}[org]
    w = wb.create_sheet(tab)
    hr, starts, last = xl_list(w, org, v, status, sub)
    pages[tab] = (hr, starts, last)

    # --- assumptions (text)
    w = wb.create_sheet("Assumptions")
    title_block(w, "Assumptions", sub, status)
    r, starts = 5, []
    for group, items in v["assumptions"]:
        starts.append(r)
        w.cell(r, 1, group).font = Font(bold=True, color=GREEN)
        r += 1
        for item, val in items:
            w.cell(r, 1, item).alignment = Alignment(indent=1, vertical="top")
            w.cell(r, 2, val).alignment = Alignment(wrap_text=True, vertical="top")
            r += 1
        r += 1
    starts.append(r)
    w.cell(r, 1, "Checks (all passed)").font = Font(bold=True, color=GREEN)
    for c in checks(org):
        r += 1
        w.cell(r, 1, "✓ " + c)
    w.column_dimensions["A"].width = 44
    w.column_dimensions["B"].width = 90
    pages["Assumptions"] = (None, starts, r)

    # order: fourth sheet, statements, list, workings, assumptions
    wb.move_sheet("Workings", offset=len(wb.sheetnames) - 2 - wb.sheetnames.index("Workings"))
    review = []
    for ws_ in wb.worksheets:
        if ws_.title not in pages:
            continue                  # the hidden 'Chart lines' sheet (points for target lines)
        hr, starts, last = pages[ws_.title]
        ek.xl_print(ws_, name, filename, retrieved, landscape=True, header_row=hr)
        review.append(ek.xl_review(ws_, ek.xl_breaks(ws_, starts, last, hr), hr))
    # record the print check in the file itself
    w = wb["Assumptions"]
    r = w.max_row + 2
    w.cell(r, 1, "Print check (done before this file was saved)").font = Font(bold=True, color=GREEN)
    for line in review:
        r += 1
        w.cell(r, 1, "✓ " + line)
    print(f"  {filename}: " + " | ".join(review))
    ek.xl_finish(wb)
    EXPORTS.mkdir(parents=True, exist_ok=True)
    ek.save_if_changed(wb.save, EXPORTS / filename)


# =============================================================== PDF

def html_report(org, v):
    esc = lambda s: str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    fmt = lambda n: f"({abs(n):,})" if n < 0 else (f"{n:,}" if n else "-")

    def stmt(s):
        stl = " · ".join(f"{date.fromisoformat(m + '-01').strftime('%b %Y')}: {ds.month_status(m)[0].lower()}" for m in fm.PERIODS)
        out = [f"<h2>{esc(s['title'])}</h2><p class=stline>{esc(stl)}</p><table><tr><th>$</th>" + "".join(f"<th class=n>{c}</th>" for c in fm.COLUMNS + ["Change"]) + "</tr>"]
        for rw in s["rows"]:
            if rw["values"] is None:
                out.append(f"<tr class=heading><td colspan=4>{esc(rw['label'])}</td></tr>")
            else:
                out.append(f"<tr class={rw['level']}><td>{esc(rw['label'])}</td>" + "".join(f"<td class=n>{ek.neg_html(fmt(x))}</td>" for x in rw["values"] + [rw["values"][0] - rw["values"][1]]) + "</tr>")
        return "".join(out) + "</table>"

    f4 = v["fourth"]
    kpis = "".join(f"<div class=kpi><span>{esc(k['label'])}</span><b>{ek.neg_html(k['value'])}</b><em>{esc(k['sub'])}</em></div>" for k in f4["kpis"])
    dtitle, dhead, drows = pdf_detail_rows(org, v)
    cellv = lambda c: fmt(c) if isinstance(c, int) else (f"{c:,.1f}" if isinstance(c, float) else c)
    num = lambda c: isinstance(c, (int, float))
    tbl = "<table class=detail-list><tr>" + "".join(f"<th{' class=n' if num(drows[0][i]) else ''}>{esc(h)}</th>" for i, h in enumerate(dhead)) + "</tr>" + \
          "".join("<tr>" + "".join(f"<td{' class=n' if num(c) else (' class=w' if len(str(c)) > 14 else '')}>{esc(cellv(c))}</td>" for c in rw) + "</tr>" for rw in drows) + "</table>"
    ch = f4["chart"]
    views = ch.get("views") or [{"label": "", "values": ch["values"], "format": ch["format"], "target": ch.get("target")}]
    chart_svg = "".join((f"<p class=viewlabel>{esc(vw['label'])}</p>" if len(views) > 1 else "")
                        + ek.hbar_svg(ek.bar_spec(ch, vw, views))
                        for vw in views)
    def wk(sp):
        two = all(not r_[2] for r_ in sp["rows"])
        head = "" if two else "<tr>" + "".join(f"<th{' class=n' if i else ''}>{esc(h)}</th>" for i, h in enumerate(sp["head"])) + "</tr>"
        body = "".join("<tr>" + "".join(f"<td{' class=n' if i else ''}>{ek.neg_html(c) if i else esc(c)}</td>" for i, c in enumerate(r_[:2] if two else r_)) + "</tr>" for r_ in sp["rows"])
        return f"<h3>{esc(sp['title'])}</h3><p class=formula>{esc(sp['formula'])}</p><table class=wk>{head}{body}</table>" + (f"<p class=note>{esc(sp['note'])}</p>" if sp.get("note") else "")
    workings = "".join(wk(k["support"]) for k in f4["kpis"])
    assum = "".join(f"<h3>{esc(g)}</h3><table class=assum>" + "".join(f"<tr><td>{esc(a)}</td><td>{esc(b)}</td></tr>" for a, b in items) + "</table>" for g, items in v["assumptions"])
    st = statements(org, v)
    return f"""<!doctype html><html><head><meta charset=utf-8>
<link rel=stylesheet href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap">
<style>
@page {{ size: A4; margin: 16mm 14mm; }}
body {{ font-family: Roboto, Arial, sans-serif; color: #25342a; font-size: 10.5pt; }}
header {{ display: flex; align-items: center; gap: 10px; border-bottom: 3px solid #2f7a5d; padding-bottom: 8px; margin-bottom: 12px; }}
.mark {{ min-width: 30px; height: 30px; padding: 0 4px; border-radius: 7px; background: #2f7a5d; color: #fff; font-weight: 800; display: flex; align-items: center; justify-content: center; font-size: 15px; }} .mark sup, header b sup {{ font-size: 0.55em; }}
header b {{ font-size: 13pt; }} header small {{ margin-left: auto; color: #5f6f63; }}
h1 {{ font-size: 17pt; margin: 6px 0 2px; }} .about {{ color: #5f6f63; margin: 0 0 10px; }}
.sample {{ display: inline-block; background: #f6f1e7; border: 1px solid #b28a92; color: #6b5532; border-radius: 4px; padding: 2px 8px; font-size: 8.5pt; font-weight: 700; }}
h2 {{ font-size: 12.5pt; color: #2f7a5d; margin: 16px 0 6px; }} h3 {{ font-size: 10.5pt; margin: 10px 0 4px; color: #2f7a5d; }}
table {{ width: 100%; border-collapse: collapse; }} table.wk, table.assum {{ page-break-inside: avoid; }} tr {{ page-break-inside: avoid; }} thead {{ display: table-header-group; }} th {{ text-align: left; background: #2f7a5d; color: #fff; padding: 4px 6px; font-size: 9pt; }}
td {{ padding: 3px 6px; border-bottom: 1px solid #eef2ee; }} .n {{ text-align: right; font-variant-numeric: tabular-nums; }}
tr.heading td {{ font-weight: 700; color: #2f7a5d; padding-top: 7px; border: 0; }} tr.detail td:first-child {{ padding-left: 16px; color: #5f6f63; }}
tr.subtotal td, tr.total td {{ font-weight: 700; border-top: 1px solid #9db8a6; }} tr.total td {{ border-bottom: 1px solid #25342a; }}
tr.key td {{ font-weight: 800; background: #eaf6ee; border-top: 1px solid #25342a; border-bottom: 3px double #25342a; color: #1f5a43; }}
.kpis {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }} .kpi {{ border: 1px solid #dce8dc; border-radius: 6px; padding: 7px; }}
.kpi span, .kpi em {{ display: block; font-size: 8.5pt; color: #5f6f63; font-style: normal; }} .kpi b {{ display: block; font-size: 15pt; color: #2f7a5d; }}
.detail-list {{ font-size: 8.5pt; }} .detail-list td {{ white-space: nowrap; }} .detail-list td.w {{ white-space: normal; min-width: 110px; }}
@page wide {{ size: A4 landscape; margin: 14mm; }} .wide {{ page: wide; }}
.formula {{ margin: 0 0 4px; font-style: italic; color: #5f6f63; }} .wk {{ margin-bottom: 10px; }} .wk tr:last-child td {{ font-weight: 700; border-top: 1px solid #9db8a6; }} .note {{ font-size: 8.5pt; color: #5f6f63; margin: 2px 0 8px; }}
.viewlabel {{ margin: 6px 0 0; font-size: 8.5pt; font-weight: 700; color: #5f6f63; }}
.neg {{ color: #B42318; }} .stline {{ margin: -4px 0 6px; font-size: 8pt; color: #5f6f63; }} .chart {{ margin: 4px 0 10px; page-break-inside: avoid; }}
""" + ek.STATUS_CSS + f"""
.two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }} .page {{ page-break-before: always; }}
.assum td:first-child {{ width: 40%; color: #5f6f63; }} .checks li {{ margin: 2px 0; }}
footer {{ margin-top: 14px; font-size: 8pt; color: #5f6f63; }}
</style></head><body>
<header><div class=mark>4<sup>th</sup></div><b>The Fourth Sheet</b><small>Your accountant gives you three sheets. I give you the fourth.</small></header>
<span class=sample>SAMPLE DATA · invented figures for demonstration</span>
<h1>{esc(v['model']['long_name'])}</h1><p class=about>{esc(v['model']['about'])}</p>
{ek.status_box_html([(date.fromisoformat(m + "-01").strftime("%B %Y"), *ds.month_status(m)) for m in STATUS_MONTHS])}
<h2>The fourth sheet: September 2026 vs August 2026</h2><div class=kpis>{kpis}</div>
<h3>{esc(ch['title'])}</h3><p class=stline>{esc(ch.get('subtitle', ''))}</p><div class=chart>{chart_svg}</div>
<div class=flow><h2>How each number is worked out</h2>{workings}</div>
<div class="page wide"><h2>{esc(dtitle)}</h2>{tbl}</div>
<div class=page>{stmt(st['pnl'])}</div>
<div class=page>{stmt(st['bs'])}</div>
<div class=page>{stmt(st['cf'])}</div>
<div class=page><h2>Assumptions</h2>{assum}<h3>Checks (all passed)</h3><ul class=checks>{''.join(f'<li>✓ {esc(c)}</li>' for c in checks(org))}</ul>
<footer>{ek.generated_text()} by a driver-based model: every figure is calculated from the assumptions above. Sample data only, not financial advice. {ek.MADE_WITH['pdf']}.</footer></div>
</body></html>"""


def write_pptx(org, v):
    """PowerPoint version of the statements PDF."""
    import pptkit
    f4 = v["fourth"]
    name = v["model"]["long_name"]
    d = pptkit.Deck(name, "Monthly report pack, September 2026", f"{org}-sample-statements.pptx", ds.as_at_text())
    d.title_slide(v["model"]["about"], [f"{date.fromisoformat(m + '-01').strftime('%B %Y')}: {ds.month_status(m)[0]}. {ds.month_status(m)[1]}" for m in STATUS_MONTHS])
    d.kpi_slide("The fourth sheet: September 2026 vs August 2026", [(k["label"], k["value"], k["sub"], k.get("cls", "")) for k in f4["kpis"]])
    ch = f4["chart"]
    views = ch.get("views") or [{"label": "", "values": ch["values"], "format": ch["format"], "target": ch.get("target")}]
    for vw in views:
        tgt = vw.get("target")
        if ch.get("variance"):     # over budget red, under green, within 1% amber (judged on % of budget)
            pcts = views[0]["values"]
            bad = [p_ >= 1 for p_ in pcts]
            warn = [0.05 <= abs(p_) < 1 for p_ in pcts]
            below = None
        else:
            below = None if ch.get("plain") else [(tgt is not None and x < tgt) or (vw.get("below_marks") and vw.get("marks") and x < vw["marks"][i]) for i, x in enumerate(vw["values"])]
            bad, warn = [x < 0 for x in vw["values"]], None
        d.bar_slide(ch["title"], ch["labels"], vw["values"], vw["format"],
                    (f"{tgt:.1f}%" if tgt is not None and str(vw["format"]).startswith("pct") else None), below,
                    " · ".join(x for x in (vw["label"] if len(views) > 1 else None, ch.get("subtitle")) if x), order_by=views[0]["values"], bad=bad, warn=warn,
                    series_name=vw["label"] or ch["title"])
    for k in f4["kpis"]:
        sp = k["support"]
        d.table_slides(f"How it's worked out: {sp['title']}", sp["head"] if any(r_[2] for r_ in sp["rows"]) else sp["head"][:2],
                       [r_ if any(x[2] for x in sp["rows"]) else r_[:2] for r_ in sp["rows"]], sub=sp["formula"])
    fmt = lambda n: f"({abs(n):,})" if n < 0 else (f"{n:,}" if n else "-")
    for key, st in statements(org, v).items():
        rows = [[rw["label"], *[fmt(x) for x in rw["values"]], fmt(rw["values"][0] - rw["values"][1])] for rw in st["rows"] if rw["values"] is not None]
        d.table_slides(st["title"], ["$"] + fm.COLUMNS + ["Change"], rows)
    dtitle, dhead, drows = pdf_detail_rows(org, v)
    cellv = lambda c: fmt(c) if isinstance(c, int) else (f"{c:,.1f}" if isinstance(c, float) else c)
    d.table_slides(dtitle, dhead, [[cellv(c) for c in r_] for r_ in drows])
    for g_, items in v["assumptions"]:            # one slide per group: label / value, no empty header row
        d.table_slides(f"Assumptions: {g_}", None, [[a_, b_] for a_, b_ in items])
    ek.save_if_changed(d.save, EXPORTS / f"{org}-sample-statements.pptx")


def write_pdfs(res):
    from playwright.sync_api import sync_playwright
    EXPORTS.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(channel="chrome")
        except Exception:
            browser = p.chromium.launch()
        page = browser.new_page()
        for org in ORDER:
            page.set_content(html_report(org, res[org]), wait_until="networkidle")
            page.evaluate("document.fonts.ready")
            ek.pdf_if_changed(page, EXPORTS / f"{org}-sample-statements.pdf",
                     **ek.pdf_options(res[org]["model"]["long_name"], "Monthly report pack, September 2026 · Sample data",
                                      f"{org}-sample-statements.pdf", ds.as_at_text()))
        browser.close()


def publish():
    res = fm.build()  # runs every check; stops here if anything doesn't add up
    publish.res = res
    for org in ORDER:
        write_xlsx(org, res[org])
        write_pptx(org, res[org])
    write_pdfs(res)
    write_dashboard_js(res)          # after the files, so the Export menu can say how many pages and slides they have
    return csv_tables(res)
