#!/usr/bin/env python3
"""
publish_dashboard.py — turns the checked financial model (financial_model.py)
into everything the website and your database use:

  dashboard-data.js                       data for the home-page dashboard
  media/exports/<org>-sample-statements.xlsx   formatted Excel workbook
  media/exports/<org>-sample-statements.pdf    A4 PDF report
  (CSV rows for the OneDrive data folder are returned to sample_data.py)

Run via:  python3 tools/sample_data.py   (it calls this)
Needs:    pip install openpyxl playwright   (PDFs use your installed Chrome)
"""

import json
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

import financial_model as fm

REPO = Path(__file__).resolve().parent.parent
EXPORTS = REPO / "media" / "exports"
ORDER = ["trades", "services", "nfp"]
TOGGLE = {"trades": "SME · trades", "services": "SME · services", "nfp": "Not-for-profit"}
GREEN, DARK, INK, MUTED, SOFT, LINE = "2F7A5D", "1F5A43", "25342A", "5F6F63", "EAF6EE", "DCE8DC"


def statements(org, v):
    nfp = org == "nfp"
    o = v["out"]
    return {
        "pnl": {"tab": "P&L", "title": ("Income and expenditure" if nfp else "Profit and loss") + ", September 2026", "rows": o["pnl"]},
        "bs": {"tab": "Balance sheet", "title": "Balance sheet at 30 September 2026", "rows": o["bsr"]},
        "cf": {"tab": "Cash flow", "title": "Cash flow, September 2026", "rows": o["cfr"]},
    }


def checks(org):
    nfp = org == "nfp"
    detail = {
        "trades": ["Every job's revenue, materials and subcontractors add up to the P&L",
                   "Trade debtors equal the invoices still unpaid at month end"],
        "services": ["Every engagement's revenue adds up to the P&L",
                     "Work in progress equals unbilled project time; debtors equal unpaid invoices"],
        "nfp": ["Grant income equals what was spent on each grant",
                "Unspent grants equal instalments received less income recognised"],
    }[org]
    return [
        "Every subtotal and total adds up",
        "Balance sheet balances: assets = liabilities + " + ("accumulated funds" if nfp else "equity"),
        "Cash flow ends at the cash in the bank",
        ("Surplus ties to the movement in accumulated funds" if nfp else "Profit ties to the movement in retained earnings"),
    ] + detail


def export_paths(org):
    return {"xlsx": f"media/exports/{org}-sample-statements.xlsx", "pdf": f"media/exports/{org}-sample-statements.pdf"}


def dashboard_payload(res):
    orgs = []
    for org in ORDER:
        v = res[org]
        f4 = v["fourth"]
        orgs.append({
            "id": org, "toggle": TOGGLE[org], "name": v["model"]["long_name"], "about": v["model"]["about"],
            "columns": fm.COLUMNS, "unit": "$",
            "statements": statements(org, v),
            "fourth": {"kpis": f4["kpis"], "chart": f4["chart"]},
            "checks": checks(org), "assumptions": v["assumptions"], "exports": export_paths(org),
        })
    return {"generated": date.today().isoformat(), "orgs": orgs}


def write_dashboard_js(res):
    payload = dashboard_payload(res)
    js = ("/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.\n"
          "   Don't edit by hand: change the assumptions in financial_model.py and re-run.\n"
          "   All figures are invented sample data, in whole dollars: September 2026 vs August 2026. */\n"
          "window.FOURTH_SHEET_DASHBOARD = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n")
    (REPO / "dashboard-data.js").write_text(js)


# ================================================= detail lists (granular)

def detail_table(org, v):
    """The granular list behind the statements: (title, head, rows, money columns)."""
    o = v["out"]
    if org == "trades":
        head = ["Month", "Job", "Type", "Description", "Invoiced", "Paid", "Revenue", "Materials", "Subcontractors",
                "Tech hours", "Labour cost", "Gross profit", "Margin %"]
        rows = [[j["month"], j["job"], j["type"], j["description"], j["invoice_date"].isoformat(), j["paid_date"].isoformat(),
                 j["revenue"], j["materials"], j["subcontractors"], j["hours"], j["labour_cost"], j["gross_profit"],
                 round(100 * j["gross_profit"] / j["revenue"], 1)] for j in o["jobs"] if j["month"] in fm.PERIODS]
        rows.sort(key=lambda r: (r[0] != "2026-09", r[2], r[1]))
        return "Jobs, September and August 2026", head, rows
    if org == "services":
        head = ["Month", "Engagement", "Type", "Description", "Hours", "Revenue", "Billed", "Contractors",
                "Consultant time cost", "Contribution", "Margin %"]
        rows = [[x["month"], x["code"], x["type"], x["description"], x["hours"], x["revenue"], x["billed"], x["contractors"],
                 x["allocated_cost"], x["contribution"], round(100 * x["contribution"] / x["revenue"], 1)] for x in o["engagements"]]
        rows.sort(key=lambda r: (r[0] != "2026-09", r[1]))
        return "Client engagements, September and August 2026", head, rows
    head = ["Grant", "Program", "Funder", "Total", "Start", "End", "Received to date", "Spent to date", "Spent Aug", "Spent Sep",
            "Budget to date", "Spend vs budget %", "Still to spend", "Months left"]
    rows = [[g["code"], g["program"], g["funder"], g["total"], g["start"], g["end"], g["received_to_date"], g["spent_to_date"],
             g["spent_aug"], g["spent_sep"], g["budget_to_date"], g["spend_vs_budget_pct"], g["unspent"], g["months_left"]] for g in o["grants"]]
    return "Grants at 30 September 2026", head, rows


def pdf_detail_rows(org, v):
    """Shorter list for the PDF: September only, call-outs rolled into one line."""
    title, head, rows = detail_table(org, v)
    if org == "nfp":
        return title, head, rows
    sep = [r for r in rows if r[0] == "2026-09"]
    if org == "trades":
        calls = [r for r in sep if r[2] == "Call-out"]
        sep = [r for r in sep if r[2] != "Call-out"]
        tot = lambda i: sum(r[i] for r in calls)
        sep.append(["2026-09", "C-09xx", "Call-out", f"{len(calls)} call-outs (each one is in the Excel and CSV)", "", "",
                    tot(6), tot(7), tot(8), tot(9), tot(10), tot(11), round(100 * tot(11) / tot(6), 1)])
        keep = [1, 2, 3, 6, 7, 8, 10, 11, 12]
    else:
        keep = [1, 2, 3, 4, 5, 6, 7, 9, 10]
    return title.replace(", September and August", ", September"), [head[i] for i in keep], [[r[i] for i in keep] for r in sep]


# =============================================================== CSV rows

def csv_tables(res):
    st, kp, asm = [], [], []
    for org in ORDER:
        v = res[org]
        for skey, s in statements(org, v).items():
            for i, rw in enumerate(s["rows"], 1):
                if rw["values"] is None:
                    continue
                for period, val in zip(fm.PERIODS, rw["values"]):
                    st.append([org, skey, s["title"], i, rw["label"], rw["level"], period, val])
        for k in v["fourth"]["kpis"]:
            kp.append([org, k["label"], k["value"], k["sub"]])
        for group, items in v["assumptions"]:
            for item, val in items:
                asm.append([org, group, item, val])
    return {
        "model_statements": ("Home-page dashboard: month-end P&L / income and expenditure, balance sheet and cash flow for the three sample organisations, September 2026 and August 2026, whole dollars. Costs and outflows are negative. level = detail/subtotal/total/key.",
                             ["org", "statement_key", "statement", "line_order", "line", "level", "period", "amount_aud"], st),
        "model_fourth_sheet_kpis": ("Home-page dashboard: the fourth-sheet KPI tiles for September 2026, as displayed.", ["org", "kpi", "value", "comparison"], kp),
        "model_assumptions": ("Home-page dashboard: the assumptions each sample organisation's statements are built from.", ["org", "assumption_group", "assumption", "value"], asm),
    }


# =============================================================== Excel

THIN = Side(style="thin", color=LINE)
DOUBLE = Side(style="double", color=INK)
NUM = '#,##0;(#,##0);"-"'


def xl_statement(ws, title, subtitle, rows, start_row=1):
    ws.cell(start_row, 1, title).font = Font(bold=True, size=14, color=INK)
    ws.cell(start_row + 1, 1, subtitle).font = Font(italic=True, size=9, color=MUTED)
    hr = start_row + 3
    for c, h in enumerate(["$"] + fm.COLUMNS + ["Change"], 1):
        cell = ws.cell(hr, c, h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=GREEN)
        cell.alignment = Alignment(horizontal="left" if c == 1 else "right")
    r = hr + 1
    for rw in rows:
        a = ws.cell(r, 1, rw["label"])
        if rw["level"] == "heading":
            a.font = Font(bold=True, color=GREEN)
        else:
            for c, val in enumerate(rw["values"] + [f"=B{r}-C{r}"], 2):
                cell = ws.cell(r, c, val)
                cell.number_format = NUM
                cell.alignment = Alignment(horizontal="right")
                if c == 4:
                    cell.font = Font(italic=True, color=MUTED)
            if rw["level"] == "detail":
                a.alignment = Alignment(indent=1)
                a.font = Font(color=MUTED)
            else:
                for c in range(1, 5):
                    ws.cell(r, c).font = Font(bold=True, color=GREEN if rw["level"] == "key" else INK)
                    ws.cell(r, c).border = Border(top=THIN, bottom=DOUBLE if rw["level"] == "key" else None)
                if rw["level"] == "key":
                    for c in range(1, 5):
                        ws.cell(r, c).fill = PatternFill("solid", fgColor=SOFT)
        r += 1
    return r


def write_xlsx(org, v):
    wb = Workbook()
    name = v["model"]["long_name"]
    sub = f"{name} · SAMPLE DATA (invented) · The Fourth Sheet · generated {date.today().isoformat()}"
    f4 = v["fourth"]

    ws = wb.active
    ws.title = "The fourth sheet"
    ws["A1"] = "The fourth sheet: September 2026 vs August 2026"
    ws["A1"].font = Font(bold=True, size=14, color=INK)
    ws["A2"] = sub
    ws["A2"].font = Font(italic=True, size=9, color=MUTED)
    r = 4
    for k in f4["kpis"]:
        ws.cell(r, 1, k["label"]).font = Font(color=MUTED)
        ws.cell(r, 2, k["value"]).font = Font(bold=True, size=12, color=GREEN if k.get("spine") else INK)
        ws.cell(r, 3, k["sub"]).font = Font(size=9, color=MUTED)
        r += 1
    r += 1
    ch = f4["chart"]
    ws.cell(r, 1, ch["title"]).font = Font(bold=True, color=INK)
    for lab, val in zip(ch["labels"], ch["values"]):
        r += 1
        ws.cell(r, 1, lab)
        ws.cell(r, 2, val).number_format = "0.0" if isinstance(val, float) else "0"
    if ch.get("target") is not None:
        r += 1
        ws.cell(r, 1, "Target").font = Font(italic=True, color=MUTED)
        ws.cell(r, 2, ch["target"])
    ws.column_dimensions["A"].width = 44
    for col in "BCD":
        ws.column_dimensions[col].width = 16

    for key, s in statements(org, v).items():
        w = wb.create_sheet(s["tab"].replace("&", "and"))
        xl_statement(w, s["title"], sub, s["rows"])
        w.column_dimensions["A"].width = 46
        for col in "BCD":
            w.column_dimensions[col].width = 14
        w.freeze_panes = "B5"
        w.page_setup.orientation = "portrait"
        w.page_setup.fitToWidth = 1
        w.sheet_properties.pageSetUpPr.fitToPage = True

    title, head, rows = detail_table(org, v)
    w = wb.create_sheet({"trades": "Jobs", "services": "Engagements", "nfp": "Grants"}[org])
    w["A1"] = title
    w["A1"].font = Font(bold=True, size=14, color=INK)
    w["A2"] = sub
    w["A2"].font = Font(italic=True, size=9, color=MUTED)
    for c, h in enumerate(head, 1):
        cell = w.cell(4, c, h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=GREEN)
        cell.alignment = Alignment(horizontal="left" if isinstance(rows[0][c - 1], str) else "right", wrap_text=True)
        w.column_dimensions[get_column_letter(c)].width = 36 if h in ("Description", "Program", "Funder") else 13
    for r, rw in enumerate(rows, 5):
        for c, val in enumerate(rw, 1):
            cell = w.cell(r, c, val)
            if isinstance(val, (int, float)):
                cell.number_format = "0.0" if "%" in head[c - 1] else ("#,##0.0" if "hours" in head[c - 1].lower() and isinstance(val, float) else NUM)
    w.freeze_panes = "C5"
    w.auto_filter.ref = f"A4:{get_column_letter(len(head))}{len(rows) + 4}"

    w = wb.create_sheet("Assumptions")
    w["A1"] = "Assumptions"
    w["A1"].font = Font(bold=True, size=14, color=INK)
    w["A2"] = sub
    w["A2"].font = Font(italic=True, size=9, color=MUTED)
    r = 4
    for group, items in v["assumptions"]:
        w.cell(r, 1, group).font = Font(bold=True, color=GREEN)
        r += 1
        for item, val in items:
            w.cell(r, 1, item).alignment = Alignment(indent=1, vertical="top")
            w.cell(r, 2, val).alignment = Alignment(wrap_text=True, vertical="top")
            r += 1
        r += 1
    w.cell(r, 1, "Checks (all passed)").font = Font(bold=True, color=GREEN)
    for c in checks(org):
        r += 1
        w.cell(r, 1, "✓ " + c)
    w.column_dimensions["A"].width = 40
    w.column_dimensions["B"].width = 70

    EXPORTS.mkdir(parents=True, exist_ok=True)
    wb.save(EXPORTS / f"{org}-sample-statements.xlsx")


# =============================================================== PDF

def html_report(org, v):
    esc = lambda s: str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    fmt = lambda n: f"({abs(n):,})" if n < 0 else (f"{n:,}" if n else "-")

    def stmt(s):
        out = [f"<h2>{esc(s['title'])}</h2><table><tr><th>$</th>" + "".join(f"<th class=n>{c}</th>" for c in fm.COLUMNS + ["Change"]) + "</tr>"]
        for rw in s["rows"]:
            if rw["values"] is None:
                out.append(f"<tr class=heading><td colspan=4>{esc(rw['label'])}</td></tr>")
            else:
                out.append(f"<tr class={rw['level']}><td>{esc(rw['label'])}</td>" + "".join(f"<td class=n>{fmt(x)}</td>" for x in rw["values"] + [rw["values"][0] - rw["values"][1]]) + "</tr>")
        return "".join(out) + "</table>"

    f4 = v["fourth"]
    kpis = "".join(f"<div class=kpi><span>{esc(k['label'])}</span><b>{esc(k['value'])}</b><em>{esc(k['sub'])}</em></div>" for k in f4["kpis"])
    dtitle, dhead, drows = pdf_detail_rows(org, v)
    cellv = lambda c: fmt(c) if isinstance(c, int) else (f"{c:,.1f}" if isinstance(c, float) else c)
    num = lambda c: isinstance(c, (int, float))
    tbl = "<table class=detail-list><tr>" + "".join(f"<th{' class=n' if num(drows[0][i]) else ''}>{esc(h)}</th>" for i, h in enumerate(dhead)) + "</tr>" + \
          "".join("<tr>" + "".join(f"<td{' class=n' if num(c) else (' class=w' if len(str(c)) > 14 else '')}>{esc(cellv(c))}</td>" for c in rw) + "</tr>" for rw in drows) + "</table>"
    ch = f4["chart"]
    mx = max(ch["values"] + ([ch["target"]] if ch.get("target") else []))
    mx *= 1.15
    below = lambda x: ch.get("target") is not None and x < ch["target"]
    bars = "".join(f"<div class=bar><i class='{'below' if below(x) else ''}' style='height:{100 * x / mx:.1f}%'><b>{x:.0f}%</b></i><span>{esc(l)}</span></div>" for l, x in zip(ch["labels"], ch["values"]))
    target = f"<div class=target style='bottom:calc({100 * ch['target'] / mx:.1f}% * 0.8 + 18px)'></div>" if ch.get("target") else ""
    assum = "".join(f"<h3>{esc(g)}</h3><table class=assum>" + "".join(f"<tr><td>{esc(a)}</td><td>{esc(b)}</td></tr>" for a, b in items) + "</table>" for g, items in v["assumptions"])
    st = statements(org, v)
    return f"""<!doctype html><html><head><meta charset=utf-8>
<link rel=stylesheet href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap">
<style>
@page {{ size: A4; margin: 16mm 14mm; }}
body {{ font-family: Inter, Arial, sans-serif; color: #25342a; font-size: 10.5pt; }}
header {{ display: flex; align-items: center; gap: 10px; border-bottom: 3px solid #2f7a5d; padding-bottom: 8px; margin-bottom: 12px; }}
.mark {{ min-width: 30px; height: 30px; padding: 0 4px; border-radius: 7px; background: #2f7a5d; color: #fff; font-weight: 800; display: flex; align-items: center; justify-content: center; font-size: 15px; }} .mark sup, header b sup {{ font-size: 0.55em; }}
header b {{ font-size: 13pt; }} header small {{ margin-left: auto; color: #5f6f63; }}
h1 {{ font-size: 17pt; margin: 6px 0 2px; }} .about {{ color: #5f6f63; margin: 0 0 10px; }}
.sample {{ display: inline-block; background: #fff4dc; border: 1px solid #d9922b; color: #8a5410; border-radius: 4px; padding: 2px 8px; font-size: 8.5pt; font-weight: 700; }}
h2 {{ font-size: 12.5pt; color: #2f7a5d; margin: 16px 0 6px; }} h3 {{ font-size: 10.5pt; margin: 10px 0 4px; color: #2f7a5d; }}
table {{ width: 100%; border-collapse: collapse; page-break-inside: avoid; }} th {{ text-align: left; background: #2f7a5d; color: #fff; padding: 4px 6px; font-size: 9pt; }}
td {{ padding: 3px 6px; border-bottom: 1px solid #eef2ee; }} .n {{ text-align: right; font-variant-numeric: tabular-nums; }}
tr.heading td {{ font-weight: 700; color: #2f7a5d; padding-top: 7px; border: 0; }} tr.detail td:first-child {{ padding-left: 16px; color: #5f6f63; }}
tr.subtotal td, tr.total td {{ font-weight: 700; border-top: 1px solid #9db8a6; }} tr.total td {{ border-bottom: 1px solid #25342a; }}
tr.key td {{ font-weight: 800; background: #eaf6ee; border-top: 1px solid #25342a; border-bottom: 3px double #25342a; color: #1f5a43; }}
.kpis {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }} .kpi {{ border: 1px solid #dce8dc; border-radius: 6px; padding: 7px; }}
.kpi span, .kpi em {{ display: block; font-size: 8.5pt; color: #5f6f63; font-style: normal; }} .kpi b {{ display: block; font-size: 15pt; color: #2f7a5d; }}
.chart {{ position: relative; height: 150px; display: flex; align-items: flex-end; gap: 6px; border-bottom: 1px solid #dce8dc; padding-bottom: 18px; }}
.bar {{ flex: 1; height: 80%; display: flex; flex-direction: column; justify-content: flex-end; align-items: center; position: relative; }}
.bar i {{ display: block; width: 70%; background: #2f7a5d; border-radius: 2px 2px 0 0; position: relative; }} .bar i.below {{ background: #d9922b; }}
.bar i b {{ position: absolute; top: -14px; left: 0; right: 0; text-align: center; font-size: 8pt; color: #25342a; }}
.detail-list {{ font-size: 8.5pt; }} .detail-list td {{ white-space: nowrap; }} .detail-list td.w {{ white-space: normal; min-width: 110px; }}
@page wide {{ size: A4 landscape; margin: 14mm; }} .wide {{ page: wide; }}
.legend .tl {{ display: inline-block; width: 16px; border-top: 2px dashed #d9922b; vertical-align: middle; margin-right: 4px; }} .legend {{ font-size: 8pt; color: #5f6f63; margin: 4px 0 0; }} .legend i {{ display: inline-block; width: 9px; height: 9px; background: #d9922b; margin-right: 4px; }}
.bar span {{ position: absolute; bottom: -16px; font-size: 8pt; color: #5f6f63; }}
.target {{ position: absolute; left: 0; right: 0; border-top: 2px dashed #d9922b; font-size: 8pt; color: #8a5410; text-align: right; }}
.two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }} .page {{ page-break-before: always; }}
.assum td:first-child {{ width: 40%; color: #5f6f63; }} .checks li {{ margin: 2px 0; }}
footer {{ margin-top: 14px; font-size: 8pt; color: #5f6f63; }}
</style></head><body>
<header><div class=mark>4<sup>th</sup></div><b>The 4<sup>th</sup> Sheet</b><small>Your accountant gives you three sheets. I give you the fourth.</small></header>
<span class=sample>SAMPLE DATA · invented figures for demonstration</span>
<h1>{esc(v['model']['long_name'])}</h1><p class=about>{esc(v['model']['about'])}</p>
<h2>The fourth sheet: September 2026 vs August 2026</h2><div class=kpis>{kpis}</div>
<h3>{esc(ch['title'])}</h3><div class=chart>{bars}{target}</div><p class=legend><i></i>Below target &nbsp; <span class=tl></span>Target {ch.get('target')}%</p>
<div class="page wide"><h2>{esc(dtitle)}</h2>{tbl}</div>
<div class=page>{stmt(st['pnl'])}</div>
<div class=page>{stmt(st['bs'])}</div>
<div class=page>{stmt(st['cf'])}</div>
<div class=page><h2>Assumptions</h2>{assum}<h3>Checks (all passed)</h3><ul class=checks>{''.join(f'<li>✓ {esc(c)}</li>' for c in checks(org))}</ul>
<footer>Generated {date.today().isoformat()} by a driver-based model: every figure is calculated from the assumptions above. Sample data only, not financial advice.</footer></div>
</body></html>"""


def write_pdfs(res):
    from playwright.sync_api import sync_playwright
    EXPORTS.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(channel="chrome")
        except Exception:
            browser = p.chromium.launch()
        page = browser.new_page()
        for org in ORDER:
            page.set_content(html_report(org, res[org]), wait_until="networkidle")
            page.evaluate("document.fonts.ready")
            page.pdf(path=str(EXPORTS / f"{org}-sample-statements.pdf"), format="A4", print_background=True)
        browser.close()


def publish():
    res = fm.build()  # runs every check; stops here if anything doesn't add up
    publish.res = res
    write_dashboard_js(res)
    for org in ORDER:
        write_xlsx(org, res[org])
    write_pdfs(res)
    return csv_tables(res)
