#!/usr/bin/env python3
"""
publish_dashboard.py — turns the checked financial model (financial_model.py)
into everything the website and your database use:

  dashboard-data.js                       data for the home-page dashboard
  media/exports/<org>-sample-statements.xlsx   formatted Excel workbook
  media/exports/<org>-sample-statements.pdf    A4 PDF report
  (CSV rows for sample-data/ are returned to sample_data.py)

Run via:  python3 tools/sample_data.py   (it calls this)
Needs:    pip install openpyxl playwright   (PDFs use your installed Chrome)
"""

import json
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

import financial_model as fm

REPO = Path(__file__).resolve().parent.parent
EXPORTS = REPO / "media" / "exports"
ORDER = ["trades", "services", "nfp"]
TOGGLE = {"trades": "SME · trades", "services": "SME · services", "nfp": "Not-for-profit"}
GREEN, DARK, INK, MUTED, SOFT, LINE = "2F7A5D", "1F5A43", "25342A", "5F6F63", "EAF6EE", "DCE8DC"


def statements(org, v):
    nfp = org == "nfp"
    o = v["out"]
    return {
        "pnl": {"tab": "P&L", "title": "Income and expenditure" if nfp else "Profit and loss", "rows": o["pnl"]},
        "bs": {"tab": "Balance sheet", "title": "Balance sheet at 30 June", "rows": o["bsr"]},
        "cf": {"tab": "Cash flow", "title": "Cash flow statement", "rows": o["cfr"]},
    }


def checks(org):
    nfp = org == "nfp"
    return [
        "Every subtotal and total adds up",
        "Balance sheet balances: assets = liabilities + " + ("accumulated funds" if nfp else "equity"),
        "Cash flow ends at the cash in the bank",
        ("Surplus ties to the movement in accumulated funds" if nfp else "Profit ties to retained earnings, after dividends"),
    ]


def export_paths(org):
    return {"xlsx": f"media/exports/{org}-sample-statements.xlsx", "pdf": f"media/exports/{org}-sample-statements.pdf"}


def dashboard_payload(res):
    orgs = []
    for org in ORDER:
        v = res[org]
        f4 = v["fourth"]
        orgs.append({
            "id": org, "toggle": TOGGLE[org], "name": v["model"]["long_name"], "about": v["model"]["about"],
            "columns": fm.FY, "unit": "$'000",
            "statements": statements(org, v),
            "fourth": {"kpis": f4["kpis"], "chart": f4["chart"], "table": f4["table"]},
            "checks": checks(org), "assumptions": v["assumptions"], "exports": export_paths(org),
        })
    return {"generated": date.today().isoformat(), "orgs": orgs}


def write_dashboard_js(res):
    payload = dashboard_payload(res)
    js = ("/* dashboard-data.js — GENERATED by tools/sample_data.py from tools/financial_model.py.\n"
          "   Don't edit by hand: change the assumptions in financial_model.py and re-run.\n"
          "   All figures are invented sample data, in $'000 unless labelled. */\n"
          "window.FOURTH_SHEET_DASHBOARD = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n")
    (REPO / "dashboard-data.js").write_text(js)


# =============================================================== CSV rows

def csv_tables(res):
    st, kp, mo, asm = [], [], [], []
    for org in ORDER:
        v = res[org]
        for skey, s in statements(org, v).items():
            for i, rw in enumerate(s["rows"], 1):
                if rw["values"] is None:
                    continue
                for fy, val in zip(fm.FY, rw["values"]):
                    st.append([org, s["title"], i, rw["label"], rw["level"], fy, val])
        for k in v["fourth"]["kpis"]:
            kp.append([org, k["label"], k["value"], k["sub"]])
        for measure, vals in v["fourth"]["monthly"].items():
            for mth, val in zip(fm.MONTHS, vals):
                mo.append([org, "FY2026", mth, measure, val])
        for group, items in v["assumptions"]:
            for item, val in items:
                asm.append([org, group, item, val])
    return {
        "model_statements": ("Home-page dashboard: P&L / income and expenditure, balance sheet and cash flow for the three sample organisations, FY2026 and FY2025, $'000. Costs and outflows are negative. level = detail/subtotal/total/key.",
                             ["org", "statement", "line_order", "line", "level", "financial_year", "amount_aud_k"], st),
        "model_fourth_sheet_kpis": ("Home-page dashboard: the fourth-sheet KPI tiles, as displayed.", ["org", "kpi", "value", "comparison"], kp),
        "model_monthly": ("Home-page dashboard: monthly drivers behind the fourth-sheet charts, FY2026 (sum to the annual figures).",
                          ["org", "financial_year", "month", "measure", "value"], mo),
        "model_assumptions": ("Home-page dashboard: the assumptions each sample organisation's statements are built from.", ["org", "assumption_group", "assumption", "value"], asm),
    }


# =============================================================== Excel

THIN = Side(style="thin", color=LINE)
DOUBLE = Side(style="double", color=INK)
NUM = '#,##0;(#,##0);"-"'


def xl_statement(ws, title, subtitle, rows, start_row=1):
    ws.cell(start_row, 1, title).font = Font(bold=True, size=14, color=INK)
    ws.cell(start_row + 1, 1, subtitle).font = Font(italic=True, size=9, color=MUTED)
    hr = start_row + 3
    for c, h in enumerate(["$'000"] + fm.FY, 1):
        cell = ws.cell(hr, c, h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=GREEN)
        cell.alignment = Alignment(horizontal="left" if c == 1 else "right")
    r = hr + 1
    for rw in rows:
        a = ws.cell(r, 1, rw["label"])
        if rw["level"] == "heading":
            a.font = Font(bold=True, color=GREEN)
        else:
            for c, val in enumerate(rw["values"], 2):
                cell = ws.cell(r, c, val)
                cell.number_format = NUM
                cell.alignment = Alignment(horizontal="right")
            if rw["level"] == "detail":
                a.alignment = Alignment(indent=1)
                a.font = Font(color=MUTED)
            else:
                for c in range(1, 4):
                    ws.cell(r, c).font = Font(bold=True, color=GREEN if rw["level"] == "key" else INK)
                    ws.cell(r, c).border = Border(top=THIN, bottom=DOUBLE if rw["level"] == "key" else None)
                if rw["level"] == "key":
                    for c in range(1, 4):
                        ws.cell(r, c).fill = PatternFill("solid", fgColor=SOFT)
        r += 1
    return r


def write_xlsx(org, v):
    wb = Workbook()
    name = v["model"]["long_name"]
    sub = f"{name} · SAMPLE DATA (invented) · The Fourth Sheet · generated {date.today().isoformat()}"
    f4 = v["fourth"]

    ws = wb.active
    ws.title = "The fourth sheet"
    ws["A1"] = "The fourth sheet: the numbers underneath"
    ws["A1"].font = Font(bold=True, size=14, color=INK)
    ws["A2"] = sub
    ws["A2"].font = Font(italic=True, size=9, color=MUTED)
    r = 4
    for k in f4["kpis"]:
        ws.cell(r, 1, k["label"]).font = Font(color=MUTED)
        ws.cell(r, 2, k["value"]).font = Font(bold=True, size=12, color=GREEN if k.get("spine") else INK)
        ws.cell(r, 3, k["sub"]).font = Font(size=9, color=MUTED)
        r += 1
    r += 1
    t = f4["table"]
    ws.cell(r, 1, t["title"]).font = Font(bold=True, color=INK)
    r += 1
    for c, h in enumerate(t["head"], 1):
        cell = ws.cell(r, c, h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=GREEN)
    for rw in t["rows"] + [t["total"]]:
        r += 1
        for c, val in enumerate(rw, 1):
            cell = ws.cell(r, c, val)
            if isinstance(val, (int, float)):
                cell.number_format = NUM
        if rw is t["total"]:
            for c in range(1, len(rw) + 1):
                ws.cell(r, c).font = Font(bold=True)
                ws.cell(r, c).border = Border(top=THIN, bottom=DOUBLE)
    r += 2
    ch = f4["chart"]
    ws.cell(r, 1, ch["title"]).font = Font(bold=True, color=INK)
    for lab, val in zip(ch["labels"], ch["values"]):
        r += 1
        ws.cell(r, 1, lab)
        ws.cell(r, 2, val).number_format = "0.0" if isinstance(val, float) else "0"
    if ch.get("target") is not None:
        r += 1
        ws.cell(r, 1, "Target").font = Font(italic=True, color=MUTED)
        ws.cell(r, 2, ch["target"])
    ws.column_dimensions["A"].width = 44
    for col in "BCD":
        ws.column_dimensions[col].width = 16

    for key, s in statements(org, v).items():
        w = wb.create_sheet(s["tab"].replace("&", "and"))
        xl_statement(w, s["title"], sub, s["rows"])
        w.column_dimensions["A"].width = 46
        w.column_dimensions["B"].width = w.column_dimensions["C"].width = 14
        w.freeze_panes = "B5"
        w.page_setup.orientation = "portrait"
        w.page_setup.fitToWidth = 1
        w.sheet_properties.pageSetUpPr.fitToPage = True

    w = wb.create_sheet("Assumptions")
    w["A1"] = "Assumptions"
    w["A1"].font = Font(bold=True, size=14, color=INK)
    w["A2"] = sub
    w["A2"].font = Font(italic=True, size=9, color=MUTED)
    r = 4
    for group, items in v["assumptions"]:
        w.cell(r, 1, group).font = Font(bold=True, color=GREEN)
        r += 1
        for item, val in items:
            w.cell(r, 1, item).alignment = Alignment(indent=1, vertical="top")
            w.cell(r, 2, val).alignment = Alignment(wrap_text=True, vertical="top")
            r += 1
        r += 1
    w.cell(r, 1, "Checks (all passed)").font = Font(bold=True, color=GREEN)
    for c in checks(org):
        r += 1
        w.cell(r, 1, "✓ " + c)
    w.column_dimensions["A"].width = 40
    w.column_dimensions["B"].width = 70

    EXPORTS.mkdir(parents=True, exist_ok=True)
    wb.save(EXPORTS / f"{org}-sample-statements.xlsx")


# =============================================================== PDF

def html_report(org, v):
    esc = lambda s: str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    fmt = lambda n: f"({abs(n):,})" if n < 0 else (f"{n:,}" if n else "-")

    def stmt(s):
        out = [f"<h2>{esc(s['title'])}</h2><table><tr><th>$'000</th>" + "".join(f"<th class=n>{c}</th>" for c in fm.FY) + "</tr>"]
        for rw in s["rows"]:
            if rw["values"] is None:
                out.append(f"<tr class=heading><td colspan=3>{esc(rw['label'])}</td></tr>")
            else:
                out.append(f"<tr class={rw['level']}><td>{esc(rw['label'])}</td>" + "".join(f"<td class=n>{fmt(x)}</td>" for x in rw["values"]) + "</tr>")
        return "".join(out) + "</table>"

    f4 = v["fourth"]
    kpis = "".join(f"<div class=kpi><span>{esc(k['label'])}</span><b>{esc(k['value'])}</b><em>{esc(k['sub'])}</em></div>" for k in f4["kpis"])
    t = f4["table"]
    tbl = "<table><tr>" + "".join(f"<th{' class=n' if i else ''}>{esc(h)}</th>" for i, h in enumerate(t["head"])) + "</tr>" + \
          "".join("<tr>" + "".join(f"<td{' class=n' if i else ''}>{esc(fmt(c) if isinstance(c, int) else c)}</td>" for i, c in enumerate(rw)) + "</tr>" for rw in t["rows"]) + \
          "<tr class=total>" + "".join(f"<td{' class=n' if i else ''}>{esc(fmt(c) if isinstance(c, int) else c)}</td>" for i, c in enumerate(t["total"])) + "</tr></table>"
    ch = f4["chart"]
    mx = max(ch["values"] + ([ch["target"]] if ch.get("target") else []))
    bars = "".join(f"<div class=bar><i style='height:{100 * x / mx:.1f}%'></i><span>{esc(l)}</span></div>" for l, x in zip(ch["labels"], ch["values"]))
    target = f"<div class=target style='bottom:calc({100 * ch['target'] / mx:.1f}% * 0.8 + 18px)'>Target {ch['target']}</div>" if ch.get("target") else ""
    assum = "".join(f"<h3>{esc(g)}</h3><table class=assum>" + "".join(f"<tr><td>{esc(a)}</td><td>{esc(b)}</td></tr>" for a, b in items) + "</table>" for g, items in v["assumptions"])
    st = statements(org, v)
    return f"""<!doctype html><html><head><meta charset=utf-8>
<link rel=stylesheet href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap">
<style>
@page {{ size: A4; margin: 16mm 14mm; }}
body {{ font-family: Inter, Arial, sans-serif; color: #25342a; font-size: 10.5pt; }}
header {{ display: flex; align-items: center; gap: 10px; border-bottom: 3px solid #2f7a5d; padding-bottom: 8px; margin-bottom: 12px; }}
.mark {{ min-width: 30px; height: 30px; padding: 0 4px; border-radius: 7px; background: #2f7a5d; color: #fff; font-weight: 800; display: flex; align-items: center; justify-content: center; font-size: 15px; }} .mark sup, header b sup {{ font-size: 0.55em; }}
header b {{ font-size: 13pt; }} header small {{ margin-left: auto; color: #5f6f63; }}
h1 {{ font-size: 17pt; margin: 6px 0 2px; }} .about {{ color: #5f6f63; margin: 0 0 10px; }}
.sample {{ display: inline-block; background: #fff4dc; border: 1px solid #d9922b; color: #8a5410; border-radius: 4px; padding: 2px 8px; font-size: 8.5pt; font-weight: 700; }}
h2 {{ font-size: 12.5pt; color: #2f7a5d; margin: 16px 0 6px; }} h3 {{ font-size: 10.5pt; margin: 10px 0 4px; color: #2f7a5d; }}
table {{ width: 100%; border-collapse: collapse; page-break-inside: avoid; }} th {{ text-align: left; background: #2f7a5d; color: #fff; padding: 4px 6px; font-size: 9pt; }}
td {{ padding: 3px 6px; border-bottom: 1px solid #eef2ee; }} .n {{ text-align: right; font-variant-numeric: tabular-nums; }}
tr.heading td {{ font-weight: 700; color: #2f7a5d; padding-top: 7px; border: 0; }} tr.detail td:first-child {{ padding-left: 16px; color: #5f6f63; }}
tr.subtotal td, tr.total td {{ font-weight: 700; border-top: 1px solid #9db8a6; }} tr.total td {{ border-bottom: 1px solid #25342a; }}
tr.key td {{ font-weight: 800; background: #eaf6ee; border-top: 1px solid #25342a; border-bottom: 3px double #25342a; color: #1f5a43; }}
.kpis {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }} .kpi {{ border: 1px solid #dce8dc; border-radius: 6px; padding: 7px; }}
.kpi span, .kpi em {{ display: block; font-size: 8.5pt; color: #5f6f63; font-style: normal; }} .kpi b {{ display: block; font-size: 15pt; color: #2f7a5d; }}
.chart {{ position: relative; height: 150px; display: flex; align-items: flex-end; gap: 6px; border-bottom: 1px solid #dce8dc; padding-bottom: 18px; }}
.bar {{ flex: 1; height: 80%; display: flex; flex-direction: column; justify-content: flex-end; align-items: center; position: relative; }}
.bar i {{ display: block; width: 70%; background: #9db8a6; border-radius: 2px 2px 0 0; }} .bar:last-child i {{ background: #2f7a5d; }}
.bar span {{ position: absolute; bottom: -16px; font-size: 8pt; color: #5f6f63; }}
.target {{ position: absolute; left: 0; right: 0; border-top: 2px dashed #d9922b; font-size: 8pt; color: #8a5410; text-align: right; }}
.two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }} .page {{ page-break-before: always; }}
.assum td:first-child {{ width: 40%; color: #5f6f63; }} .checks li {{ margin: 2px 0; }}
footer {{ margin-top: 14px; font-size: 8pt; color: #5f6f63; }}
</style></head><body>
<header><div class=mark>4<sup>th</sup></div><b>The 4<sup>th</sup> Sheet</b><small>Your accountant gives you three sheets. I give you the fourth.</small></header>
<span class=sample>SAMPLE DATA · invented figures for demonstration</span>
<h1>{esc(v['model']['long_name'])}</h1><p class=about>{esc(v['model']['about'])}</p>
<h2>The fourth sheet: the numbers underneath (FY2026)</h2><div class=kpis>{kpis}</div>
<h3>{esc(ch['title'])}</h3><div class=chart>{bars}{target}</div>
<h3>{esc(t['title'])}</h3>{tbl}
<div class=page>{stmt(st['pnl'])}</div>
<div class=page>{stmt(st['bs'])}</div>
<div class=page>{stmt(st['cf'])}</div>
<div class=page><h2>Assumptions</h2>{assum}<h3>Checks (all passed)</h3><ul class=checks>{''.join(f'<li>✓ {esc(c)}</li>' for c in checks(org))}</ul>
<footer>Generated {date.today().isoformat()} by a driver-based model: every figure is calculated from the assumptions above. Sample data only, not financial advice.</footer></div>
</body></html>"""


def write_pdfs(res):
    from playwright.sync_api import sync_playwright
    EXPORTS.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(channel="chrome")
        except Exception:
            browser = p.chromium.launch()
        page = browser.new_page()
        for org in ORDER:
            page.set_content(html_report(org, res[org]), wait_until="networkidle")
            page.evaluate("document.fonts.ready")
            page.pdf(path=str(EXPORTS / f"{org}-sample-statements.pdf"), format="A4", print_background=True)
        browser.close()


def publish():
    res = fm.build()  # runs every check; stops here if anything doesn't add up
    write_dashboard_js(res)
    for org in ORDER:
        write_xlsx(org, res[org])
    write_pdfs(res)
    return csv_tables(res)
